### ISSUE TITLE
Add a 'beforeTagAdded' and 'beforeTagRemoved' callback

### ISSUE THREAD

**Issue by JAndritsch** [mbenford/ngTagsInput#100]
It might be handy to implement an event that the user could bind to that gets called prior to a tag being added or removed. This way, the user could define whether or not they want the tag to be added/removed in their own way, then give them the option to abort the process by returning false or allowing it to proceed by returning true.

I actually have this featured patched in an older version of ngTagsInput (v1.1.1), but haven't found an easy way to make it work with the newer code base. It looks something like this:

```javascript
    return {
        restrict: 'E',
        require: 'ngModel',
        scope: {
            tags: '=ngModel',
            beforeTagAdded: '&',
            onTagAdded: '&',
            onTagRemoved: '&'
        },
```
 Then in the 'tryAdd' function:

```javascript
    if ($scope.beforeTagAdded({ $tag: tag })) {
        $scope.tags.push(tag);
        $scope.events.trigger('tag-added', { $tag: tag });
    }
```
The implementation for 'beforeTagRemoved' is basically the same thing. Again, not too sure how this could fit into the newer code base, but you would know best.

**Comment by LooMan91** [comment]
+1

**Comment by bezoerb** [comment]
+1

**Comment by lishner** [comment]
+1

**Comment by JAndritsch** [comment]
I see there are a lot of +1's on this. For what it's worth, I did submit a pull request to add this behavior. Hopefully it'll get merged in soon.

**Comment by pedrogusman** [comment]
+1
