### ISSUE TITLE
Support for ng-disable

### ISSUE THREAD

**Issue by Nailer** [mbenford/ngTagsInput#102]
First of all, I really like this directive. Thanks to all contributors!

I have a tiny feature request: 
Forward the ng-disable attribute down to the input field so we can disable it.

**Comment by zarno** [comment]
+1

**Comment by jukkasi** [comment]
+1

**Comment by Zyquivilly** [comment]
+1

**Comment by dales** [comment]
+1

**Comment by davidetrapani** [comment]
+1

**Comment by shukerullah** [comment]
+1

**Comment by ChillkroeteTTS** [comment]
+1

**Comment by AthenkosiM** [comment]
Is there a way to hide the text area that appears below the tags, or disable user input, pre-populate directive with tags and also be able to remove  a tag. In short a feature to only disable user input and not the whole directive.
