### ISSUE TITLE
Option to force a text case on all new tags

### ISSUE THREAD

**Issue by mbenford** [mbenford/ngTagsInput#120]
It would be nice to have some way to force a given case on all tags (uppercase, lowercase and none).

**Comment by etaiklein** [comment]
It would be awesome to add a way to force inflection as well...
titleize
singularize
pluralize
etc.

**Comment by mbenford** [comment]
The proposed behavior can be easily achieved by using the `onTagAdded` option, so there's no need to bake it into the directive's code.
