### ISSUE TITLE
Autocomplete with resource

### ISSUE THREAD

**Issue by cranesandcaff** [mbenford/ngTagsInput#129]
I believe this is very similar to Issue #127, I have

```
$scope.loadTags = function(query) { 
   return $http.get('tags');
};
```

My backend has a /tags/ route that returns an array and that part is being served up but I am getting the same undefined method 'then'. I'm not sure if I am using $http.get incorrectly as it seems to be straight out of the documentation? 

From my title, I have this set up as a $resource inside of a factory, would I need to follow the same directive change in order to make this work or am I using it wrong all together?

**Comment by phuyem** [comment]
Just to summarize my 2 hours of digging the internet for this $promise  : 

1) With http: just return $http('whatever')  ;
2) but with resource : yourRestApi.query().**$promise** , without $promise, things are still working good, just no suggestion dropdown, which may give your hours of pains debugging
