### ISSUE TITLE
transcludeFn is `undefined` at `tiTranscludeAppend` directive.

### ISSUE THREAD

**Issue by mr-moon** [mbenford/ngTagsInput#133]
![](http://cl.ly/image/3v203Q0A3e14/Screen%20Shot%202014-04-22%20at%2015.30.10.png)

... and that rises `TypeError: undefined is not a function` error.

**Comment by adiroiban** [comment]
I am still using an old angular version 1.1.5 ... i have disabled the directive and it still works

```
var tagsInput = angular.module('ngTagsInput')
tagsInput.factory('tiTranscludeAppendDirective', function() {
    return function() {}
})
```
