### ISSUE TITLE
feature: add options to only show matching tags on autocomplete

### ISSUE THREAD

**Issue by funkjunky** [mbenford/ngTagsInput#134]
Honestly, I'm confused. I have NEVER seen an autocomplete that shows every option and simply highlights what the text matches. This kind of autocomplete is completely useless.

There should be an option to enable disabling options that aren't matched by the entered text. This would also mean that the down and up arrows gain greater meaning, and further would allow the potential for a tab or other key input to choose the only remaining options in the options.

Such a nice module missing such a key feature. I'll see if I can fork and add it.
Was this a design decision, or did no one actually think to add this?

**Comment by sushiladokar** [comment]
Hello,

Is there any way to see only the matched values in list.
Its of no use otherwise :(

**Comment by bobzhang199102** [comment]
@funkjunky , do you find a way to see only the matched values in list?

**Comment by Sayan-Paul** [comment]
The autocomplete should only show the list of matched guys or other guys only in case of no match. 
Current feature is very futile as "autocomplete" feature as we sometimes even do not see the matched terms as they are lost.
