### ISSUE TITLE
Allow nested property for display-property

### ISSUE THREAD

**Issue by mbenford** [mbenford/ngTagsInput#159]
See #158 for more information.

**Comment by MHaendel** [comment]
This feature would be really cool. Theres no way I can use this without nested properties.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
