### ISSUE TITLE
Different binding for "," — comma key.

### ISSUE THREAD

**Issue by cre-o** [mbenford/ngTagsInput#162]
In case of english keyboard, all working, as expected.
But for users with different languages there is a problem, that on place of comma can be another letter.
Example: russian "б"
Maybe it should bind not keyCodes, but exactly symbols?

Btw, many thanks for this directive!

**Comment by kotmatpockuh** [comment]
same issue! , is not binding in russian keyboard

**Comment by AlexanderKozhevin** [comment]
👍 I'lve got this issue tooo

**Comment by terpenoid** [comment]
same issue.
now i find a temporary solution: add-on-comma="false".
russian "б" is worked, but entering "," not add entered text as new tag...

**Comment by AlexanderKozhevin** [comment]
I fixed the stuff manually within [the code](https://github.com/AlexanderKozhevin/ngTagsInput/commit/7ad898979deaa14a3c368cd965b72458de703431).

**Comment by boo-ga-ga** [comment]
Unfortunately, the previous fix doesn't work for me, so I have made another change [here](https://github.com/boo-ga-ga/ngTagsInput/commit/5d6792e64cbad58214da15d63a890f679d1c76d9).
