### ISSUE TITLE
Multiple tag inputs within single form

### ISSUE THREAD

**Issue by vredchenko** [mbenford/ngTagsInput#169]
Hi. 
Thank You for this widget - does exactly what I need!

I've added two tag inputs on my page, each with their separate model:

http://hack.management/#/edit-project/new

The first one works as expected, while if I try clicking within the second tag input to add a new tag - the caret activates on the first input element and goes red (suggesting an invalid state?)

How do I isolate the two inputs from each other? 
Am I missing something very basic?

**Comment by sprakashg** [comment]
it doesn't work if I use with autocomplete. here is an example and the error in console.
"TypeError: a.filter is not a function"
                <label class="control-label pull-left" style="padding: 10px;line-height: 30px;" ng-show=" promo_action_option =='Sale'">Link to a Sale</label>
                          <tags-input ng-model="tags" placeholder="Link to a sale" display-property="label" on-tag-added="tagAdded($tag)" on-tag-removed="tagRemoved($tag)" ng-show=" promo_action_option =='Sale'" style="margin-top:5px;" id="id1">
                          <auto-complete source="loadTags($query)"></auto-complete>
                          </tags-input>
                          </p>

                          <p>

                            <label class="control-label pull-left" style="padding: 10px;line-height: 15px;" ng-show="promo_action_option =='Category'">Link to a Category</label>
                            <tags-input ng-model="sales" placeholder="Link to a Category" display-property="label" ng-show=" promo_action_option =='Category'" style="margin-top:5px;"  id="id2">
                              <auto-complete source="loadSales($query)"></auto-complete>
                            </tags-input>
