### ISSUE TITLE
can 'display-property' be a getter/setter function?

### ISSUE THREAD

**Issue by TomKuhn** [mbenford/ngTagsInput#194]
AngularJS have just added a feature in 1.3.0-beta.15 that allows ng-model to databind to getters and setters. I have an issue using ngTagsInput where the display value on the tags object is not readily available on the object - all I have is an id field, and the display text needs to be looked up. If ngTags input could see that the display-property was a function and called it, this would be very helpful.

When you add a tag, it would call the same function but pass the tag's text as the first parameter.

**Comment by Adhara3** [comment]
I vote for this feature too.
My use case: I receive a bunch of "filter" objects, each of them has different options and the filter itself should specify the field to be used to find the display name. Example:

    $scope.filters = [
        {
          name: 'Status',
          options: [
            {text: 'Active'},
            {text: 'Completed'},
           {text: 'Closed'},
          ],
          tag: 'text'
        },
        {
          name: 'Region',
          options: [
            {id: 1, region: 'North America'},
            {id: 2, region: 'Latin America'},
            {id: 3, region: 'Europe'},
          ],
          tag: 'text'
        }
       ];

and in the HTML:

     <tags-input ng-model="currentCriteria" display-property="{{currentFilter.tag}}" [...]

When a user selects a filter, `currentFilter` is populated and the tag list and autocomplete get automatically filled, so they are dynamic.
Of course, I used `{{currentFilter.tag}}` but having something like `getDisplayProperty()` would work.

Thanks
Andrea

**Comment by jukkasi** [comment]
+1 what I said in https://github.com/mbenford/ngTagsInput/issues/504

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
