### ISSUE TITLE
ng-change directive not working with tags-input

### ISSUE THREAD

**Issue by mazurroman** [mbenford/ngTagsInput#197]
```
<tags-input ng-model="tags" ng-change="onChange()"></tags-input>
```

The onChange() method is not called when the "tags" model changes.

**Comment by robtcallahan** [comment]
For whatever reason, the on-tag-added and on-tag-removed is not working. Here is my html:

        <tags-input ng-model="server.ldapUserGroups"
                    class="col-lg-12"
                    key-property="name"
                    display-property="name"
                    placeholder="Add a group"
                    length="50"
                    on-tag-added="checkFields('groups');"
                    on-tag-removed="checkFields('groups');"
                    add-from-autocomplete-only="true">
            <auto-complete
                   source="loadLdapUserGroups($query)"
                   display-property="name">
            </auto-complete>
        </tags-input>

what am I doing wrong?

**Comment by LoganBarnett** [comment]
@robtcallahan do you have a plunkr demonstrating this? At a glance this looks ok.

**Comment by Uncle-Bens** [comment]
how a can watch current printing tag?

**Comment by fresjitendra** [comment]
i have faced same issue  so you can use ngKeyup instead of ngChange .it will work fine

**Comment by obahareth** [comment]
I tried making a simple example based on [this comment](https://github.com/mbenford/ngTagsInput/issues/197#issuecomment-49781659) I'm having issues with these as well, they always seem to lag behind, I am always getting the ngModel how it was before the latest event, it looks like this event happens before the ngModel is updated. 

Here's how my code looks like

```html
<tags-input ng-model="firstCtrl.tags" 
            on-tag-added="otherCtrl.tagChanged(tags)" 
            on-tag-removed="otherCtrl.tagChanged(tags)">
</tags-input>
```

I'm trying to get the list of tags to stay updated on another controller.

**Comment by vidstige** [comment]
@obahareth I was able to solve this by removing `use-strings="true"`. It's marked as "experimental" after all.
