### ISSUE TITLE
displayProperty option is not taken in account by the autocomplete ng-repeat tracking

### ISSUE THREAD

**Issue by reda-alaoui** [mbenford/ngTagsInput#198]
Hi,

It seems that the displayProperty that we can define in the tags-input element is not taken into account by the autocomplete ng-repeat tracking.

```
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. 
Use 'track by' expression to specify unique keys. 
Repeater: item in suggestionList.items track by track(item), Duplicate key: undefined
```

**Comment by jancel** [comment]
Can you explain? I'm running across similar issue. @reda-alaoui

**Comment by abbish** [comment]
@jancel @reda-alaoui 
I'm miss the issue also !

**Comment by reda-alaoui** [comment]
I am sorry guys, I searched but I can't find what I was doing wrong.
I don't remember :(
