### ISSUE TITLE
Let the autocomplete list open w/ loadOnFocus

### ISSUE THREAD

**Issue by root-io** [mbenford/ngTagsInput#205]
Hello, I'm using this:

    <tags-input ng-model="tags">
        <auto-complete source="loadTags($query)" load-on-empty="true" load-on-focus="true" load-on-down-arrow="true"></auto-complete>
    </tags-input>

Is there a way to let the autocomplete list open after selecting an element on the list ? Thanks

edit: Ok, it's not good for UX because the user have to click outside to close the autocomplete.
Lose the input's focus or add a close button on the right top of the autocomplete seems better.

**Comment by root-io** [comment]
Hello there, the patch provided by @offsky works well, thanks

**Comment by DharmendraVaishnav91** [comment]
I

**Comment by DharmendraVaishnav91** [comment]
I used ngTagsInput in ionic mobile app but there is issue in showing autocomplete suggestion list, suggestion list hides when click on back button. Is there method to prevent this one ?

**Comment by sushiladokar** [comment]
Is there any solution to load the suggestion list on first mouse click only means when we dont have any tags selected, just to show some suggestions on click.
