### ISSUE TITLE
 [ngRepeat:dupes]  http://errors.angularjs.org/1.2.20/ngRepeat/dupes?p0=item%20in%20suggestionList.items%20track%20by%20track(item)&p1=toiletries     at Error (native)

### ISSUE THREAD

**Issue by abhijeet-mantralabs** [mbenford/ngTagsInput#206]
i am using ng-tags input as follows 
in html

<tags-input ng-model="tags" min-length="1" display-property="canonicalName">
      <auto-complete min-length="1" source="loadTags($query)"></auto-complete>
 </tags-input>

in controller 
               });
                $scope.loadTags = function(query) {
                     console.log(query)
                     var param = {providerId : 'Bl', prefixedName : query};
                     return $http.get(apiBase + 'typeAheadS',{
                      params:{
                        query: param
                      }
                     }).then(function(res){
                            var categories = [];
                            angular.forEach(res.data.typeAhead, function(item){
                              categories.push(item.suggestedResult);
                            });
                            console.log(categories)
                            return categories;
                          });

```
            };
```

its working fine for most of the result, but giving following error when i type 't' to search 
 [ngRepeat:dupes]  http://errors.angularjs.org/1.2.20/ngRepeat/dupes?p0=item%20in%20suggestionList.items%20track%20by%20track(item)&p1=toiletries     at Error (native)

my response in categories is like in this screen shot , which is in the image, below the reponse, there is error
![screenshot 2014-08-06 17 10 36](https://cloud.githubusercontent.com/assets/6152004/3826220/98796b6c-1d5e-11e4-9ea8-788683b0108e.png)

please help

**Comment by devendrasr** [comment]
Did any one get any success in getting rid of the dupes error? I am having duplicate labels to display in my use case. How can I get this resolved? Can anyone help me resolve this?

**Comment by ilanbiala** [comment]
@mbenford duplicate values should be supported because often a duplicate value may exist, but the objects have many differences.

**Comment by devendrasr** [comment]
@mbenford I got resolved my issue by removing the "track by track(item)" string from the ng-repeat template in the ng-tag library as of now.
