### ISSUE TITLE
Placeholder cut off if element is hidden initially

### ISSUE THREAD

**Issue by adrianhara** [mbenford/ngTagsInput#207]
I've noticed that if the element is initially hidden (or hidden when the placeholder gets set, e.g. if placeholder interpolation is enabled and the placeholder text gets set "later") then the placeholder text gets cut off. Debugging reveals that the offsetWidth of the <span> used to calculate the text width is 0 and it looks like that's indeed the case with hidden elements.

My particular scenario is I have the tags input inside a collapsible section which is initially collapsed (it's an advanced search of sorts). The text is "type to find business partners" which gets cut off.

One solution that I can think of is, instead of creating the hidden <span> used to calculate the <input>'s width once, create the span whenever the resize() function is called and check if the element's visible or not. Then, if the element's NOT visible simply append the <span> to the document.body, instead of the parent. I implemented this solution and it works (of course, removing any previously created <span>s every time). The only strange thing is that I needed to increase the THRESHOLD to 18, otherwise the very end of the text would get cut off (note, this would happen regardless of text length). I presume it might have something to do with the fact that some CSS selectors which are specific to the span residing inside of ng-tags-input don't apply anymore, but haven't dug through the css yet.

Can you please share your feedback on the issue and other ideas for a fix you might have?

Thanks!

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
