### ISSUE TITLE
Stop inserting tags when `max-tags` is reached

### ISSUE THREAD

**Issue by lmammino** [mbenford/ngTagsInput#210]
It would be really pretty if users can't add tags anymore when the `max-tags` (if any) is reached.
Without a precise analysis of the code, the simplest solution seems to be to just disable the internal input of the component when the `num-tags == max-tags` condition is satisfied.

Does anybody thinks this would be a convenient addition?

**Comment by TimMcCauley** [comment]
@mbenford I wasn't able to get your code to run with Angular 1.3.16 but this did:

```
link: function(scope, element, attrs, ngModelController) {
            var maxTags = attrs.maxTags ? parseInt(attrs.maxTags, '10') : null;
            ngModelController.$validators.checkLength = function(value) { // 'pastDate' is the name of your custom validator ...
                if (value && maxTags && value.length > maxTags) {
                    value.splice(value.length - 1, 1);
                }
                return value;
            };
        }

```

**Comment by naveencasp** [comment]
@mbenford This code not working with latest verision of  "ngTagsInput v3.0.0"

app.directive('enforceMaxTags', function() {
  return {
    require: 'ngModel',
    link: function(scope, element, attrs, ngCtrl) {
      var maxTags = attrs.maxTags ? parseInt(attrs.maxTags, '10') : null;

      ngCtrl.$parsers.push(function(value) {
        if (value && maxTags && value.length > maxTags) {
          value.splice(value.length - 1, 1);
        }
        return value;
      });
    }
  };
});

**Comment by Shiva-kayathi** [comment]
I tried enforceMaxTags directive for v3.0.0 and it did not work. 

The optimal solution for me was to **restrict the number of input values to tags input array** so that when user type also he cannot receive data

**Comment by dlukez** [comment]
I'll look again at updating it for v3.0.0 and getting into the main codebase

**Comment by chaudhryjunaid** [comment]
any updates?

**Comment by chaudhryjunaid** [comment]
I would love to have this feature.

**Comment by AdrienDC** [comment]
Up!

**Comment by Namledz** [comment]
> @mbenford I wasn't able to get your code to run with Angular 1.3.16 but this did:
> 
> ```
> app.directive('enforceMaxTags', function() {
>   return {
>     require: 'ngModel',
>     link: function(scope, element, attrs, ngModelController) {
>             var maxTags = attrs.maxTags ? parseInt(attrs.maxTags, '10') : null;
>             ngModelController.$validators.checkLength = function(value) { 
>                 if (value && maxTags && value.length > maxTags) {
>                     value.splice(value.length - 1, 1);
>                 }
>                 return value;
>             };
>         }
>    };
> });
> ```

Thanks, that helped me a lot
