### ISSUE TITLE
Doesn't work on mobile chrome 

### ISSUE THREAD

**Issue by mainalikishan** [mbenford/ngTagsInput#217]
The auto-complete does't get selected on mobile chrome. Input box touch event is also not working smooth.

**Comment by kolli1337** [comment]
Hi @RPieter 

could you please share an example of how you manipulated the width of the input field?
I tried 

tags-input input {
  width: 100%;
}

but this i overwritten automatically to "width: 68px;" when the input field is created... :(

Best regards,

kolli

**Comment by cacothi** [comment]
Hey guys, I've run into this issue and I have fixed for my scenario. I don't know if it would work for your.

When the tag is not focused, the input box withing the tag is with width zero and height zero to hide it. What I did was to set a min-width to the field, so it's just fixed. 

I think the mobile browser have some difficulties to work with no width.
