### ISSUE TITLE
Option for autocomplete to be open immediately

### ISSUE THREAD

**Issue by offsky** [mbenford/ngTagsInput#221]
Currently, you must type at least 1 character for the autocomplete to appear.  Could we have an option to have the autocomplete appear immediately when the input gets focused (0 keystrokes)?  

Use case: Your list of options for autocomplete is a limited small set. They would all be visible in the autocomplete box. In this case, you could click to focus and click to select a tag without having to move to the keyboard.  On touch devices where keyboard input is more difficult this would be a bigger win.

**Comment by Prabhuoptisol** [comment]
I have enter the  random text in tag and save it saved without throws an error 
how to clear the random text in tag filed
