### ISSUE TITLE
wrong behavior for allowLeftoverText

### ISSUE THREAD

**Issue by guilbep** [mbenford/ngTagsInput#223]
Hmm allowLeftoverText  has the opposite wanted behavior ?  to not trigger on lose focus on a modal I had to put a allow-leftover-text to true ..

I think it's wrong.

**Comment by bgold0** [comment]
What I'm assuming he means is:

When the input-tags are focused (while I'm typing something): if there is left over text with `allow-leftover-text="false"`, the form will still be valid.

If you focus off the `input-tags`, the form will then be invalid.
