### ISSUE TITLE
hide irrelevant results

### ISSUE THREAD

**Issue by mpmisha** [mbenford/ngTagsInput#228]
hey,
I'm trying to use ngTagsInput and cant figure out how to hide irrelevant results in the suggestion lists
I see you did just that in the main example in the main page (http://mbenford.github.io/ngTagsInput/) with the superheros,
but couldn't find an example for this in the demos section.
Thanks.
Michael

**Comment by EdmundMai** [comment]
Here's my solution:
```
  $scope.loadInterests = function(query) {
    // in my case, interests is an array of resources that was resolved in the routes since i didn't need to make a request each time the user typed inside the text field
    var filtered_interests = interests.filter(function(interest) {
      return interest.text.match(RegExp(query, "i"));
    })
    var deferred = $q.defer();
    deferred.resolve(filtered_interests);
    return deferred.promise;
  };

```

**Comment by Mr-Developer** [comment]
Thank you, this last answer works perfect;
See my implementation of your answer.
`$scope.loadClients = function (query) {
        var filtered_clients = $scope.clientSelectOptions.filter(function(client) {
            return client.display.match(RegExp(query, "i"));
        });
        var deferred = $q.defer();
        deferred.resolve(filtered_clients);
        return deferred.promise;
    };`
