### ISSUE TITLE
Allow "tab" to add tag and retain focus in the input

### ISSUE THREAD

**Issue by offsky** [mbenford/ngTagsInput#233]
When you press the "tab" key, what you have typed is turned into a tag and the focus is moved to the next input on the page. 

What do you think about this: When you press the "tab" key, your tag is created and the focus remains in the input for you to enter another tag. If you press the "tab" key again (with nothing typed) _then_ it moves the focus to the next input.  

My reasoning is that "tab to complete" is a common action and I find myself getting annoyed that I can't "type, tab, type, tab, type, tab" to quickly enter multiple tags.  I know that I can use "return", but for some reason that doesn't feel natural to me.  You can still tab to the next field by double tabbing, so I don't think any usability is lost.

**Comment by jeffschenck** [comment]
I hate to comment for what's barely more than a +1, but I do think this deserves higher billing than a low-priority. I also agree that myself (and the users I've seen in user testing) consider tabbing to complete in a widget like this to be standard functionality. 

I don't know how soon I'd have time, but @mbenford would you be open to a pull request for this? I'd love to make this excellent tool better!

**Comment by mbenford** [comment]
@jeffschenck I marked most of all non-bug issues as low priority so I could focus on what to work on for the next release. It's a common organization practice when you have a large backlog and need to know what to do next. It doesn't mean that this feature isn't important.

And of course you can send a PR solving this. No need to ask. :) Don't forget to read the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file before you start so you know how to format things according to the project guidelines.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
