### ISSUE TITLE
Include raw Sass in Bower Build?

### ISSUE THREAD

**Issue by mpolichette** [mbenford/ngTagsInput#234]
Hey, I just started using this and it has been working great! :+1:  for the project!

A minor issue we have is trying to include the styles with our own.  We also use Sass and we compile down to a single css file for deployment.  With that in mind, since Sass doesn't currently allow importing of .css files, it would be great if the raw Sass files were included in the bower build. Then we could import to our hearts desire! :)  

Thanks for your time!
Matt

**Comment by azachar** [comment]
Hello,
this is not true, once you modify bootstrap variables, the css styles provided by this library are not updated. I do not see any overhead providing sass files into a bower package.

Thanks for reconsidering it :)

Cheers, 
Andrej
