### ISSUE TITLE
Allow selection of all tags with Ctrl+a / cmd+a

### ISSUE THREAD

**Issue by alexanderjeurissen** [mbenford/ngTagsInput#240]
It would be nice if ngTagsInput would allow the user to select all tags / text that has yet to be parsed to a tag with keyboard shortcuts.

There are two usecases where this would be helpfull:
1.  I want to delete all entered text that is not yet parsed to a tag and all tags already parsed with `Ctrl + a + backspace` / `Cmd + a + backspace`. because if the amount of tags is large, manually removing them or pressing backspace for a long time can be time consuming.
2. I want to coppy all entered text that is not yet parsed to a tag and all tags already parsed with `Ctrl + a > Ctrl + c` / `Cmd + a > Cmd + c`. 

I can understand if you don't want the last useCase to be implemented as it's quite app-specific, but in my opinion due to the flexibility of this directive it is possible that person A enters a large amount of tags for inviting people or sending a newsletter Then person B wants to copy those and put them in excel as CSV etc. It's possible that person A and person B don't know each other and thus don't have access to the source file that was used to enter the tags.

This ofc all is related for use-cases where the tagCollection get's very large.

**Comment by chetanra** [comment]
Is this extensibility added?

**Comment by popod** [comment]
Is this function still in your mind ? I'd like to use it too ;)
