### ISSUE TITLE
input is readonly

### ISSUE THREAD

**Issue by hatemzidi** [mbenford/ngTagsInput#241]
hey, 

is it possible to add the attribute readonly to the directive ? 
i have the need here that the user chooses the tags from a fixed list without taping them directly ...

thanks

**Comment by emiguevara** [comment]
Any news about this? Setting boolean attributes in the template <input> element does not pass them to application, but modifying the generated HTML in the console produces the expected behaviour (e.g. <input readonly>, <input disabled>).

**Comment by marcusgao94** [comment]
if using addFromAutoCompleteOnly, user can still delete a tag
i want the user can only see the tags, neither add or delete a tag
thanks

**Comment by hazzik** [comment]
@mbenford can this issue be reopened? We had to make an ugly work-around to achieve this. We need to be able to disable fields based on expression (something like ng-readonly)

**Comment by jakobmaier** [comment]
+1

**Comment by codeandcats** [comment]
@mbenford Can you please reopen this. You're right, it's not a bug. It's a feature. A very useful feature that people are clearly in need of (inc. myself).

**Comment by sebastientromp** [comment]
@mbenford Same here, definitely something I'm needing too :)

**Comment by jitterbox** [comment]
@mbenford Please add read-only mode to the feature roadmap - we have a need for it in an ongoing project, and it looks like many others have in the past year.

**Comment by jonpeterson** [comment]
+1

**Comment by iboware** [comment]
+1 it would be better to be able to specify if it is allowed to add or remove items to input. In my case I just want to make it remove-only.

**Comment by indianazhao** [comment]
+1 remove-only

**Comment by AniWar** [comment]
# Readonly Tags

![image](https://cloud.githubusercontent.com/assets/16691390/23122487/65dc07e2-f78a-11e6-8315-ed662de030ab.png)



In **_ng-tags-input.min.js_**
1. Removing Close/remove Tag symbol : 
      a) Search for **ng-click="$removeTag()" ng-bind="::$$removeTagSymbol"**
![image](https://cloud.githubusercontent.com/assets/16691390/23122391/02d2c85c-f78a-11e6-8977-9662ea79b30d.png)
      b) Delete it
![image](https://cloud.githubusercontent.com/assets/16691390/23122414/21bc9f04-f78a-11e6-926c-c8b4e5fb5c82.png)

2. Making Tags Read only : 
      a) Search for **<input class="input"**
      b) Add **readonly**  attribute
![image](https://cloud.githubusercontent.com/assets/16691390/23122334/cc78e408-f789-11e6-9149-d9a61da3ec36.png)


3. Removing "Add a tag" placeholder :
     a) Search for **Add a tag**, you will see something like **placeholder:[String,"Add a tag"]**
![image](https://cloud.githubusercontent.com/assets/16691390/23122449/494c50fa-f78a-11e6-8179-6399dd5bc6c8.png)

     b) Replace it with empty string , something like this **placeholder:[String,""]**
![image](https://cloud.githubusercontent.com/assets/16691390/23122441/3ccbb1b8-f78a-11e6-9e6f-f0482eb5a2bd.png)

**Comment by cgatesman** [comment]
FWIW, I was able to solve this by setting `disabled` and `readonly` on the `tags-input`, then apply a small amount of CSS (Saas):

```css
  tags-input[disabled][readonly] {
    .tags {
      background-color: #fff;
      cursor: default;

      .tag-item {
        opacity: 1;
        background: #428bca;

        .remove-button {
          display: none;
        }
      }

      .input {
        display: none;
      }
    }
  }
```

![screen shot 2017-10-16 at 2 30 32 pm](https://user-images.githubusercontent.com/6276072/31628411-99fa5574-b27e-11e7-9c6c-232bb2b830f8.png)

**Comment by jungalwala** [comment]
This seems like a very obvious feature to add to have a `readonly="true"` capability built into the directive.
