### ISSUE TITLE
Tab and shift+tab do not move focus correctly within form

### ISSUE THREAD

**Issue by offsky** [mbenford/ngTagsInput#242]
```
<input type="text" tabindex="1" />
<tags-input ng-model="tags" tabindex="2"></tags-input>
<input type="text" tabindex="3"/>
```
- When input 1 is focused and you press tab, the tags-input gets highlighted, but does not get focus and become active for typing. You have to press tab again to give it focus.
- When tags-input is focused and you press tab, the focus is correctly moved to input 2.
- When tags-input is focused and you press shift+tab, the tags-input loses focus but remains highlighted and input 1 is not given focus. You must press shift+tab a second time to move focus to input 1.  When this happens, tags-input retains it's "focused" class which gives it the blue highlight around the object even thought it is no longer focused.
- When input 3 is focused and you press shift+tab, the tags-input correctly gets focus and becomes active for typing.

This is because the tabindex of the tags-input is copied into the internal input, which causes there to be two dom elements with the same tabindex.  In the example above, when you go from 1 to 2, the tags-input div gets focused first which is a fake focus since that div can't accept input. You tab again to get into the actual input box.  Same scenario when going backwards.

I think the solution is to remove the tabindex from the tags-input after you compile it and move the tabindex to the internal input.  I added this in the tags-input link step and it seems to solve the problem in my limited testing

```
element[0].tabIndex = -1;
```

**Comment by ArdentZeal** [comment]
+1 on this one, could need it right now!

**Comment by RobertHeim** [comment]
+1

**Comment by ReidBraswell** [comment]
First, great component! Any traction on this defect at this point? It's been more than a year now, and I believe there are several Pull Requests with fixes. I'm using this in an app now, which could benefit from a fix.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
