### ISSUE TITLE
When ngTagsInput is used within another Directive with Compile The options are lower cased by Angular

### ISSUE THREAD

**Issue by MyCADDev** [mbenford/ngTagsInput#253]
The html element "displayProperty" is change to displayproperty by AngularJS hence ngTagsInput sees it as default - 'text'.

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by MyCADDev** [comment]
Angular changing the case of the property is making ngTagsInput work incorrectly. Can you change the option of ngTagsInput to snake-case style. This will fix the problem.

**Comment by mbenford** [comment]
I wonder if you could you post the markup you are using?

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by MyCADDev** [comment]
Sure - please close it.

thanks
