### ISSUE TITLE
Clicking an item from suggestion list does not select the item

### ISSUE THREAD

**Issue by egervari** [mbenford/ngTagsInput#262]
Let's say we have two tags in our database: 'dog' and 'dog-city'.

The user types in 'dog', and the suggestion list is filled with both 'dog' and 'dog-city'.

If the user uses the arrow keys and pressed 'enter' to select the tag, everything works fine.

However, if the user clicks 'dog-city' from the suggestion list when 'dog' is typed out, your directive will only put 'dog' as a tag, even though 'dog-city' was clicked. I'm using Firefox btw.

If `add-from-autocomplete-only="true"` is used, then nothing is put into the input field when 'dog-city' is clicked.

I believe this is probably a bug. I think it should work the same way for clicks as it does for arrow keys and enter.

**Comment by mbenford** [comment]
@egervari Any update on this?

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by kevinrenskers** [comment]
Clicking on items in the suggestions list doesn't work in Firefox when addFromAutocompleteOnly=true.

**Comment by mbenford** [comment]
@kevinrenskers I've just tested v2.2.0 in Firefox 36 and everything has worked just fine. I used this [Plunker](http://plnkr.co/edit/49GswrDdrLdGKPS04Oi2?p=preview).

**Comment by kevinrenskers** [comment]
It seems the problem is related to custom CSS. This is my plunk, with kind-of the css that I'm using in my project: http://plnkr.co/edit/Jy5kWQ84CWRMW3oZI80j?p=preview. Note that in Firefox it's not possible to select any of the suggestions with the mouse. So I guess that I'm missing a critical piece of your css code, any idea what it could be?

**Comment by mbenford** [comment]
Yes, your custom stylesheet is missing the `.host` class. I suggest that you include the default stylesheet before your custom one, and then change only the classes you need to.

**Comment by kevinrenskers** [comment]
Cool, that does indeed fix the Firefox problem. I think this issue can be closed.
