### ISSUE TITLE
Dynamic coloring of tags

### ISSUE THREAD

**Issue by doorman02** [mbenford/ngTagsInput#273]
Is there a way to change the color on specifc tags programmically?

Thanks!

**Comment by tanzaho** [comment]
+1 for that.
Personnal use case : I have two sets of tags. Ones that could be edited, and ones that couldn't. I would like to show it with some CSS.

**Comment by reubenbrown** [comment]
Have a similar use case to @tanzaho. Is there an estimated timetable for when this this (or #390) will be released?

**Comment by juanvillegas** [comment]
+1 here!

**Comment by Gompje** [comment]
I've added support for colored tags in my fork. They get inline styles based on fields returned from the database. this way you can do both scenario's mentions in this thread. It's a rough implementation atm with some default values that work for my application. I really don't have time to write extensive tests for this.

Bit new to pull request/forking and will gladly share if someone points me to the right direction :)

I'm currently adding support for a nice color badged in the suggestion list as well.

**Comment by shyamal890** [comment]
+1

**Comment by lubiluk** [comment]
Hi guys,
please consider this uber simple fix for the issue.

**Comment by Gompje** [comment]
@shyamal890 Sorry Shyamal, I didn't see your message in a see of Github mails and kinda lost track of time after that. If I remember correctly I added some properties and mapped them accordingly. I use inline styles so that each tag can have his own user definable color/bg-color. Other styling is done with the default css. I also altered the dropdown to include a coloured badge and some extra logic to show a 'nothing found' message to the user. Hope this helps.

**Comment by markroze** [comment]
ADD TO THE JS FILE AFTER ..." ng-class=\"{ selected: tag == tagList.selected }   "..  THIS..."  style=\"background: {{tag.color}}\"     "... TO BE ABLE TO READ PRPERTY color OF TAG OBJECT

**Comment by pklinger** [comment]
```
    $templateCache.put('ngTagsInput/tags-input.html',
    "<div class=\"host\" tabindex=\"-1\" ng-click=\"eventHandlers.host.click()\" ti-transclude-append><div class=\"tags\" ng-class=\"{focused: hasFocus}\"><ul class=\"tag-list\"><li class=\"tag-item\" ng-style=\"{ 'background' : tag.colorscheme }\" ng-repeat=\"tag in tagList.items track by track(tag)\" ng-class=\"{ selected: tag == tagList.selected }\" ng-click=\"eventHandlers.tag.click(tag)\"><ti-tag-item data=\"::tag\"></ti-tag-item></li></ul><input class=\"input\" autocomplete=\"off\" ng-model=\"newTag.text\" ng-model-options=\"{getterSetter: true}\" ng-keydown=\"eventHandlers.input.keydown($event)\" ng-focus=\"eventHandlers.input.focus($event)\" ng-blur=\"eventHandlers.input.blur($event)\" ng-paste=\"eventHandlers.input.paste($event)\" ng-trim=\"false\" ng-class=\"{'invalid-tag': newTag.invalid}\" ng-disabled=\"disabled\" ti-bind-attrs=\"{type: options.type, placeholder: options.placeholder, tabindex: options.tabindex, spellcheck: options.spellcheck}\" ti-autosize></div></div>"
  );
```

As a quick fix you may search in the JS file for 'ngTagsInput/tags-input.html' in the template and alter it accordingly. As the demo broke every time, I chose to go this way. Updates of this library will break this color addon, therefore, beware if you use it on a productive system.

You may add a dynamic coloring functionality by adding in `ng-style=\"{ 'background' : tag.colorscheme }\"` to the tags-input directive as I have done above.

Add a colorscheme property to your model on the same level as the text property to display the tag text and you will be fine to go.
