### ISSUE TITLE
Enforce tags count limit

### ISSUE THREAD

**Issue by orlaqp** [mbenford/ngTagsInput#283]
In my project I needed to force the user to enter up to a certain amount of tags and disable the input after that. After doing some research I could not find a way to that with this directive so I implemented something like this:

Added a new `limit` property to the directive's controller

```javascript
limit: [Number, -1]
```

added a new method call to the events `tag-added` and `tag-removed`

```javascript
.on('tag-added tag-removed', function () {
       ngModelCtrl.$setViewValue(scope.tags);
       processLimitOption();
})
```

and this is the implementation of the `processLimitOption` method

```javascript
function processLimitOption() {
     if (scope.options.limit > 0 && scope.tags.length === scope.options.limit) {
           element.find('input').hide();
     } else {
           element.find('input').show();
     }
}
```

do you think you can add this feature to your control? I did not create a pull request because I still do not understand the full implementation of it but this is working fine for my needs.

Thanks for sharing!

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by orlaqp** [comment]
Yes #297 covers it. Thank you very much!
