### ISSUE TITLE
Provide proper error message when not assigning an array of objects to ng-model.

### ISSUE THREAD

**Issue by jgehrcke** [mbenford/ngTagsInput#284]
Hello!

I had a hard time finding an error in my ngTagsInput-related code, because the error message provided by AngularJS was

```
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed.
```

whereas the error itself was that I assigned an object to the property bound to the tags-input directive, instead of an array of objects. 

The `ngRepeat:dupes` error is [well-defined](https://docs.angularjs.org/error/ngRepeat/dupes?p0=tag%20in%20tagList.items%20track%20by%20track%28tag%29&p1=undefined&p2=%22C%22) and should never be triggered by mis-using ngTagsInput.

So, how could misusing ngTagsInput yield such an error in the first place?  The erroneous assignment happened in a function which was executed upon button click, as defined via an ng-click directive, which itself was specified _within an ng-repeat directive_. So, in fact, I was using ng-repeat, got this error message, and wasted my time looking for duplicates. You can imagine, debugging this was not too easy.

Therefore, I propose that ngTagsInput should provide a meaningful error message when one assigns wrongly to whatever ng-model points at. Or, do you think that AngularJS needs to be fixed, because this error can be triggered with only one item in the ng-repeat directive, so there definitely is no duplicate in the game?

As this is difficult to put in words, I have created a little reproduction plunker: http://embed.plnkr.co/yK6rNoDySJzPwIVPUkRf/preview

Pressing any of the "Set as tag (fails)" buttons raises the error (to be seen in e.g. the Chrome dev tools JavaScript console). Pressing any of the "Set as tag" buttons shows proper behavior. The only difference between both cases is `$scope.tags = {taglabel: i.label, item: i};` (failing) vs. `$scope.tags = [{taglabel: i.label, item: i}];` (succeeding, note the squared brackets).

**Comment by kirilgorbachov** [comment]
+1

**Comment by geoguide** [comment]
+1

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
