### ISSUE TITLE
Documentation: clarify "active interpolation"

### ISSUE THREAD

**Issue by jgehrcke** [mbenford/ngTagsInput#285]
Currently, the docs only say "Sets active interpolation for a set of options.", but it is hard to find out what is actually meant by that. From the examples, it looks like whatever property is "actively interpolated" becomes injected into the current $scope, for observation and modification. Is that correct or is there more to it?

Also, please note that the explanation for `setTextAutosizeThreshold(threshold)` currently is a copy-paste-error (it also is "Sets active interpolation for a set of options.").

**Comment by mbenford** [comment]
There is a [new page](http://mbenford.github.io/ngTagsInput/documentation/global-configuration) on the ngTagsInput website explaining what active interpolation means, among other things.
