### ISSUE TITLE
Add a new option to enforce maxTags

### ISSUE THREAD

**Issue by mbenford** [mbenford/ngTagsInput#297]
A new option could be implemented to enforce how many tags can be added. That option should work along with the existing `maxTags` option.

**Comment by pcocko** [comment]
At the moment, @dlukez enhancement works very well. Please add it as new feature

**Comment by hoodsy** [comment]
Would love to use the new enforce-max-tags functionality :D

**Comment by Sylox** [comment]
+1

**Comment by zardaloop** [comment]
Any progress on this feature? Cheers :)

**Comment by cklemming** [comment]
+1

**Comment by sterlingwes** [comment]
+1

**Comment by JackGommeren** [comment]
+1

**Comment by ChristianLJ** [comment]
+1

**Comment by mmastika** [comment]
+1

**Comment by brunomeira** [comment]
+1

**Comment by numasi** [comment]
+1

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by AdrienDC** [comment]
+1
