### ISSUE TITLE
Material design theme

### ISSUE THREAD

**Issue by mikaelharsjo** [mbenford/ngTagsInput#300]
Hi!

In my project we use [material design](http://www.google.com/design/spec/material-design/introduction.html). So I basically have finished css for making this plugin look material. Would it be of interest to add that as an alternative to bootstrap in this project? I would be happy to make a pull request out of it.

**Comment by mbenford** [comment]
Any update on this?

**Comment by mikaelharsjo** [comment]
No, sorry. This gone down prioritized in my project. I'll close this for now and reopen if and when I have time to do it.
