### ISSUE TITLE
Placeholder is not working :(

### ISSUE THREAD

**Issue by techwarriorz** [mbenford/ngTagsInput#312]
I don't know if this is a common occurrence, however, none of my placeholders are showing up :(

Here is a sample of my code, please let me know if there is anything that I am currently screwing up (or if there are any common backend errors).

 // tags-input
ng-model="model.sample"
display-property="description"
unique-property="id"
placeholder="Placeholder Text"
replace-spaces-with-dashes="false"
max-length="100">

 auto-complete source="loadEventPositions($query)" min-length="0"

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by techwarriorz** [comment]
Issue is closed, sorry about that, we just took out the IE8 support and it works fine! Great tool you guys built.
