### ISSUE TITLE
Make the input text bindable

### ISSUE THREAD

**Issue by mbenford** [mbenford/ngTagsInput#315]
The input text should be bindable so it could be retrieved and/or changed from outside the directive.

**Comment by mbenford** [comment]
Implemented in 22ef356487084269fa4b9744d84eb20e51f90d51

**Comment by DamodarSojka** [comment]
Hi
Can you please document how to use this feature? I would like to use it.

**Comment by danielcrisp** [comment]
It seems you can add a `text` attribute to the directive which will contain the current value of the field, so you can clear it.

    <tags-input text="text"></tags-input>

    <button type="button" ng-click="text = null">Clear text</button>

**Comment by adeopura4** [comment]
Hi, how would you do this text = null inside a function call in JS. Basically I have this input field in a dialog box, and i want to clear the field when the dialog box closes and not on blur. Thank you.

**Comment by penguin020** [comment]
FYI: When resetting, I had to call `$setValidity` for `leftoverText` to get the $invalid state cleared.

e.g.
```
    $scope.reset = function () {
        $scope.editable = angular.copy(savedState);
        $scope.myForm.ctrlTags.$setValidity("leftoverText", true);
    };

```
