### ISSUE TITLE
Support of Angular 1.3+ is very needed

### ISSUE THREAD

**Issue by sunra** [mbenford/ngTagsInput#318]

**Comment by mbenford** [comment]
I haven't tested ngTagsInput with Angular 1.3 yet, so I can't say what works and what doesn't. Anyway, this has to be done eventually. I'll add this to the backlog so I don't forget about it. 

I appreciate if you could share any problems you may have run into regarding Angular 1.3.

**Comment by jacquie** [comment]
+1

**Comment by kfprimm** [comment]
I've been attempting to integrate this into a 1.3 application.

Everything seems to work fine except for data binding. The scope attribute that I pass with `ng-model` never appears to be touched, i.e. it remains undefined. I'm going to attempt to solve this issue myself. Will report back if/when I make progress.

**Comment by vdsabev** [comment]
The plugin works fine for me using AngularJS 1.3.4, with an asynchronous autocomplete source:

```html
<tags-input ng-model="share.emails" add-on-space="true" allowed-tags-pattern="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}" enable-editing-last-tag="true" placeholder="Type email addresses...">
  <auto-complete source="share.filter($query)" />
</tags-input>
```

As you may have noticed, my model scope variable is in an object, not directly bound to the scope to avoid any possible issues with scope inheritance: http://stackoverflow.com/a/23943930/651595
I'm not sure if that has anything to do with the issues some people are having, I just do it to be safe.

**Comment by jmorrice** [comment]
+1

**Comment by kfprimm** [comment]
@vdsabev, that solved my issue. Original I was binding a variable directly on the scope. I can confirm that it appears to work fine now. Thanks!

**Comment by Dr4K4n** [comment]
+1

**Comment by hoxu** [comment]
Angular 1.3.11 and ng-tags-input 2.1.1. The only issue I noticed was that the form stayed `$invalid` despite the model being set properly.

**Comment by Fonger** [comment]
@hoxu 
Also `minLength` won't work. Even if I set it to `2` or `1`, I still can't use 2-world tag.

**Comment by mpolizzotti** [comment]
+1 Using Angular v1.3.13 and ngTagsInput v2.2.0. The properties ($pristine, $dirty) used for form validation do not appear to update.

**Comment by ozalvarez** [comment]
+1

**Comment by aarosil** [comment]
+1!
