### ISSUE TITLE
updating parent model when no value is bad

### ISSUE THREAD

**Issue by se7** [mbenford/ngTagsInput#320]
We shouldn't be setting ```scope.tags``` explicitly as that circumvents ng-model and can create invalid models on parent, especially when model hasn't been loaded yet (tags === undefined)

Consider the following scenario
```html
<tags-input ng-model="someObject.metadata.tags"></tags-input>
```

With the current code, if ```someObj``` is undefined/null, tagsInput would create the whole ```someObj.metadata``` objects as empty objects with one property ```tags``` that would be an empty array. With the only seeming reason being that you can count on running ```scope.tags.length```.  This could make the parent model invalid and cause weird side effects. Allowing for ```scope.tags``` to be undefined/null should be up to the consumer, and the value shold only be set through ```$ngModelCtrl.setViewModel()``` when the value actually changes, not through some automatic initialization. 

If you agree, I can make a PR

**Comment by mbenford** [comment]
Sorry for not replying sooner.

I agree with you. This probably will fix #204.
