### ISSUE TITLE
How to show thumbnail in suggestion dropdown?

### ISSUE THREAD

**Issue by shahidmau** [mbenford/ngTagsInput#323]
I am showing the list of the users in the suggestion dropdown, I want to show the photo of the user at left side of each row. How to do this?

Please see example 2 of below page
http://darylrowland.github.io/angucomplete/

**Comment by mbenford** [comment]
Sorry for not replying sooner.

Unfortunately that's not possible right now. It's in the project backlog, though. Take a look at #99.

**Comment by mbenford** [comment]
Can this issue be closed?
