### ISSUE TITLE
inserting new tags

### ISSUE THREAD

**Issue by muuuub** [mbenford/ngTagsInput#327]
Suppose we have the tags:

[ one ] [ two ] [ three] [ four ]

It would be nice to be able to delete [ three ] and then use the arrow keys/mouse click to scroll over and insert a new tag:

[ one ] [ two ] [ new_three ] [ four ]

It's useful for when the list of tags is long and the user wants to keep it in a certain order (ie, list of favorite movies from best to worst).

**Comment by mbenford** [comment]
Something similar to this has been requested before. Take a look at #62.

**Comment by muuuub** [comment]
Closing since it's a duplicate of #62
