### ISSUE TITLE
Bug in highlight

### ISSUE THREAD

**Issue by amidudu** [mbenford/ngTagsInput#328]
Hi,

There is an issue when highlighting word with special characters such as "&".
For example in case the autocomplete return "AT&T" while the user enter "a" it will replace the &amp; to &amp;amp; and will highlight the a inside the &amp; word (&amp;&lt;em&gt;a&lt;/em&gt;mp;)

**Comment by amidudu** [comment]
Maybe this code can be a solution (find the matches in a loop and encoding the text in the replace phase so it will not affect the find part)

            scope.highlight = function(item) {
                var text = getDisplayText(item);

                if (options.highlightMatchedText) {
                    if (!suggestionList.query) {
                        text = encodeHTML(text);
                    } else {
                        var part, result;
                        var currIndex = 0;
                        var findRegExp = new RegExp(suggestionList.query.replace(/([.?*+^$[\]\\(){}|-])/g, '\\$1'), 'gi');
                        var highlightedText = "";

                        while (result = findRegExp.exec(text)) {
                            part = text.substring(currIndex, result.index);
                            highlightedText += encodeHTML(part) + "<em>" + encodeHTML(result[0]) + "</em>";
                            currIndex = result.index + result[0].length;
                        }

                        part = text.substring(currIndex);
                        highlightedText += encodeHTML(part);
                        text = highlightedText;
                    }
                } else {
                    text = encodeHTML(text);
                }

                return $sce.trustAsHtml(text);
            };

**Comment by mbenford** [comment]
Thanks for reporting this bug. :+1: 

It has been [reported before](https://github.com/mbenford/ngTagsInput/issues/200) and I'm working on it already.

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by amidudu** [comment]
Yes
ᐧ
