### ISSUE TITLE
Removing the only tag doesn't mark the form as $dirty

### ISSUE THREAD

**Issue by kevinrenskers** [mbenford/ngTagsInput#341]
```
<tags-input ng-model="ctrl.shift.attendees" max-tags="1" placeholder="Enter name">
    <auto-complete source="ctrl.loadUsers($query)" display-property="displayName"></auto-complete>
</tags-input>
```

When I show this and `ctrl.shift.attendees` is set to an array containing one object and then remove the tag, `form.$dirty` isn't set. I have to start typing in the input before it's marked as dirty.

**Comment by kevinrenskers** [comment]
My workaround at the moment: `on-tag-removed="form.$dirty=true"`

**Comment by mbenford** [comment]
I did a quick test and everything worked fine. Take a look at [this plunk](http://plnkr.co/edit/GiOUwp?p=preview). Feel free to change it in order to reproduce the problem you are experiencing.

**Comment by kevinrenskers** [comment]
It's only happening in AngularJS 1.3.x.

**Comment by kevinrenskers** [comment]
I just noticed from the readme that 1.3 isn't officially supported yet but apart from this one problem it seems to work perfectly. We've been using it in production for some time now.

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by kevinrenskers** [comment]
Well it is a problem in 1.3..

**Comment by mbenford** [comment]
Fair enough. I'll add this to the backlog.

**Comment by deiwin** [comment]
Having an issue with $dirty as well. It looks like this was expected, though: [tags-input.js#314](https://github.com/mbenford/ngTagsInput/blob/664dfc70942ece06b0b97d85cbc52d1954398696/src/tags-input.js#L314)

**Comment by deiwin** [comment]
@mbenford, any idea when you will be able to release a version including this fix?

**Comment by mbenford** [comment]
@deiwin I haven't been able to work on this project lately, so I can't promise any ETA. But I'll *try* to make some time for it time next weekend.
