### ISSUE TITLE
Custom html remove-tag-symbol

### ISSUE THREAD

**Issue by otaviodecampos** [mbenford/ngTagsInput#343]
Hello,

I'm tried put a custom html in remove-tag-symbol, but this parameter accepts only a simple text. That would be very cool for complex buttons.

What you think?

Thankyou.

**Comment by mbenford** [comment]
Sorry for not replying sooner.

I think this has been requested before. I wonder if you could take a look at open issues and see if you find it?

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by mbenford** [comment]
From v2.3.0 on you can replace the default tag template with your own, so you can use whatever markup you want as the remove button. There's no documentation on custom templates yet, but I'm working on it.

**Comment by otaviodecampos** [comment]
Thankyou mbenford. I will investigate this functionality.
