### ISSUE TITLE
Can we have navigation within tags.

### ISSUE THREAD

**Issue by prabhu-das** [mbenford/ngTagsInput#350]
Its not an issue but a missing feature that we cannot navigate within the tags. Something similar to what we see in the 'To', 'cc', 'bcc' of gmail mails. We can navigate with the arrow keys, and delete the tags with backspace. Not a difficult feature. I was doing it in a fiddle, but I was using jquery to achieve that. Would be great if it comes with ngTagsInput.

**Comment by Zhouzi** [comment]
Actually it is already implemented. You might miss the css to make it visually perceptible but have a look at the demo page, start typing "superman" and navigate in the dropdown with arrow keys. 

http://mbenford.github.io/ngTagsInput/

**Comment by prabhu-das** [comment]
Oh, I actually have a different question in mind. I was asking for the horizontal navigation among the tags that are already added to the tags-input box. 

Ex: if I have below tags in my tags-input box
[abc] [xyz] [pqr] [mno]
consider the [] as the tag boxes.
My requirement is when i press the left arrow key once, my cursor should go between [pqr] | [mno]
pressing left arrow again should take my cursor between [xyz] | [pqr].

So that if i want to delete [abc] i can hit left arrow 3 times and then backspace once. same goes with right arrow. It should take my cursor to the next tagbox.

Its more of a non mouse feature and horizontal navigation. I want to support keyboard control like we have in gmail compose mail style.

Thanks for looking into it and replying. You are the best.

**Comment by prabhu-das** [comment]
@Zhouzi , Do you think this is possible, or can be achieved with minor modifications ?

**Comment by mbenford** [comment]
Sorry for not replying sooner.

This feature is in the backlog already. Take a look at #62.

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by mbenford** [comment]
Tag navigation is implemented in master. I've decided to split navigation off from editing because the latter is more complicated and needs further thinking.
