### ISSUE TITLE
korean is not working

### ISSUE THREAD

**Issue by choiks14** [mbenford/ngTagsInput#354]
when i typed "김" tag input is not working
please fix it.

**Comment by Fonger** [comment]
It's working. However you have to type at least 3 characters as it's default setting. `minLength` property may help. Also note that it doesn't support angularJS >=1.3.

Please check the document before asking a question.

![screen shot 2015-02-16 at 2 49 06 am](https://cloud.githubusercontent.com/assets/5862369/6204440/720d7c78-b586-11e4-9ded-d7cfba2c868c.png)

**Comment by mbenford** [comment]
Sorry for not replying sooner.

Did @Fonger's answer solve your problem? If so, please close this issue. If not, please provide more information on your problem.

**Comment by qpitlove** [comment]
I think you should check this issue.
https://github.com/mbenford/ngTagsInput/issues/303
Its reason is angular composition event, and I think you will resove it.

**Comment by choiks14** [comment]
sorry. i'm late.

it works.
min-length="1" is solved my problem. 
thanks :)
