### ISSUE TITLE
Show autocomplete suggestions on click

### ISSUE THREAD

**Issue by emiguevara** [mbenford/ngTagsInput#355]
In order to make autocomplete behave like a button, I added loadOnClick:
- event handler and template:
https://github.com/emiguevara/ngTagsInput/commit/3ca413ec0ae6ec4987cf4bcc297af60448710302
- implementation:
https://github.com/emiguevara/ngTagsInput/commit/b2227f3b2d9817a802c5c0d80c1838d61e10edeb

I'm not sure if it is the best way to accomplish this, first time I get dirty with angular modules.

**Comment by yarl** [comment]
+1 for this, will be really useful.

**Comment by mbenford** [comment]
Sorry for not replying sooner.

That behavior can sort of be accomplished by setting the `loadOnFocus` option as true. And if you want the user to be able to reload the autocomplete list while the input is focused, you can turn the `loadOnDownArrow` option on.

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by emiguevara** [comment]
yes, thanks for the reply
