### ISSUE TITLE
Is it possible to make the look-and-feel using TODC Bootstrap instead of the original Bootstrap?

### ISSUE THREAD

**Issue by cheonhyangzhang** [mbenford/ngTagsInput#361]
In the Documentation Integrating with Bootstrap:
Using 
<link rel="stylesheet" href="path/to/ng-tags-input.bootstrap.min.css">
Will make the input and tags to look in Bootstrap style.
This is great.
But for my sites, I am using a customized version of Bootstrap, TODC, http://todc.github.io/todc-bootstrap/.
This is a Google style them for Bootstrap.
Is there a quick way to integrate ngTagsInput with this TODC Bootstrap?

**Comment by mbenford** [comment]
Sorry for not replying sooner.

All you have to do is change the default stylesheet accordingly. Take a look at the [variables.scss](https://github.com/mbenford/ngTagsInput/blob/master/scss/bootstrap/variables.scss) file. You might be able to accomplish what you want by just changing the values in that file.

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by cheonhyangzhang** [comment]
Yes. Sure.  Sorry for the delay of replying.
