### ISSUE TITLE
How can I retrieve a flat string as ngModel something like that "tagone, tagtwo, tag three, tag four"?

### ISSUE THREAD

**Issue by alakip** [mbenford/ngTagsInput#362]
Hey dude,
Thank you for you awesome and great work.
Actually I need to get my final retrieved value as a flat string instead of [object]!
I'm new in AngularJS and I don't know how can I handle that.

Thanks.

**Comment by markni** [comment]
Before you save to database, just loop through the object and get text value of each node, push them into a new array. 

    var flat = [];
    for (var key in tags){
       flat.push(tags[key].text);
    }
    $scope.finalFlatString = flat.join(',');

You can call this in `on-tag-added` AND `on-tag-removed` to keep `$scope.finalFlatString` updated in real time.

**Comment by alakip** [comment]
Thanks a lot! :)

**Comment by mbenford** [comment]
ngTagsInput only works with array of objects. You can easily extract an array of strings out of an array of objects, though:

```javascript
$scope.tagsString = $scope.tags.map(function(tag) { return tag.text; });
```

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by alakip** [comment]
Yes, Thanks.
