### ISSUE TITLE
feature: add option to autocomplete to show suggestion list after adding or removing a tag

### ISSUE THREAD

**Issue by scottbcovert** [mbenford/ngTagsInput#365]
I have set the loadOnFocus and loadOnEmpty attributes to true per #316 so the suggestion list becomes visible upon focus. 

However, in a situation where the user needs to add several tags he/she must blur & refocus in between each tag entry to make the suggestion list reappear. This slows down the experience quite a bit so It would be nice if the suggestion list could be set to appear after adding/removing a tag, thereby keeping the suggestions visible until blur.

**Comment by mbenford** [comment]
This issue has been reported before and it's in the backlog already. Take a look at #205.

**Comment by scottbcovert** [comment]
Thanks; sorry for overlooking that it was already covered

**Comment by mbenford** [comment]
No problem. Can this issue be closed?

**Comment by scottbcovert** [comment]
Definitely; thanks!
