### ISSUE TITLE
chrome autofill interaction

### ISSUE THREAD

**Issue by schwer** [mbenford/ngTagsInput#368]
Chrome autofill interacts poorly with the autocomplete widget. To see this behavior, you need to have autofill enabled in your desktop chrome browser, and using a field-name that chrome interprets as "fillable" like a street address or zipcode. And, you need to have something in your autofill settings. The consequence of this problem is a dropdown that appears above the autocomplete dropdown and prevents you from clicking on the first item amongst the autocomplete options.

I am using Chrome 40.0.2214.111. ngTagsInput v2.0.1. Angular 1.2.16.

 A simple solution is to specify
```
<input autocomplete="off"'
```
in the tags-input.html template.

**Comment by mbenford** [comment]
Thanks for reporting this! I'll add it to the backlog.
