### ISSUE TITLE
Suggestion to improve keyboard autocomplete behavior

### ISSUE THREAD

**Issue by schwer** [mbenford/ngTagsInput#369]
When I am typing in the input field, and the autocomplete contains a single option, it would be ideal if three things happened:
  1. The last remaining option was highlighted.
  2. Pressing enter selected the last remaining option.
  3. Focus remained in the input box.

This is a nice-to-have, not really a bug, but I believe it would improve keyboard interactions substantially. Presently, one needs to use the directional keys to select the last remaining option.

**Comment by mbenford** [comment]
This is already implemented in the master branch (not released yet, but totally functional). You just need to set the `autoSelectFirstSuggestion` as `true`.

You can grab the latest build files [here](http://shrub.appspot.com/ng-tags-input).

**Comment by mbenford** [comment]
Can this issue be closed?
