### ISSUE TITLE
Gulp-uglify 1.1.0 issue

### ISSUE THREAD

**Issue by root-io** [mbenford/ngTagsInput#371]
Error: [$injector:unpr] http://errors.angularjs.org/1.3.13/$injector/unpr?p0=tProvider%20%3C-%20t%20%3C-%20tags

**Comment by mbenford** [comment]
That error message is pretty self-explanatory. You must annotate the source code before minifying it. I don't know much about Gulp, but there may be some extension to annotate Angular code.

**Comment by root-io** [comment]
Oups, thanks, I forgot to annotate my services.js :/
