### ISSUE TITLE
Long tags wrap awkwardly

### ISSUE THREAD

**Issue by JAndritsch** [mbenford/ngTagsInput#372]
If you enter in a tag that is really long (longer than the width of the parent container), you get a weird wrapping issue where the tag splits into two. Sometimes, this makes it so you cannot delete the tag by clicking on the "X".

I know there is a rule you can specify to limit the length of tags, but in my use case there are actually some pretty lengthy tags that exist so I cannot set a rule to prevent this issue.

Here is a preview of the problem:

![screen shot 2015-02-23 at 1 33 05 pm](https://cloud.githubusercontent.com/assets/190611/6335414/03c4cc36-bb61-11e4-84ec-ff5b356f8508.png)

To address this issue, I've cloned the repo and added a new "maxDisplayLength" option that will truncate the tag text via the "getDisplayText" method and replace the excess characters with an ellipsis. If you think this is something worthy of a fix, I'd be happy to submit a pull request.

**Comment by mbenford** [comment]
Truncating the text at some arbitrary length will break as soon as the text width changes - which can happen if a custom stylesheet alters the tag's text font. It would be great if this could be solved with some CSS trick. I'm no CSS expert, so I'll need to do some research to find out whether it's possible or not.

**Comment by JAndritsch** [comment]
Yeah, I know this isn't a great solution. I tried looking into some CSS styling and didn't really find anything that worked. I can set the overflow of the "tag-item" class to hidden, but doing that causes the "X" icon to also be hidden when the keyword is long. 

Perhaps a better way to do it would be to restructure the markup in such a way that the text and "X" icon are both block element siblings that live within a tag item. If you force the max width of the text container to say, 80% of the parent element, you can then use "overflow:hidden" or "text-overflow: ellipsis" on that container to hide excess text without hiding the X.

I might try experimenting with this and see what it looks like.

**Comment by mbenford** [comment]
Any update on this?

**Comment by JAndritsch** [comment]
I did try what I suggested but didn't end up with a good result. Splitting the tag contents into separate sections of a percentage-based width works, but I ran into some problems where even really short tags were being truncated.

I'm still messing around with some ideas here and there. If I find something that works, I'll definitely submit a PR for it.

**Comment by mbenford** [comment]
Sorry for not replying sooner.

I'm closing this issue, but if you come up with a solution for this problem, please send a PR. :)

**Comment by zcsongor** [comment]
It's the same problem, right? https://github.com/mbenford/ngTagsInput/issues/287
The second comment contains the CSS code.
