### ISSUE TITLE
How to use ngmessages directive with input tag.

### ISSUE THREAD

**Issue by ittechsathish** [mbenford/ngTagsInput#373]
How to use ngmessages directive with input tag.

**Comment by mbenford** [comment]
ngMessages is part of Angular 1.3, which isn't supported yet. Apart from that, you should be able to use it along with ngTagsInput just fine.

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by ittechsathish** [comment]
Thanks for your reply, I will look some other option for validation to ngTagInput. Requesting you to develop & test with ngMessages.
