### ISSUE TITLE
angular-material support?

### ISSUE THREAD

**Issue by MilosStanic** [mbenford/ngTagsInput#374]
Any chance to have support for angular-material?
Can't hack the template to behave well with `<md-input-container>`.

**Comment by mbenford** [comment]
I don't know nothing about angular-material. :(

If you know how to do it, I'll be more than happy to accept your PR. :)

**Comment by mbenford** [comment]
Any update on this?

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by MilosStanic** [comment]
Hi, sorry, I definitely need this for my project, and will make a pull request as soon as I get to it. So you can close the issue. Thank you very much.

**Comment by mbenford** [comment]
OK. I'm looking forward to your PR. :)
