### ISSUE TITLE
Allow duplicate options

### ISSUE THREAD

**Issue by verblick** [mbenford/ngTagsInput#382]
I have go through the document and code and can't find an option to enable or allow duplicate tag input?

Is there any or similar option that allow tag to be input more than once?

**Comment by mbenford** [comment]
Currently there's no way to do that. There is a feature request in the backlog to enable using an arbitrary property of the tag object as an id, so it would be possible to have multiple tags with the same display text, but different underlying identifiers.

**Comment by mbenford** [comment]
This has already been implemented in master. Now there's a new option, `keyProperty` that allows you to  set a different property to uniquely identify a tag. You can either grab the [latest build](http://shrub.appspot.com/ng-tags-input) right now or wait for v2.3.0 to be released.

Can this issue be closed?
