### ISSUE TITLE
Arrow up and down events are canceled 

### ISSUE THREAD

**Issue by deje1011** [mbenford/ngTagsInput#384]
Hello Michael, 

thank you for writing and maintaining this directive. We are using it inside of a table in which the user should be able to navigate using the arrow keys (in combination with ctrl). Unfortunately we are not able to retrieve the arrow up and arrow down events as they are canceled in this event handler: 

```javascript
...
// Version 1.3.0 (line 603)
.on('input-keydown', function(e) {
   ...
   if (handled) {
         e.preventDefault();
         e.stopImmediatePropagation();
         scope.$apply();
   }
});
```
Would it be possible to leave out the stopImmediatePropagation-line? 

Looking forward to your response, 
Jesse

**Comment by mbenford** [comment]
Events are only stopped from begin propagated when they have been handled by the directive. This helps prevent side effects from happening. But, when a modifier is activated (e.g. ctrl, alt, shift), the directive ignores the event altogether, so in your case everything should work.

I don't know what version you are using. There is no v1.3.0. Never was. Are you using a fork?

**Comment by mbenford** [comment]
Any update on this?

**Comment by deje1011** [comment]
Thank you for replying, unfortunately I only received a notification about you second answer. So thanks again for helping github to keep me up to date. 
We are using version 2.1.1, I have no idea how i mixed that up. However, when I listen for the keydown event and print out the key-code, it does not fire as I press the up/down arrows (even in combination with alt/shift/ctrl). The key-codes for alt, shift and ctrl (and every other key as it seems) are logged properly. 

As soon as I find the time, I will try to reproduce the case in an isolated example.

**Comment by deje1011** [comment]
http://codepen.io/jjd/pen/JoqGvp

As long as there are items inside the autocompletion list, the events for going up and down do not bubble up (even if you press ctrl/alt/shift). The behavior makes sense but for us it would be much nicer to be able to listen for the event.

**Comment by mbenford** [comment]
Ok, I found out there's a bug in the `autocomplete` directive and keystrokes aren't ignored when a modifier is on. I'll add this to the backlog.
