### ISSUE TITLE
Responsive placeholder text

### ISSUE THREAD

**Issue by simonwaw** [mbenford/ngTagsInput#385]
May have missed it - what would be the best way to provide an alternative (shorter) placeholder string on responsive layouts??

Ie/  

placeholder="Enter some tags to start searching"
placeholder-short="Search"

**Comment by mbenford** [comment]
You can dynamically change the placeholder text by using active interpolation. Take a look at [this guide](http://mbenford.github.io/ngTagsInput/documentation/global-configuration). But you'll need to detect that the screen size has changed and act accordingly yourself.

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by simonwaw** [comment]
Thanks - managed to sort this out with the advice above.
