### ISSUE TITLE
Restful apis

### ISSUE THREAD

**Issue by denzelwamburu** [mbenford/ngTagsInput#387]
Hey,great work,but i have one issue though,i tried to make rest apis from the tag inputs but it seem to output an array which is [object object]
The input that are submitted are somehow not 'collected'.
How do i fix this?

**Comment by denzelwamburu** [comment]
![tagssjon](https://cloud.githubusercontent.com/assets/6532631/6550298/53b1dc78-c635-11e4-8855-cb493ec789af.png)

**Comment by mbenford** [comment]
ngTagsInput works with array of objects. That's what you model will look like after you bind it to the directive. It seems that you are treating it as an array of strings. You can do something like this in order to convert an array of objects into an array of strings:

```javascript
$scope.tagsString = $scope.tags.map(function(tag) { return tag.text; });
```

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by denzelwamburu** [comment]
@mbenford yeah i will let you know incase of anything
