### ISSUE TITLE
Case-insensitive matching in autoComplete

### ISSUE THREAD

**Issue by Shamilik** [mbenford/ngTagsInput#388]
Is there any way to make matching in autoComplete case-insensitive?

**Comment by mbenford** [comment]
What exactly do you mean by "matching"?

**Comment by Shamilik** [comment]
![image](https://cloud.githubusercontent.com/assets/2459175/6652197/4ed36126-ca78-11e4-8200-58a184e3c916.png)
![image](https://cloud.githubusercontent.com/assets/2459175/6652199/54e4bd30-ca78-11e4-8529-5982af8dc267.png)

**Comment by goull** [comment]
Up
I replaced the function with a decorator

app.config(function($provide) {
    $provide.decorator('tiUtil', function($delegate) {

        // myApp depends on the emailService from a third-party module, but the service is lacking a way to send email with signature.
        // To avoid reinventing the wheel and, as well as, maintaining a good habit of leaving third-party module intact,
        // I use $provide.decorator here to enhance emailService.
        $delegate.safeHighlight = function(str, value) {

            if (!value) {
                return str;
            }

            function escapeRegexChars(str) {
                return str.replace(/([.?*+^$[\]\\(){}|-])/g, '\\$1');
            }

            var expression = new RegExp('&[^;]+;|' + escapeRegexChars(value), 'gi');
            return str.replace(expression, function(match) {
                **changed to case insensitive match**
                **return match.toLowerCase() === value.toLowerCase() ? '<em>' + match + '</em>' : match;**
            });
        };

        return $delegate;
    });
});

**Comment by goull** [comment]
Could be implemented with a property on autocomplete tag (ex. <auto-complete highlight-ig="true"...)
