### ISSUE TITLE
ngTagsInput doesn't play well with AngularJS Batarang

### ISSUE THREAD

**Issue by markwongsk** [mbenford/ngTagsInput#393]
Pre-requisites: Have the AngularJS Batarang extension installed
1. Have some tags, try deleting a previous tag by pressing backspace.
2. Expected: previous tag gets highlighted into red on the first press, then deleted.
3. Actual: two tags get deleted.

FWIW the "input-keydown" event gets triggered four times. Also, I couldn't repro this if I open the .html file directly, only if it were served via a server. Granted, I think this is probably a bug on Batarang's side, but I would like to flag this nonetheless.

**Comment by mbenford** [comment]
That's really odd. I can reproduce it, and actually the `keydown` event is triggered four times, which in turn triggers four `input-keydown` events. It indeed seems to be a bug in Batarang. Let me know if you find out anything else.

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by markwongsk** [comment]
Yep! Thanks :)
