### ISSUE TITLE
Show placeholder text only when there are no tags

### ISSUE THREAD

**Issue by jukkasi** [mbenford/ngTagsInput#395]
I would appreciate a feature where the placeholder text is not visible when there is one ore more tags in input. Our placeholder texts are quite long and taking a lot of space together with many tags.

**Comment by mbenford** [comment]
You can dynamically change the placeholder text (or any other option, for that matter) by using active interpolation. Take a look at [this guide](http://mbenford.github.io/ngTagsInput/documentation/global-configuration).

**Comment by kevinrenskers** [comment]
What I did was something like `<tags-input ng-class="{'has-tags': mymodel.length}"` and then with css just hide the placeholder.

**Comment by mbenford** [comment]
@kevinrenskers Nice solution!

**Comment by jukkasi** [comment]
Thanks for the tips, will look into these

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by jukkasi** [comment]
Yes
