### ISSUE TITLE
Is it possible to limit the input tag?

### ISSUE THREAD

**Issue by sdiwu** [mbenford/ngTagsInput#397]
As the example shown at here:
http://plnkr.co/edit/CX9b1k

Is it possible to limit the tag? 

For example, I want to limit the inputted tags to one tag only, so after a tag has been inputted, the autocomplete textfield become disabled and user can't input any new tags nor typing on the textfield, but he can remove the inputted tag so the textfield become enabled again and he can re-input a new tag.

I found `max-tags` option, but it only for showing warning if inputted tags number are larger than max-tags.

**Comment by mbenford** [comment]
> Is it possible to limit the tag?

Not right now. But you can accomplish that behavior by using a helper directive. [Here](https://github.com/mbenford/ngTagsInput/issues/210#issuecomment-52431874) you can find more info on that.

**Comment by sdiwu** [comment]
Thanks, it helps. I hope it can be made as main feature though.

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by sdiwu** [comment]
Sure.
