### ISSUE TITLE
Compatibility on Internet explorer

### ISSUE THREAD

**Issue by Duovili** [mbenford/ngTagsInput#398]
I have the directive working well on all browsers except IE. I cant add a tag in IE. Do you know of this bug and perhaps have a work around for IE?

**Comment by mbenford** [comment]
What version of IE are you using? ngTagsInput works only with IE 10+.

**Comment by Duovili** [comment]
the system is ie9 to 11. Do you perhaps know of a work around?

On 17 March 2015 at 18:05, Michael Benford <notifications@github.com> wrote:

> What version of IE are you using? ngTagsInput works only with IE 10+.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbenford/ngTagsInput/issues/398#issuecomment-82436139>
> .
>



-- 
Ross Rawlins
*Tel:* 021 531 7087
*Cell:* 072 424 9480
*Skype:* ross.rawlins
*Email:* ross@duovili.co.za

<http://www.duovili.co.za>
<https://plus.google.com/113781084234234096576/posts>
<https://www.facebook.com/Duovili>
<http://www.linkedin.com/company/duovili/>     <https://twitter.com/Duovili>


This e-mail message and all attachments contain the CONFIDENTIAL AND
PROPRIETARY information of DUOVILI DEVELOPMENTS. and may contain LEGALLY
PRIVILEGED information. If you are not the intended recipient, you are
hereby notified that any disclosure, distribution, or use of this e-mail,
its attachments or any information contained therein is unauthorised and
prohibited. If you have received this in error, please contact the sender
immediately and delete this e-mail and any attachments.

**Comment by mbenford** [comment]
Do you mean the directive doesn't work in any IE from 9 to 11? In addition to that, what version of ngTagsInput and Angular are you using?

**Comment by Duovili** [comment]
I am running v2.1.1, and it seems to work on the later versions just not
the one you said is not supported. Do you have any plans to make it
supported for ie 9?

On 17 March 2015 at 20:38, Michael Benford <notifications@github.com> wrote:

> Do you mean the directive doesn't work in any IE from 9 to 11? In addition
> to that, what version of ngTagsInput and Angular are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbenford/ngTagsInput/issues/398#issuecomment-82516840>
> .
>



-- 
Ross Rawlins
*Tel:* 021 531 7087
*Cell:* 072 424 9480
*Skype:* ross.rawlins
*Email:* ross@duovili.co.za

<http://www.duovili.co.za>
<https://plus.google.com/113781084234234096576/posts>
<https://www.facebook.com/Duovili>
<http://www.linkedin.com/company/duovili/>     <https://twitter.com/Duovili>


This e-mail message and all attachments contain the CONFIDENTIAL AND
PROPRIETARY information of DUOVILI DEVELOPMENTS. and may contain LEGALLY
PRIVILEGED information. If you are not the intended recipient, you are
hereby notified that any disclosure, distribution, or use of this e-mail,
its attachments or any information contained therein is unauthorised and
prohibited. If you have received this in error, please contact the sender
immediately and delete this e-mail and any attachments.

**Comment by Duovili** [comment]
I just tested it again and it work fine on ie 9 -11, I think there is a
compile issue that is breaking it thanks for helping you can close this
ticket

On 18 March 2015 at 08:42, Ross Rawlins <ross@duovili.co.za> wrote:

> I am running v2.1.1, and it seems to work on the later versions just not
> the one you said is not supported. Do you have any plans to make it
> supported for ie 9?
>
> On 17 March 2015 at 20:38, Michael Benford <notifications@github.com>
> wrote:
>
>> Do you mean the directive doesn't work in any IE from 9 to 11? In
>> addition to that, what version of ngTagsInput and Angular are you using?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mbenford/ngTagsInput/issues/398#issuecomment-82516840>
>> .
>>
>
>
>
> --
> Ross Rawlins
> *Tel:* 021 531 7087
> *Cell:* 072 424 9480
> *Skype:* ross.rawlins
> *Email:* ross@duovili.co.za
>
> <http://www.duovili.co.za>
> <https://plus.google.com/113781084234234096576/posts>
> <https://www.facebook.com/Duovili>
> <http://www.linkedin.com/company/duovili/>
> <https://twitter.com/Duovili>
>
> This e-mail message and all attachments contain the CONFIDENTIAL AND
> PROPRIETARY information of DUOVILI DEVELOPMENTS. and may contain LEGALLY
> PRIVILEGED information. If you are not the intended recipient, you are
> hereby notified that any disclosure, distribution, or use of this e-mail,
> its attachments or any information contained therein is unauthorised and
> prohibited. If you have received this in error, please contact the sender
> immediately and delete this e-mail and any attachments.
>



-- 
Ross Rawlins
*Tel:* 021 531 7087
*Cell:* 072 424 9480
*Skype:* ross.rawlins
*Email:* ross@duovili.co.za

<http://www.duovili.co.za>
<https://plus.google.com/113781084234234096576/posts>
<https://www.facebook.com/Duovili>
<http://www.linkedin.com/company/duovili/>     <https://twitter.com/Duovili>


This e-mail message and all attachments contain the CONFIDENTIAL AND
PROPRIETARY information of DUOVILI DEVELOPMENTS. and may contain LEGALLY
PRIVILEGED information. If you are not the intended recipient, you are
hereby notified that any disclosure, distribution, or use of this e-mail,
its attachments or any information contained therein is unauthorised and
prohibited. If you have received this in error, please contact the sender
immediately and delete this e-mail and any attachments.

**Comment by RobzInadE** [comment]
Hi,

We're also having issues in IE. The problem is `KEYS.delete` where 'delete' is a protected keyword in javascript. Do you mind if I submit a pull-request renaming 'delete' to something more js-friendly, like 'del' ?

Regards
