### ISSUE TITLE
replaceSpacesWithDashes not respected

### ISSUE THREAD

**Issue by goodforenergy** [mbenford/ngTagsInput#399]
As per [this Plunkr](http://plnkr.co/edit/Hw7sJ6?p=preview), despite setting replaceSpacesWithDashes to false, when you type "Ty" and select one of the autocompleted suggestions, it will insert dashes into the tag name. It doesn't seem to matter if you select one of the autocompleted suggestions or type a new tag.

Am I missing something or is this a bug? Any help appreciated.

Cheers,

Helen

**Comment by mbenford** [comment]
You should use `replace-spaces-with-dashes` instead of `replaceSpacesWIthDashes`. That's how Angular processes elements and attributes in HTML. From their [guide](https://docs.angularjs.org/guide/directive#normalization) on directives:

> Angular normalizes an element's tag and attribute name to determine which elements match which directives. We typically refer to directives by their case-sensitive camelCase normalized name (e.g. ngModel). However, since HTML is case-insensitive, we refer to directives in the DOM by lower-case forms, typically using dash-delimited attributes on DOM elements (e.g. ng-model).

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by goodforenergy** [comment]
Hi @mbenford, sorry I never replied, I've been away and saw but never responded to your last post. Yes, I will close now - thanks for the note, works like a charm. I've been working with Angular for months now and that still trips me up now and then.. doh. Thanks!
