### ISSUE TITLE
What is the plan to release version 2.3.0? How could I install the most recent build using bower/npm?

### ISSUE THREAD

**Issue by vcardins** [mbenford/ngTagsInput#400]

**Comment by mbenford** [comment]
I'm going to release version 2.3.0 later this week. Unfortunately it's not possible to install the most recent build with npm or bower right now.

**Comment by vcardins** [comment]
Ok, thank you for the prompt response !!

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by mbenford** [comment]
v2.3.0 is already published on both bower and npm.
