### ISSUE TITLE
$compile issue

### ISSUE THREAD

**Issue by Duovili** [mbenford/ngTagsInput#401]
I am getting a sporadic error where I get a compile error for the directive.
Error: [$compile:tpload] http://errors.angularjs.org/1.3.13/$compile/tpload?p0=ngTagsInput%2Ftags-input.html
    at Error (native)
    at http://localhost:63470/webapp/bundle.js:1375:417
    at http://localhost:63470/webapp/bundle.js:1505:257
    at http://localhost:63470/webapp/bundle.js:1481:20
    at l.$eval (http://localhost:63470/webapp/bundle.js:1494:305)
    at l.$digest (http://localhost:63470/webapp/bundle.js:1491:398)
    at l.$apply (http://localhost:63470/webapp/bundle.js:1495:58)
    at l (http://localhost:63470/webapp/bundle.js:1450:171)
    at P (http://localhost:63470/webapp/bundle.js:1454:301)
    at XMLHttpRequest.w.onload (http://localhost:63470/webapp/bundle.js:1455:315)

That is the error I am getting. Is this a known bug? Do you have a fix?

**Comment by mbenford** [comment]
> Failed to load template: ngTagsInput/tags-input.html

That template file is loaded by ngTagsInput into the `templateCache` service. It seems that you are compiling some markup before loading the `ng-tags-input.js` file.

In addition to that, I see you're using Angular 1.3, and ngTagsInput isn't officially compatible with that version yet. That doesn't necessarily mean it won't work with that particular version, just that I can't guarantee it will.

**Comment by Duovili** [comment]
Would you recommend I revert back to an older version of angular? A version
of 1.2?

On 17 March 2015 at 20:48, Michael Benford <notifications@github.com> wrote:

> Failed to load template: ngTagsInput/tags-input.html
>
> That template file is loaded by ngTagsInput into the templateCache
> service. It seems that you are compiling some markup before loading the
> ng-tags-input.js file.
>
> In addition to that, I see you're using Angular 1.3, and ngTagsInput isn't
> officially compatible with that version yet. That doesn't necessarily mean
> it won't work with that particular version, just that I can't guarantee it
> will.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbenford/ngTagsInput/issues/401#issuecomment-82522768>
> .
>



-- 
Ross Rawlins
*Tel:* 021 531 7087
*Cell:* 072 424 9480
*Skype:* ross.rawlins
*Email:* ross@duovili.co.za

<http://www.duovili.co.za>
<https://plus.google.com/113781084234234096576/posts>
<https://www.facebook.com/Duovili>
<http://www.linkedin.com/company/duovili/>     <https://twitter.com/Duovili>


This e-mail message and all attachments contain the CONFIDENTIAL AND
PROPRIETARY information of DUOVILI DEVELOPMENTS. and may contain LEGALLY
PRIVILEGED information. If you are not the intended recipient, you are
hereby notified that any disclosure, distribution, or use of this e-mail,
its attachments or any information contained therein is unauthorised and
prohibited. If you have received this in error, please contact the sender
immediately and delete this e-mail and any attachments.

**Comment by mbenford** [comment]
> Would you recommend I revert back to an older version of angular?

Not at all. That would probably cause more harm than good to you. Besides, there are some people using ngTagsInput along with Angular 1.3 and none of them has reported this particular problem.

As I said above, the `tags-input.html` file isn't being added to template cache. I see you're using a bundle file; perhaps during the its generation something is being included out of order.

**Comment by mbenford** [comment]
Any update on this?

**Comment by Duovili** [comment]
I had to force a refresh. Only quick way to solve this. you can close the
ticket.

On 25 March 2015 at 05:26, Michael Benford <notifications@github.com> wrote:

> Any update on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbenford/ngTagsInput/issues/401#issuecomment-85811935>
> .
>



-- 
Ross Rawlins
*Tel:* 021 531 7087
*Cell:* 072 424 9480
*Skype:* ross.rawlins
*Email:* ross@duovili.co.za

<http://www.duovili.co.za>
<https://plus.google.com/113781084234234096576/posts>
<https://www.facebook.com/Duovili>
<http://www.linkedin.com/company/duovili/>     <https://twitter.com/Duovili>


This e-mail message and all attachments contain the CONFIDENTIAL AND
PROPRIETARY information of DUOVILI DEVELOPMENTS. and may contain LEGALLY
PRIVILEGED information. If you are not the intended recipient, you are
hereby notified that any disclosure, distribution, or use of this e-mail,
its attachments or any information contained therein is unauthorised and
prohibited. If you have received this in error, please contact the sender
immediately and delete this e-mail and any attachments.
