### ISSUE TITLE
Add Support for Custom Container

### ISSUE THREAD

**Issue by jgodi** [mbenford/ngTagsInput#402]
I would be nice to specify what container to place the autocomplete in. 

e.x. Append to BODY rather in inline

**Comment by mbenford** [comment]
That's not possible. The current structure is a requirement for the `autoComplete` directive to work.

But I'm curious: why would you want to place the autocomplete markup anywhere else in the DOM?

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by jgodi** [comment]
Yes, sry!

**Comment by ceyhunnabiyev** [comment]
> But I'm curious: why would you want to place the autocomplete markup anywhere else in the DOM?

@mbenford , if you have scrolled container div () inside body, when suggestion list is loaded,  every time you have to scroll the container div to the end  to see the suggestion list.
