### ISSUE TITLE
Error: type property can't be changed

### ISSUE THREAD

**Issue by Gargol** [mbenford/ngTagsInput#405]
The tagsinput component is being initialized inside of `$scope.$apply` and this error is being thrown `Error: type property can't be changed` in this block:

```javascript
tagsInput.directive('tiBindAttrs', function() {
    return function(scope, element, attrs) {
        scope.$watch(attrs.tiBindAttrs, function(value) {
            angular.forEach(value, function(value, key) {
                attrs.$set(key, value);
            });
        }, true);
    };
});
```
to be exact it gets thrown at : `attrs.$set(key, value);`

The question is how could this be prevented and whether or not this is a bug?

**Comment by mbenford** [comment]
Are you using jQuery? What version?

**Comment by Gargol** [comment]
Hi we are at `1.8.3`. Thanks for getting back so fast btw :+1:

**Comment by mbenford** [comment]
That version of jQuery doesn't allow changing the input `type` attribute. You should upgrade it to at least 1.9.x. More information on that issue [here](http://bugs.jquery.com/ticket/13011).

**Comment by Gargol** [comment]
Great. Will look into that. Thank you for your time and support.
