### ISSUE TITLE
Error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by daric81** [mbenford/ngTagsInput#408]
In my use case of ngTagsInput, If the bound ngModel is undefined is get the following error;

*"Cannot read property 'length' of undefined"*

at the following;
**ngModelCtrl.$setValidity('maxTags', scope.tags.length <= options.maxTags)**

maybe this should be changed to something like;

**ngModelCtrl.$setValidity('maxTags', scope.tags.length || 0 <= options.maxTags)**

and also the same for options.minTags validity.

**Comment by mbenford** [comment]
Currently the `tagsInput` directive automatically initializes your model as an empty array if it's undefined, so that error shouldn't occur.

Could you provide a plunker showing your problem? You can use [this template](http://plnkr.co/edit/tpl:Y7cuEGojnyGLbsUXJL1k).

**Comment by daric81** [comment]
Hi Michael,
I thought I'd recreated our use case in the following [plunker](http://plnkr.co/edit/eMWORML7Bb7Ni1inAd4Q?p=preview).However this doesn't recreate the issue in our solution.

I'm happy for you to close this off and If I can repro I'll post a plunker. Apologies for any inconvenience.
