### ISSUE TITLE
email type not working 

### ISSUE THREAD

**Issue by amalmansouri** [mbenford/ngTagsInput#411]
I'm trying to use email type but it's not working? I'm I doing something wrong or it's a bug?

here is my sample

<code>
  form name="form">
          tags-input type="email" ng-model="numbers" name="email"
                placeholder="Add a number" >
    /tags-input>
    p>Model: {{numbers}}</p>
    /form>
{{form.email.$valid}}
</code>
always shows valid = true even if I entered 123, test values 

it should be validating an email to be test@test.com <<
Any help?

**Comment by renanlecaro** [comment]
The email type is mainly to get the right keyboard on mobile.
Use the on-tag-adding to return true or false depending on the type of input.
`<tags-input on-tag-adding="returnsTrueIfEmail($tag)"></tags-input>`
http://mbenford.github.io/ngTagsInput/documentation/api

**Comment by amalmansouri** [comment]
I have solve it manually by checking on user input but it should be validated by type when I choose email as a type.

**Comment by mbenford** [comment]
@amalmansouri I agree with you that the directive should take the `type` attribute into account before adding a tag. I don't know exactly how to do that now, but I'll add this to the backlog so I can work on it later.

**Comment by duall** [comment]
or just add
allowed-tags-pattern="^[A-Za-z0-9._%+-]+@(?:[A-Za-z0-9-]+\.)+[A-Za-z]{2,}"

**Comment by victorbadila** [comment]
+1 on this

**Comment by bpinhosilva** [comment]
+1 on this.

**Comment by santosguilherme** [comment]
+1

**Comment by joesleiman** [comment]
+1 @duall

**Comment by reggielee** [comment]
+1

**Comment by mdopieralski** [comment]
+1

**Comment by chozzz** [comment]
+1

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by abdo-host** [comment]
add this attribute

> allowed-tags-pattern="^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$"

`<tags-input ng-model="emails" placeholder="Add Emails" allowed-tags-pattern="^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$"></tags-input>
`
