### ISSUE TITLE
custom template support example

### ISSUE THREAD

**Issue by aacanakin** [mbenford/ngTagsInput#413]
Hi,
Can you add a sample demo on implementing custom templates?

**Comment by mbenford** [comment]
I'll update the website with examples and detailed documentation on custom templates later this week.

In the meantime, you can take a look at this [plunk](http://plnkr.co/edit/fIhvMku9q7UfbfwN5EJQ?p=preview). Let me know if you need more information.

**Comment by mbenford** [comment]
I updated the [Demos page](http://mbenford.github.io/ngTagsInput/demos) so it contains custom templates examples as well. I also added a [detailed guide](http://mbenford.github.io/ngTagsInput/documentation/guides/custom-templates) on how to create custom templates.

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by paul-barry-kenzan** [comment]
@mbenford 
Your demos page is failing. Is there another location where example HTML can be viewed?

<img width="1037" alt="screen shot 2015-12-09 at 2 00 30 pm" src="https://cloud.githubusercontent.com/assets/12274057/11695456/400495aa-9e7d-11e5-9810-05398dedd932.png">
