### ISSUE TITLE
Clear Invalid Tag

### ISSUE THREAD

**Issue by barathank** [mbenford/ngTagsInput#414]
How to clear the invalid Tag from the Tags Input, The user entered text is still present in the Tag Input control if it is invalid.

**Comment by mbenford** [comment]
Currently there's no built-in way to do that. Version 3.0.0 will introduce a new property that will enable that, though.

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by barathank** [comment]
Sure, thanks for the heads up!

**Comment by zardaloop** [comment]
Is there any work around for that?Cheer.

**Comment by PratibhaP** [comment]
@mbenford as per you mentioned that clear invalid tags option will be introduced in version3.0.0. 
We have 3.1.1 version now. Can you help me to clear invalid tags? 
Thank you in advance?
