### ISSUE TITLE
accessibility issue with tags

### ISSUE THREAD

**Issue by longmatthewh** [mbenford/ngTagsInput#416]
The delete anchors with class remove-button are not keyboard accessible.

**Comment by mbenford** [comment]
You can select and remove tags by using both left and right arrow keys when the input is empty. After selecting a tag, just press backspace or delete to remove it. Take a look at the following gif:

![Imgur](http://i.imgur.com/IYuuWES.gif)

That's not very well documented, though. But I'm working on it.

But, I don't think that makes the directive accessible, does it?

**Comment by mbenford** [comment]
Any update on this?

**Comment by longmatthewh** [comment]
Thanks for the reply/reminder. Is the usage of arrow keys a config option?
Using the arrow keys is nice, but if you want to rely on arrow keys, the
least that will need to be done is to use aria to indicate which tag is
selected. The problem with an aria only solution, though, is that there's
not a role, like "tree" for tags. Making the x's tab-able with offscreen
text indicating that it's for deleting the corresponding tag could work.
Are you interested in a pull request?

**Comment by mbenford** [comment]
Sorry for not replying sooner.

Yes, I'm definitely interested in a PR. I don't know much about accessibility, so I appreciate any help on that matter.

**Comment by maia-n** [comment]
Hi Michael and Matthew,
so good to hear about that. I was about to do a similar fix to have ARIA roles included and input form labels as well.
Anyway, I tested it and the basic keyboard use is supported, though it can be optimized  :)

One very simple thing that can be done meanwhile is to parametrize HTML templates.. so everyone could use their own with or without ARIA roles..
Yes Matthew, I am interested too!

**Comment by kfeinUI** [comment]
Would like to see this as well.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
