### ISSUE TITLE
show autocomplete on click (drop-down arrow icon)  

### ISSUE THREAD

**Issue by GeekOnGadgets** [mbenford/ngTagsInput#417]
Hi ,
I want the drop-down arrow image on tag-input and then on-click it should show the autocomplete. Is there a way to achieve this ? Please let me know.

PS: Every nice plugin. Good job

**Comment by mbenford** [comment]
You may try to insert an arrow image by tweaking with the directive's CSS, but there's no way to force the autocomplete to load without using the keyboard.

**Comment by mbenford** [comment]
Can this issue be closed?
