### ISSUE TITLE
Don't set validation errors if option is not set

### ISSUE THREAD

**Issue by ValentinH** [mbenford/ngTagsInput#420]
In [this block](https://github.com/mbenford/ngTagsInput/blob/master/src/tags-input.js#L245), I think that each ```ngModelCtrl.$setValidity``` should only be called if options.minTags (for instance), is defined.

If I use a tag input inside a form and I don't want to fix a tags count limit, I don't want to see an error message! ;)

**Comment by mbenford** [comment]
`minTags` is always defined. If you don't provide it with a value it will default to a predefined value. Them same is true for `maxTags` and almost all other options.

What error message are you seeing, exactly?

**Comment by ValentinH** [comment]
Actually, I am using a fork from an old version that I have heavily patched for my project purpose. So this problem might have been fixed. I just need to find what I need to take from the latest version.

What I meant by error was that those classes were added to the field: ```ng-invalid ng-invalid-max-tags ng-invalid-min-tags``` even if I haven't provided any minTags or maxTags...
