### ISSUE TITLE
Placeholders don't work in IE9

### ISSUE THREAD

**Issue by clintharris** [mbenford/ngTagsInput#421]
The placeholder text isn't shown in IE9.

I've tried adding [this](https://github.com/urish/angular-placeholder-shim) popular shim for fixing the placeholder in IE9; placeholder text is visible but collides with tags and the hidden text input.

**Comment by mbenford** [comment]
ngTagsInput only works with IE10+, so I don't know exactly how to help you. :disappointed: 

I think you need to debug the source code to understand why the shim you mentioned didn't work along with this directive.
