### ISSUE TITLE
How do I submit tags through a form?

### ISSUE THREAD

**Issue by DABESTAPPSEVER** [mbenford/ngTagsInput#423]
If I have a `form` with a `tags-input` full of tags, how do I submit the form with those tags?

**Comment by kewball** [comment]
This is what I'm working on today. It seems to work okay for now
```javascript
          $scope.saveTags = function (thg) {
            console.log('myngTW.saveTags begins', thg);
            if (thg) {
              var flatTags = thg.tags.map(function (o) {
                return o.text;
              });
              console.log('flatTags:', flatTags);
              PillThg.upone({ id: thg.id, tags: flatTags })
                .then(function (res) {
                  PillTag.index()
                    .then(function (res) {
                      //$scope.pkg.alltags = res.data.tags;
                      $scope.alltags = res.data.tags;
                    });
                });
            }
          }
```
PillThg.upone saves a Thing in the database; PillTag.index fetches a new tag list for autocomplete.

**Comment by DABESTAPPSEVER** [comment]
@kewball Interesting! What does your HTML look like?

**Comment by kewball** [comment]
the multiple $parent on autocomplete is suboptimal; I need to re-think the layout of this template :)
```html
            <tags-input
                    on-blur="$parent.saveTags( $parent.thg )"
                    ng-model="$parent.thg.tags"
                    replace-spaces-with-dashes="false">
              <auto-complete min-length="1" source="$parent.$parent.$parent.loadSuggestions($query)"></auto-complete>
            </tags-input>
```

**Comment by DABESTAPPSEVER** [comment]
Ahh that looks a bit complex for me. I'm trying to figure out how to apply that to my [simpler code](https://github.com/mbenford/ngTagsInput/issues/428)...

**Comment by DABESTAPPSEVER** [comment]
Actually, I put `ng-submit="submit()"` in my form, and it seems to work.

<form ng-controller="fetchTagsCtrl" ng-submit="submit()">
		<div class="form-group">
			<tags-input 
				ng-model="tags" 
				ng-class="{'has-tag': tags.length}"  
				display-property="name"
				replace-spaces-with-dashes="false"
				placeholder="What are you in the mood for?">
			  <auto-complete 
			  	source="tagSuggestions($query)"
			  	min-length="3"></auto-complete>
			</tags-input>
		</div>
		<button type="submit" class="btn btn-primary">Find films</button>
		<p>
			Model: {{tags}}
		</p>
	</form>

and my JS;
	var app = angular.module('cultmovies',['ngTagsInput']);
	app.controller('fetchTagsCtrl',function($scope,$http){
		$scope.tagSuggestions = function(query){
			result = $http({
				url: '/tags/fetch',
				method: 'GET',
				params: {
					input: query
				}
			});
			return result;
		};

		$scope.submit = function(){
			var tagObjectArray = $scope.tags;
			var tagIdArray = tagObjectArray.map(function(obj){
				return obj.id;
			});
			console.log(tagIdArray);
		};
	});

`console.log()` prints the IDs from the tag objects.

**Comment by mbenford** [comment]
@DABESTAPPSEVER  Is your question about submitting a list of items to a server or is it specific to ngTagsInput?

**Comment by DABESTAPPSEVER** [comment]
Specific to ngTagsInput, but I used the AngularJS' `ng-submit` and `submit()`

**Comment by nayzawoo** [comment]
```
<input ng-repeat="item in items" type="hidden" name="items[]" value="{{ item.name }}" />
<tags-input display-property="name" ng-model="items"></tags-input>
```

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by DABESTAPPSEVER** [comment]
Yes
