### ISSUE TITLE
HighlightMatchedText not working

### ISSUE THREAD

**Issue by ebtc** [mbenford/ngTagsInput#424]
Hi there,

I am using the directive as follows:

    <tags-input
        ng-model="personCtrl.tags"
        replace-spaces-with-dashes="false"
        addFromAutocompleteOnly="false"
        placeholder="{{'Add a tag' | translate}}">
        <auto-complete
          source="personCtrl.loadTags($query)"
          selectFirstMatch="false"
          highlightMatchedText="false"></auto-complete>
      </tags-input>

The problem now is that when I add a tag that is not yet in "tags" it will select the first from the autocomplete when I press "Enter". But I want to have the new tag entered instead.

This behaviour does not appear when I click outside the input box. In this case it enters the correct data (the new tag). So I guess this has to do with selectFirstMatch() not doing it's job properly.

Tested on Chrome with angular 1.3.15.

Btw: this also happens on your demo examples.

**Comment by stclem93** [comment]
You are using the wrong syntax. It's `add-from-autocomplete-only="false"` and `highlight-matched-text="false"` and `select-first-match="false"`. See the API usage.

**Comment by ebtc** [comment]
Thanks! I am an idiot :laughing:
