### ISSUE TITLE
How to disable the creation of new tags

### ISSUE THREAD

**Issue by playUruguay** [mbenford/ngTagsInput#425]
Hi! 
Im trying to use ngTagsInput like a select with suggesting existent data.
How to disable the creation of new labels ?
<pre>
<tags-input ng-model="tags" display-property="name">
    <auto-complete source="loadTags($query)"></auto-complete>
</tags-input>
</pre>
<pre>
$scope.loadTags = function(query) {
	 	return $http.get('/api/users?conditions={ "name": { "$regex": "' + query + '" } }', config);
	};
</pre>

**Comment by oleksiyo** [comment]
Hi.
Try set property  add-from-autocomplete-only="true" for your tags-input

**Comment by codefullon** [comment]
hi @oleksiyo did try that but folks can still type things inside the input box, what i want to do instead is have it such that only the pre-populated tags appear and nothing more can be manually entered - curious, how can I make this happen?

**Comment by mbenford** [comment]
@playUruguay Set the `add-from-autocomplete-only` option as true, as suggested by @oleksiyo, and the user will be able to add tags only by selecting a suggestion from the autocomplete list.

@codefullon ngTagsInput supports Angular's `ngDisabled` directive. If you do the following the `tags-input` element will be disabled and the user won't be able to neither add nor remove any tags.

```html
<tags-input ng-model="tags" ng-disabled="true"></tags-input>
```

**Comment by codefullon** [comment]
excellent, thanks @mbenford, that worked :-)

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by codefullon** [comment]
absolutely :-)
