### ISSUE TITLE
tag with special character e.g C#

### ISSUE THREAD

**Issue by mfandre** [mbenford/ngTagsInput#427]
Tag with special characters like C# doesnt working when select. Filter ok but when I click to select tag nothing happens.

**Comment by mbenford** [comment]
Could you create a plunker or something showing your problem? You can use [this template](http://plnkr.co/edit/tpl:Y7cuEGojnyGLbsUXJL1k).

**Comment by mfandre** [comment]
http://plnkr.co/edit/11MBw7Blb1pAuBTUtMqZ

**Comment by dboczek** [comment]
There is no problem with special character ```#```. By default tag needs to have at least 3 characters.
adding ```min-length="1"``` to ```tags-input``` fixes the issue.

Adding ```min-length="1"``` (not ```minLength=1```) to ```auto-complete``` will show tag selector after inputing just one character.

```
  <body ng-controller="MainCtrl">
    <tags-input ng-model="tags" min-length="1">
      <auto-complete min-length=1 source="loadTags($query)"></auto-complete>
    </tags-input>
  </body>
```

http://plnkr.co/edit/Tkt9NdVX7UREtsXPH3hZ

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by VanHumbeeckA** [comment]
C# not working. He removes the hashtag, resulting in 'C'

**Comment by juddey** [comment]
Just stumbled on this issue thanks @dboczek for posting your comment. I've had no problem with C# as an input tag after applying your solution, although I did have to tinker with the auto-complete tag just slightly, it became: ` min-length=0`. I'm restricting users to only pick from tags in a known list though.

If I enter a 'C', I don't see C# in the autocomplete list, but that might be more to do with angular's filter than this module... Once I enter C# I'm able to search.

HTH

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
