### ISSUE TITLE
Placeholder value won't clear when I enter at least one tag

### ISSUE THREAD

**Issue by DABESTAPPSEVER** [mbenford/ngTagsInput#428]
I want `tags-input`'s placeholder value to be `""` when I've entered at least one tag. 

Here's `index.html`

    <form ng-controller="fetchTagsCtrl">
	<div class="form-group">
		<tags-input ng-model="tags" ng-class="{'has-tag': tags.length}" display-property="name">
		  <auto-complete source="tagSuggestions($query)"></auto-complete>
		</tags-input>
	</div>
	<button type="submit" class="btn btn-primary">Find films</button>
	<p>
		Model: {{tags}}
	</p> 
    </form>

And `app.js`

    var app = angular.module('cultmovies',['ngTagsInput']);

    app.config(function(tagsInputConfigProvider) {
	var placeholderString = 'What are you in the mood for?';
      tagsInputConfigProvider.setActiveInterpolation('tagsInput', {
        placeholder: placeholderString
      });
    });

    app.controller('fetchTagsCtrl',function($scope,$http){
	$scope.tagSuggestions = function(query){
		result = $http({
			url: '/tags/fetch',
			method: 'GET',
			params: {
				input: query
			}
		});

		return result;
	};
    });

`style.css`
      `tags-input.has-tags input {
          display: none;
      }`

I followed kevinrensers's advice in [this issue](https://github.com/mbenford/ngTagsInput/issues/395), but the placeholder text won't clear.

**Comment by mbenford** [comment]
Hiding the input element will prevent the user from adding any news tags, and I guess that's not what you want. In order to change the `placeholder` attribute dynamically, you need to use [active interpolation](http://mbenford.github.io/ngTagsInput/documentation/global-configuration):

```javascript
app.config(function(tagsInputConfigProvider) {
  tagsInputConfigProvider.setDefaults('tagsInput', { placeholder: '' });
  tagsInputConfigProvider.setActiveInterpolation('tagsInput', { placeholder: true });
});
```

Now you can simply use an Angular expression in your markup:

```html
<tags-input ng-model="tags" 
            placeholder="{{tags.length ? '' : 'What are you in the mood for?'}}">
</tags-input>
```

[Working Plunker](http://plnkr.co/edit/jYEf7FdaQh4sCBE4aMkv?p=preview)

Finally, this kind of question belongs in StackOverflow, since it's about *how* to use ngTagsInput. Just be sure to use the `ng-tags-input` tag so I get a notification.

**Comment by DABESTAPPSEVER** [comment]
Yep, that did it!

**Comment by joesleiman** [comment]
where should i put 
app.config(function(tagsInputConfigProvider) {
  tagsInputConfigProvider.setDefaults('tagsInput', { placeholder: '' });
  tagsInputConfigProvider.setActiveInterpolation('tagsInput', { placeholder: true });
});

**Comment by joesleiman** [comment]
how can i remove the placeholder at all ? not putting a space just remove it .
another question : i want the placeholde to be removed when all the tags are existing and when i remove all the tags a placeholder appear "add tags" for example

**Comment by passiondev211** [comment]
@mbenford Where should I insert the active interpolation.
```
app.config(function(tagsInputConfigProvider) {
  tagsInputConfigProvider.setDefaults('tagsInput', { placeholder: '' });
  tagsInputConfigProvider.setActiveInterpolation('tagsInput', { placeholder: true });
});
```

**Comment by BaamAadmi** [comment]
I cannot override app.config because, 'ngTagsInput' config comes from anther library. How do I actively interpolate in that case ?
