### ISSUE TITLE
Add a 'class' attribute to specify the CSS class

### ISSUE THREAD

**Issue by beradrian** [mbenford/ngTagsInput#431]

**Comment by beradrian** [comment]
At this moment I think you can only embed the element in another one and specify a class for the enclosing element.

**Comment by mbenford** [comment]
You *can* use `class` with the `tags-input` directly:

```html
<style>
    .my-class .tags .tag-item {
        background: lime;
    }
</style>

<tags-input ng-model="tags" class="my-class"></tags-input>
```

[Plunker](http://plnkr.co/edit/oDmoR7wHKObwHjmKPByl?p=preview)

**Comment by beradrian** [comment]
Thanks!
