### ISSUE TITLE
Autocomplete: Adding a tag by clicking dropdown item in Firefox only adds typed letters, not dropdown item

### ISSUE THREAD

**Issue by pfarnach** [mbenford/ngTagsInput#435]
It seems like there's a bug in Firefox where if you start typing, say "te" and the autocomplete dropdown comes up with "test", and if you click on "test", a tag will be added that is only "te".  This doesn't happen in Chrome or IE10 (you get "test" as expected).  Please let me know if there is a known fix.  Thanks!

Edit: If it helps, I noticed that if you select the dropdown item with the keyboard, it works as expected. It's only on click when it doesn't select the dropdown item.

Edit2: What it comes down to is addSuggestionByIndex() is not being called by the ng-click on the <li> autocomplete element in Firefox but it is in Chrome.  Also, the problem exists in both 2.2.0 and 2.3.0

**Comment by JosselinTD** [comment]
Same problem here, but only in the Mac version of Firefox (version 36.0.1), not in the Windows version.

**Comment by mbenford** [comment]
Are you guys using a custom CSS?

**Comment by pfarnach** [comment]
It works! I had to add `.host` inline in the source file but it works. I'm working on a larger project so styles may have been stepping on each other. Thanks a lot.

**Comment by tcrammond** [comment]
Would just like to add that I had the same problem in Firefox, fixed by including the default css for `tags-input host` https://github.com/mbenford/ngTagsInput/blob/master/scss/main.scss#L10.

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by pfarnach** [comment]
Yes

**Comment by gruzzilkin** [comment]
If somebody don't want to add `position: relative` to `.host`, I found a dirty workaround.

Just wrap clickable content with `<button>` in [templates/auto-complete.html](https://github.com/mbenford/ngTagsInput/blob/master/templates/auto-complete.html).

Before:

```html
<div class="autocomplete" ng-if="suggestionList.visible">
  <ul class="suggestion-list">
    <li class="suggestion-item"
        ng-repeat="item in suggestionList.items track by track(item)"
        ng-class="{selected: item == suggestionList.selected}"
        ng-click="addSuggestionByIndex($index)"
        ng-mouseenter="suggestionList.select($index)">
      <ti-autocomplete-match data="::item"></ti-autocomplete-match>
    </li>
  </ul>
</div>
```
After:

```html
<div class="autocomplete" ng-if="suggestionList.visible">
  <ul class="suggestion-list">
    <li class="suggestion-item"
        ng-repeat="item in suggestionList.items track by track(item)"
        ng-class="{selected: item == suggestionList.selected}"
        ng-mouseenter="suggestionList.select($index)">
      <button ng-click="addSuggestionByIndex($index)">
        <ti-autocomplete-match data="::item"></ti-autocomplete-match>
      </button>
    </li>
  </ul>
</div>
```
And add some styles for this "button":

```css
.autocomplete button {
  display: block;
  margin: 0;
  padding: 0;
  border: 0;
  background: none;
}
```

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
