### ISSUE TITLE
Feature Request: adding 'on-tag-click'

### ISSUE THREAD

**Issue by jusopi** [mbenford/ngTagsInput#436]
I was not able to find on either Stackoverflow via the `ng-tags-input` tag nor here on any feature request the ability to add a on-tag-click to the directive.   I think this is a useful API.  I am currently looking at this by:

- creating a new tag template
- a new directive that will handle the click event and then pass which tag was clicked to an expression

Are there any other ideas for this?

**Comment by calebthebrewer** [comment]
There is currently an open [pull request](https://github.com/mbenford/ngTagsInput/pull/239)for this functionality. [@lunks](https://github.com/lunks/ngTagsInput) rebased the changes against this repo a couple weeks ago if you need the functionality now.

**Comment by jusopi** [comment]
Thanks for the feedback.  Since I posted this, I have created a solution as mentioned above http://stackoverflow.com/questions/29851027/ng-tags-input-on-tag-click-handler-is-there-a-better-way/29851028#29851028  

Since this is a **duplicate of #183** I will close this one.
