### ISSUE TITLE
consuming objects AND strings as ngModel source

### ISSUE THREAD

**Issue by jusopi** [mbenford/ngTagsInput#437]
Much like the OP of issue #362, there are some cases where the developer is providing and expecting an array of just strings.  Currently the only solution is to map the array based on the target properties like so: 

```
var vals = $scope.tags.map( function(tag){ return tag.text } )
```

Could a modification be made to the `options.displayProperty` such that if a person sets `"toString"` or `"toString()"` as the value, that could then be called during the process of rewriting the `ngModel`.  I am still digging into the code so I don't know exactly where the swapping of simple strings for object in the `ngModel` are taking place.

**Comment by jusopi** [comment]
I also notice if `ngModel

**Comment by mbenford** [comment]
Basically all places that use `.displayProperty` should be changed. I took a quick look at the code and *maybe*  it won't be so hard to do it. But whatever be the solution, I'd prefer if it wouldn't rely on several `if`s scattered across the code. Let's try to be smart about it. ;)

Your suggestion on how to enable this new behavior is valid, but I think a new option would be more appropriate. Something like `use-objects="true|false"` or `tags-as-objects="true|false"`.

**Comment by jusopi** [comment]
Totally agree on it needing a new option.  However I am thinking more of a *tag-factory*, whereby your default factory function is something like so: 

   function( obj ) { 
      //string or object logic here
      //assuming it's a string
      return { text: obj }
   }

And then a user could supply their own factory function, so in the case of a simple string return:

   function (obj) { return obj.toString() }

What do you think?  Would that be redundant or make the `.displayProperty` redundant?  Using a factory function is how a lot of the Flex list-based UI components work.  I think you're doing that somewhere already, just haven't poked enough in the code to see.  I will try a few solutions over the weekend and submit a pull request.

**Comment by Cyruxx** [comment]
+1

**Comment by jusopi** [comment]
@mbenford did this get addressed with the update recently?  Specifically from this change - https://github.com/mbenford/ngTagsInput/commit/b5dc57f542c11351ad881e45cc238f75b9adc24a ?

**Comment by estaub** [comment]
+1 (or more!) - especially the "use-objects" option

**Comment by BrianHutchison** [comment]
+1 This would simplify my code. I like the use-objects or tags-as-objects option as described above.

**Comment by jukkasi** [comment]
+1 what I said in https://github.com/mbenford/ngTagsInput/issues/504

**Comment by mazavr** [comment]
+1 (I need to work with a strings array)

**Comment by mbenford** [comment]
The latest version of ngTagsInput (v3.2.0) provides basic support for array of strings. More information can be found [here](http://mbenford.github.io/ngTagsInput/blog/2017/04/15/basic-support-for-arrays-of-strings).
