### ISSUE TITLE
Timeline for Next Release

### ISSUE THREAD

**Issue by pbtura** [mbenford/ngTagsInput#442]
This project looks great and I would love to use it in an application I am working on. Unfortunately I am using Angular 1.3 and the current release only supports older versions of angular. Do you have a ball park idea when there will be a release that supports angular 1.3+ (days, weeks, months) ?

**Comment by vp-hwood** [comment]
It's not officially supported but it's been working OK for us with Angular 1.3.15.

**Comment by mbenford** [comment]
Sorry for not replying sooner.

v3.0 was released earlier today and Angular 1.3+ is now officially supported.

**Comment by pbtura** [comment]
Great! thanks for the update.
