### ISSUE TITLE
Filter options instead Highlight

### ISSUE THREAD

**Issue by concepta-thiago** [mbenford/ngTagsInput#450]
Hello there, 
is the a way the results in the auto sugest be filtered instead only highlight?, 
i have a field up to 100k records, and will be hard to find the one that is higlight.

tks

**Comment by benhoad** [comment]
Yeah I'm looking at this too... the demo on the lander page (http://mbenford.github.io/ngTagsInput/) works ideally but the demos page opts to highlight in lieu of  strict filtering.

**Comment by concepta-thiago** [comment]
i made a quick change in the makeObjectArray  function, to get what it wanted, its not the best way, but thats what i have now. 

self.makeObjectArray = function (array, key, query) {
        array = array || [];
        if (array.length > 0 && !angular.isObject(array[0])) {
            array.forEach(function(item, index) {
                array[index] = {};
                array[index][key] = item;
            });
        }

        /*
         * >> Need review <<
         * Quick update, 
         * in order to only display options 
         */
        if (query) {
            var resultFiltered = _.filter(array, function (rec) {
                return rec.text.toLowerCase().indexOf(query) > -1
            })

            if (resultFiltered && resultFiltered.length > 0) {
                array = resultFiltered;
            }
        }
        return array;
    };

**Comment by mbenford** [comment]
Sorry for not replying sooner.

It's up to your application to determine what should be displayed. The autocomplete directive simply passes whatever the user has typed to your code and displays whatever is returned.

**Comment by nikshulipa** [comment]
check "Tags input and autocomplete with custom templates" in Demos page 
http://mbenford.github.io/ngTagsInput/demos
You should probably use function instead of array in <autocomplete> directive. And I agree that is not clear from documentation.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
