### ISSUE TITLE
No name attribute in the related text input field

### ISSUE THREAD

**Issue by soldiertt** [mbenford/ngTagsInput#461]
The input field behind the directive has no name attribute. So , it cannot be accessed via the form object.
That makes error validation very hard, cannot check for 'form.field.$error' for example.

**Comment by mbenford** [comment]
Sorry for not replying sooner.

The inner input field has no validation applied to it, so even if it had a name, there would be nothing for you to check.

But you can validate the `tags-input` element itself. Take a look at [this example](http://plnkr.co/edit/XlMpTl).

**Comment by mbenford** [comment]
Can this issue be closed?

**Comment by soldiertt** [comment]
yes thank you
