### ISSUE TITLE
Enable child attributes in display property tag

### ISSUE THREAD

**Issue by Jakobovski** [mbenford/ngTagsInput#462]
I am wondering if there is a way to do the following.

Given a model:
`{id: 1, person: {fullName: 'Fred Jackson'}}

Can I set the display property to fullName. Something like this
`display-property="person.fullName"`

**Comment by mbenford** [comment]
Sorry for not replying sooner.

You can't do that by using `displayProperty`, but you can use a custom template. Take a look at [this issue](https://github.com/mbenford/ngTagsInput/issues/429).

**Comment by mbenford** [comment]
Can this issue be closed?
