### ISSUE TITLE
Observing min-tags causes "TypeError: Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by dloehr** [mbenford/ngTagsInput#464]
When I turn on active interpolation for the `min-tags` attribute, ng-tags-input throws `TypeError: Cannot read property 'length' of undefined`.

It looks like it's assuming that the ngModel value is an array and trying to validate it before a value has been set.

See this plunker: http://plnkr.co/edit/2jbiOqIhVnnU8QrxV9o9?p=preview

```
TypeError: Cannot read property 'length' of undefined
    at d.directive.link.j (http://mbenford.github.io/ngTagsInput/js/ng-tags-input.min.js:1:3249)
    at http://mbenford.github.io/ngTagsInput/js/ng-tags-input.min.js:1:4691
    at d.factory.b.handleUndefinedResult (http://mbenford.github.io/ngTagsInput/js/ng-tags-input.min.js:1:12956)
    at http://mbenford.github.io/ngTagsInput/js/ng-tags-input.min.js:1:13333
    at Array.every (native)
    at Object.d.factory.b.simplePubSub.trigger (http://mbenford.github.io/ngTagsInput/js/ng-tags-input.min.js:1:13279)
    at http://mbenford.github.io/ngTagsInput/js/ng-tags-input.min.js:1:11731
    at https://code.angularjs.org/1.2.28/angular.js:5981:13
    at Scope.$get.Scope.$eval (https://code.angularjs.org/1.2.28/angular.js:12811:28)
    at Scope.$get.Scope.$digest (https://code.angularjs.org/1.2.28/angular.js:12623:31)
```

Possibly related to #408

**Comment by mbenford** [comment]
Sorry for not replying sooner.

I updated your plunker to use v3.0 (released yesterday) and I didn't see any errors. I wonder if you could test it again? The updated plunker is [here](http://plnkr.co/edit/eh4Ojqatggr8xc40kmfo?p=preview).

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
