### ISSUE TITLE
Can I able to add a tag using a add button? instead of hitting enter, space, comma or pasting

### ISSUE THREAD

**Issue by kanagukrs** [mbenford/ngTagsInput#469]

**Comment by kanagukrs** [comment]
I have achieved this in the following way, Initially I tried to trigger the tag input enter key event but it doesn't work for me, so I tried by getting the scope of the input variable like
'''javascript
    var scope = angular.element('tag input selector').scope();
    scope.eventHandlers.input.keydown(enterKeyEventObject);
'''

Here the enterKeyEventObject is created by using KeyboardEvent of javascript. I knew this is a hacky way to achieve this. If you expose the eventHandlers of ngTagsInput to controller in some way it would be better I can able to trigger tag adding in external button click instead of hitting enter, space, comma

**Comment by mbenford** [comment]
Sorry for not replying sooner.

There's currently no way to programmatically add a tag through the directive itself. I guess the best you can do now is either hack the directive (as you did already) or fork this repo and change the code so it fits your needs.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by ib1987** [comment]
My solution based on @kanagukrs comment:
```javascript
  var scope = angular.element('.input').scope();                    
  scope.tagList.addText(city.value);
  vm.search.address.push(city.value);
```

inside my buttons ng-click function and don't forget to push the new item into the `tags-input`s ng-model.

**Comment by devakone** [comment]
This won't work if you have 
```
$compileProvider.debugInfoEnabled(false);
```
Which you should definitely have for your production build.
