### ISSUE TITLE
Autocomplete with duplicated tag

### ISSUE THREAD

**Issue by m3ftah** [mbenford/ngTagsInput#471]
When I use autocomplete with two tags, that have the same text, there is this error : https://docs.angularjs.org/error/ngRepeat/dupes
I think you should add : "track by $index" in ng-repeat.
For my example I tried to make the array elements unique.

**Comment by lordfriend** [comment]
I have encountered the same problem, After I walk through the source code. I found using key-property in `tagsInput` directive can solve this. because the default auto-complete template using a custom track function
`ng-repeat="item in ::suggestionList.items track by track(item)"`

in src/auto-complete.js, there are
```javascript
scope.track = function(item) {
       return item[options.tagsInput.keyProperty || options.tagsInput.displayProperty];
};
```
So you can use any property which is unique among your elements.

**Comment by m3ftah** [comment]
thanks :+1:

**Comment by mbenford** [comment]
Sorry for not replying sooner.

@lordfriend is correct. If you have duplicate tags in your model, you need to set the `keyProperty` option as an existing property that uniquely identifies each element.

Can this issue be closed?

**Comment by m3ftah** [comment]
Yes.

**Comment by ws-fegon** [comment]
it doesn't work with keyProperty :(
my model is:
             [{
                "field":"Software",
                "skills":"Software",
                "Multi_lang":"Software"
              },
              {
                "field":"Software",
                "skills":"DBA",
                "Multi_lang":"DBA"
              },
              {
                "field":"Software",
                "skills":"QA",
                "Multi_lang":"DBA"
              },
              {
                "field":"Software",
                "skills":"Real Time",
                "Multi_lang":"Real Time"
              }]
"skills" is unique field in my model

I use min length for tags and for autocomplete equals 1 symbol

<auto-complete source="vm.searchQuery($query)" 
                         min-length="1"
                         display-property="skills"
                         key-property="skills">
          </auto-complete>

so when i type the unique letter (for example. Q, "q" presented once at tags) i see the correct autocomplete list but if this letter is not unique (for example "o") so i have duplicate error 
Error: [ngRepeat:dupes] http://errors.angularjs.org/1.4.1/ngRepeat/dupes?p0=item%20in%20suggestionL…22Software%22%2C%22skills%22%3A%22DBA%22%2C%22Multi_lang%22%3A%22DBA%22%7D


so when i changed 
ng-repeat="item in suggestionList.items track by track(item)"
to
ng-repeat="item in suggestionList.items track by $index"

it works correct for me

**Comment by rootux** [comment]
What if I don't have a unique property in my elements.
how can I use key-property="$index"

**Comment by rootux** [comment]
OK - the way to do it is by listening to the addNewTag and then override that element which is not unique and make it unique. so for example. if the key-property is index we can 
```
   $scope.addNewTag = function($tag) {
        $tag.id = Math.floor((Math.random() * 10000000000));
    };
```

**Comment by pujabhatt1** [comment]
can yo please show with example.I am having hard time to fix it.

**Comment by weihanchen** [comment]
I use index as id make it unique and works for me below
```html
<tags-input ng-model="tags" key-property="id" display-property="text" on-tag-added="tagAdded($tag)"></tags-input>
```
```javascript
$scope.tags=[];
$scope.tagAdded = function($tag) {
     var currentId = 0;
     if ($scope.tags.length > 1) {
              var previousTagIdx = $scope.tags.indexOf($tag) - 1;
              var previousTag  = $scope.tags[previousTagIdx];
              currentId = previousTag.id + 1;
      }
      $tag.id = currentId;
}

[example](https://plnkr.co/edit/o0JZnP?p=info)
