### ISSUE TITLE
How to trigger minTags error when form.$submitted = true

### ISSUE THREAD

**Issue by abbish** [mbenford/ngTagsInput#478]
Currently i found that the minTags is triggered before submit the form

How to do let the validator be triggered after form submitted ?

Thanks

**Comment by mbenford** [comment]
Sorry for not replying sooner.

That's the way Angular handles validation. If you want to delay the validation until after the form has been submitted, you will need to do something like [this](http://stackoverflow.com/questions/17452247/validate-form-field-only-on-submit-or-user-input). Or [this](http://www.matheuslima.com/angularjs-form-validation-after-submit-directive/).

**Comment by abbish** [comment]
Thanks a lot
