### ISSUE TITLE
placeholder attribute is not re-evaluated

### ISSUE THREAD

**Issue by pwambach** [mbenford/ngTagsInput#479]
Hey,

i'm using a translation filter for the placeholder attribute like `placeholder="{{ 'add_new_tag' | i18n }}"`. The problem is that when i switch the language the placeholder is not translated because the placeholder attribute is not reevaluated. Guess an additional observer for the placeholder attribute would do the trick here. I would need to have a deeper look. Or is there already a possibility to trigger an update of the options (or single properties) manually? Couldn't find any.

I think the issue is related to @itanex comment in #433 although i don't want the new value to be empty just updated.

Thanks for the great work!

**Comment by kotmatpockuh** [comment]
same trouble

**Comment by kotmatpockuh** [comment]
seems that i founded solution:

```
app.config(function(tagsInputConfigProvider) {
  tagsInputConfigProvider.setDefaults('tagsInput', { placeholder: '' });
  tagsInputConfigProvider.setActiveInterpolation('tagsInput', { placeholder: true });
});
```

and in view, just:

```
placeholder="{{ 'ADD_TAG' | translate }}"
```

**Comment by pwambach** [comment]
awesome, that's exaclty what i was looking for, thx!
