### ISSUE TITLE
Custom template with textarea rather than input tag

### ISSUE THREAD

**Issue by adambarthelson** [mbenford/ngTagsInput#482]
I currently have a situation where I'd prefer the ability to use a textarea rather than an input tag.  A client requires a really long placeholder text, and input placeholder text does not wrap.

For example, I currently have:
![](http://i.imgur.com/c5MyxUU.png) 

But would prefer something like: 
![](http://i.imgur.com/FrNQXaC.png)

I have not figured out a way to do this with CSS/JS, but I'm pretty sure you can't line break input placeholders.  If there's another way to accomplish this without using a textarea, I'd accept that solution as well.

**Comment by mbenford** [comment]
Sorry for not replying sooner.

Yes, AFAIK it's not possible to make the input's placeholder word-wrap. I guess the best you can do is fork the main repo and replace the `input` with a `textarea` and do something like [this](http://stackoverflow.com/a/25261886/1349152).

**Comment by adambarthelson** [comment]
I ended up going a better route and just setting it as the description attribute to show on hover rather than an obnoxiously long placeholder.  I'll go ahead and close.
