### ISSUE TITLE
Is it possible to invoke a scope method in the template?

### ISSUE THREAD

**Issue by beradrian** [mbenford/ngTagsInput#486]
Something like

    <script id="tagTemplate" type="text/ng-template">
        <div>
	    <span>{{$getDisplayText()}}</span>
	    <button ng-click="showDetails(data)">More</button>
        </div>
    </script>

**Comment by mbenford** [comment]
Sorry for not replying sooner.

That's not currently possible, but I've been thinking of implementing that feature in a future release.

**Comment by theBull** [comment]
+1

**Comment by beradrian** [comment]
So now you can use it as in my example or should I add $scope, like `$scope.showDetails(data)`?

**Comment by mbenford** [comment]
@beradrian You should add the `$scope`prefix. I resisted naming it as "scope" because nowadays people rarely need to deal with scopes, but I couldn't come up with a better name. I welcome suggestions :)

**Comment by theBull** [comment]
To be clear

```
<script id="tagTemplate" type="text/ng-template">
    <div>
    <span>{{$getDisplayText()}}</span>
    <button ng-click="$scope.showDetails(data)">More</button>
    </div>
</script>
```

?

**Comment by vdsabev** [comment]
@mbenford are you planning a new release including this fix soon, or should we directly use the commit hash for now?

**Comment by mbenford** [comment]
@theBull Yes, your markup is correct. Take a look at [this working plunker](http://plnkr.co/edit/rmkJ1nBUWe2bk9prGlEs?p=preview).

@vdsabev v3.1.1 has been released earlier today on all distribution channels. v3.1 had been released before, but don't use it because it's buggy.

**Comment by vdsabev** [comment]
Thanks, @mbenford, it works beautifully!

Something to note in our use case - we needed the event in the template of the `<auto-complete></auto-complete>` directive, but the `template-scope` attribute is set in the `<tags-input></tags-input>` directive.

Also, the autocomplete template click event bubbles up and the item gets added to the tags input list, unless the `$event` object is used to stop the propagation.

Example:
```html
<tags-input template-scope="this">
  <auto-complete template="autocomplete-item-template"></auto-complete>
</tags-input>

<script type="text/ng-template" id="autocomplete-item-template">
  <div>
    <span ng-bind-html="$highlight($getDisplayText())"></span>
    <span ng-click="$scope.deleteAutocompleteItem(item, $event)">
      <i class="fa fa-fw fa-trash"></i>
    </span>
  </div>
</script>
```

```js
$scope.deleteAutocompleteItem = function (item, $event) {
  $event.stopPropagation(); // Prevent item from being added to the list
  ...
};
```

**Comment by Arunadevi** [comment]
Would be nice to reference this here: http://mbenford.github.io/ngTagsInput/documentation/api#tagsInput or http://mbenford.github.io/ngTagsInput/documentation/guides/custom-templates
