### ISSUE TITLE
ng-model not updated with tags-input in ng-repeat

### ISSUE THREAD

**Issue by pierredavidbelanger** [mbenford/ngTagsInput#490]
Have a look at this jsfiddle:
https://jsfiddle.net/wmsoor18/

Try to add tags, nothing happen.
Uncomment line 4 in the javascript (where the model is initialized).
Try yo add tags, it works.

Is this an expected behaviour ?
I am sorry if its just me not understanding angular, I am new to this.

**Comment by asborisov** [comment]
It's ok. Tags-input try to use variable, that isn't exists. When you uncomment line with initializing you create this variable in the controller's scope.

**Comment by pierredavidbelanger** [comment]
But [this one](http://jsfiddle.net/r78ohcf0/1/) is working without initialization.
I guess this is an issue with me not understanding ngModel and not with ngTagsInput itself :)

**Comment by nehadpfriends** [comment]
This one is working fine. [https://jsfiddle.net/wmsoor18/](url)

**Comment by nehadpfriends** [comment]
This is working fine with tags [JsFiddle](https://jsfiddle.net/wmsoor18/8/)
