### ISSUE TITLE
Possible XSS vulnerability

### ISSUE THREAD

**Issue by jws305** [mbenford/ngTagsInput#491]
I am using this plugin to allow for user submitted tags. Everything works fine when I am using custom templates, however, when I use the `display-property` of the `auto-complete` directive, I can execute scripts by adding tags.

I solved this issue in my code by encoding the HTML before trusting it.  Is this expected behavior?

I replaced
```return $sce.trustAsHtml(text);```
with
```return $sce.trustAsHtml(tiUtil.encodeHTML(text));```

https://github.com/mbenford/ngTagsInput/blob/master/src/auto-complete-match.js#L28

**Comment by jws305** [comment]
With the fix above screwed up the text highlighting. I instead had to replace

```js
scope.$highlight = function(text) {
    if (options.highlightMatchedText) {
        text = tiUtil.safeHighlight(text, autoComplete.getQuery());
    }
    return $sce.trustAsHtml(text);
};
```

with

```js
scope.$highlight = function(text) {
    if (options.highlightMatchedText) {
        text = tiUtil.safeHighlight(tiUtil.encodeHTML(text), autoComplete.getQuery());
    }
    return $sce.trustAsHtml(text);
};
```

**Comment by mbenford** [comment]
Sorry for not replying sooner.

That's odd. The `safeHighlight` function already escapes the provided arguments before anything else, as you can see [here](https://github.com/mbenford/ngTagsInput/blob/master/src/util.js#L66).

I wonder if you could create a plunker script showing the problem that you have experienced? You can use [this template](http://plnkr.co/edit/tpl:93P2qxOjYmlcYSqDmo39).

**Comment by punzki** [comment]
Here's a demonstration of a vulnerability in safeHighlight. I don't know if it's the same as @jws305 was referring to but it's the one I could find. Demo: http://plnkr.co/edit/KpAuRNNUORBaR4qFxhDC?p=preview

Vulnerable if all conditions are met:
- min-length=0
- load-on-empty=true
- either load-on-focus or load-on-down-arrow =true

Please be advised I'm submitting PR 665 as an employee of Google, hence I added Google Inc. to the copyright authors.
