### ISSUE TITLE
array1.filter is not a function

### ISSUE THREAD

**Issue by davidedellai** [mbenford/ngTagsInput#492]
Hi,
i'm using the auto-complete in tags-input but when i start writing i get this error: array1.filter is not a function. This is my angular call

``` javascript
 $scope.loadTags = function(query) {
            var searchPeople = $scope.baseUrl + "&searchString=";
            return $http.get(searchPeople + query, {

            }).success(function (data) {
                $scope.people = data.data.data;
                console.log($scope.people);
            }).error(function (data){
                console.log("Error");
            });
        };
```

moreover i don't know how to retrieve a value from, in my case $scope.people json that is something like:

``` json
         {
                "id": 17,
                "cod": "gg117",
                "name": "Alex"
            }
```

i know that i need a custom template but as long as i get the error i can't do it. By the way the template is this one but i don't know if it's correct

``` html
    <script type="text/ng-template" id="my-custom-template">
       <div class="left-panel">
            <img ng-src="./img/avatar.jpeg" />
       </div>
       <div class="right-panel">
            <span ng-bind-html="$highlight($getDisplayText())"></span>
            <span>({{people.name}})</span>
      </div>
    </script>
```

**Comment by khorolets** [comment]
@davidedellai have u succeed? I might try to help, but I need to look at you *tags-input* call.

**Comment by marcusg** [comment]
same problem here... @davidedellai do you have a workaround?

**Comment by jusopi** [comment]
@davidedellai it doesn't look like your `.success` callback is returning anything, you're setting the `$scope.people = data.data.data` but you never actually return `data.data.data` in the promise chain. I assume you're using the `<auto-complete source="loadTags($query)"></auto-complete>`.

**Comment by mbenford** [comment]
Sorry for not replying sooner.

@jusopi is right. If you don't return anything within .then()`, your promise will be resolved with the undefined value, and that will break the autocomplete directive later on. 

But I think the directive should at least check for null/undefined and throw a better error message. I'll add it to the backlog.

**Comment by kinopio29** [comment]
I have the same problem... but the think is that .then() is returning data.
Works if i remove the line from the example, of course country is not my variable...
```
return countries.filter(function(country) {
        return country.name.toLowerCase().indexOf($query.toLowerCase()) != -1;      
});
```
but shows always the complete list of data and can't filter no matter what..

**Comment by paolomaffei** [comment]
I had the same problem when I returned "defer" instead of "defer.promise"

**Comment by tarunwittyfeed** [comment]
return countries.filter(function(country) {
                return country.name.toLowerCase().indexOf($query) != -1;
            });
this is working fine....
otherwise you can use filter

**Comment by nitin-healthians** [comment]
getDifference = function(array1, array2) {
            **if(array1 !== null) {**
                return array1.filter(function(item) {
                    return !tiUtil.findInObjectArray(array2, item, getTagId(), function(a, b) {
                        if (options.tagsInput.replaceSpacesWithDashes) {
                            a = tiUtil.replaceSpacesWithDashes(a);
                            b = tiUtil.replaceSpacesWithDashes(b);
                        }
                        return tiUtil.defaultComparer(a, b);
                    });
                });
            }
            else {
                **return [];**
            }
            
        };

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
