### ISSUE TITLE
Timeline for minor release

### ISSUE THREAD

**Issue by ESimmonds** [mbenford/ngTagsInput#493]
Upcoming on 4 months and over 23 commits of great features in the master branch. Any idea when a push to bower is coming? Can't wait to show off the progress.

**Comment by mbenford** [comment]
Sorry for not replying sooner.

v3.0 was released yesterday, so you can show it off all you want. :)

**Comment by ESimmonds** [comment]
Awesome, Thanks. Great work on this repo btw.
