### ISSUE TITLE
The input focus is not working

### ISSUE THREAD

**Issue by talamaska** [mbenford/ngTagsInput#496]
This is really weird issue. I saw it working on the demo page, but when implemented in my page it is not working.
When I click outside the input , but inside the host, the element is not getting a focus. tried to debug with breakpoints and this is exactly what i see , the code just stops after the input[0].focus(); in host.click eventHandler. I have tried the source files of the example itself, but again i got only the highlight but no focus on the input field. Please help.

P.S. After further investigation I can suggest that this issue is happening in ionic, not in plain angular app.

P.S. What i see actually in ionic is that the blur is fired immediately after the focus, but I didn't lost focus on the window like the code is suggesting, realying on activeElement is working here it seems. I would suggest using page visibility api instead of this workaround

P.S. More findings - the input triggers ng-blur, without any reason. I still can't find a solution to my problem

**Comment by igorprado** [comment]
I'm trying to use this with Ionic too and I'm getting weird behaviors too. This that you mentioned and another one is: if I select a option from autocomplete by clicking on it, the input looses the focus. If I hit enter, or tab, with an option selected, everything works fine: the tag is added and the input is focused and the autocomplete is shown (I set it to show on empty).

If I select a option by clicking on it, the tag is added, the autocomplete list is shown but I can only dismiss it by clicking on the input (not the host as mentioned in this bug), and then clicking outside it.

**Comment by talamaska** [comment]
i have added additional timeout, fixes my problem for now, but it's ugly.

**Comment by igorprado** [comment]
@talamaska can you share it?

**Comment by levity** [comment]
This is probably the same issue as #512

**Comment by mbenford** [comment]
Sorry for not replying sooner.

I have never tested ngTagsInput with Ionic, so I'm honestly unaware of any issues. I'll try to find time to do some tests. 

If you guys have any additional information on this issue, please let me know.

**Comment by jmterminator** [comment]
In ionic use data-tap-disabled="true" on tags-input element, like so:

<tags-input data-tap-disabled="true"></tags-input>

**Comment by mjrobichaud** [comment]
@jmterminator this nearly drove me nuts. your solution works perfectly!

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
