### ISSUE TITLE
Hide suggestion list after tag removed problem

### ISSUE THREAD

**Issue by jukkasi** [mbenford/ngTagsInput#501]
In 3.0.0 https://github.com/mbenford/ngTagsInput/commit/731ef9eb0874ae083cba47c942034cb9109e6cf9 is causing a problem when tag is removed and suggestion list is hidden, after this the focus still remains in input but when the input is clicked the list does not appear but you have to click outside the input and then input again to make list visible.

I'm using load-on-focus="true", load-on-empty="true" in this particular scenario

**Comment by mbenford** [comment]
Sorry for not replying sooner.

Thanks for reporting it. Could you provide a plunker reproducing the issue? You can use [this template](http://plnkr.co/edit/tpl:93P2qxOjYmlcYSqDmo39).

**Comment by jukkasi** [comment]
Try http://plnkr.co/edit/xs0Y8XMn17wf9RrN3fDI

1) Click tags input (suggestions appear)
2) Remove item using backspace or mouse (suggestions disappear)
3) Click tags input -> I think suggestions should appear but only appears after clicking outside input and then clicking input

**Comment by NodeJoSe** [comment]
Did you find any solution for this?
 Im having the same problem and cant figure out how to solve this

**Comment by jukkasi** [comment]
Nope, did not find any solution. Maybe @mbenford missed my plnkr

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by gauravdixit007** [comment]
@mbenford @NodeJoSe I used a workaround for this problem. If that helps below are the details:

Defined a deFocus function:
$scope.deFocus = function(){
        $timeout(function(){
            document.activeElement.blur();
        }, 100);
    };

Binded on-tag-removed and on-tag-clicked properties with deFocus function as below:
<tags-input
    display-property="name"
    key-property="id"
    on-tag-removed="deFocus();"
    on-tag-clicked="deFocus();"
    .
    .
    .
</tags-input>

I hope this help somebody like me :)
