### ISSUE TITLE
Un-minified release version can't be minified

### ISSUE THREAD

**Issue by lookfirst** [mbenford/ngTagsInput#519]
It needs to be preprocessed to support the angular minified injection syntax.

**Comment by mbenford** [comment]
Sorry for not replying sooner.

The released, unminified version of ngTagsInput is completely annotated with Angular's [inline array annotations](https://docs.angularjs.org/guide/di#inline-array-annotation), as you can see [here](https://cdnjs.cloudflare.com/ajax/libs/ng-tags-input/3.0.0/ng-tags-input.js). You shouldn't face any problems minifying it
