### ISSUE TITLE
tag element with long label - usage of ellipsis when tag label / autocomplete item text is too long

### ISSUE THREAD

**Issue by angel1st** [mbenford/ngTagsInput#526]
Hi there,
Since my intentions are to use this excellent control in responsive design, I would appreciate support of auto truncate option, when control width reaches certain threshold.
Currently, if I have item with relatively long label and control's width drops below label width, the result is not pleasant.
You can see small screenshot here:
![tagsinput](https://cloud.githubusercontent.com/assets/8547131/9494524/02ecf3d0-4c0f-11e5-88ed-f2fb3df0c492.png)

The fifth tag is called "Bosnia and Herzegovina and Montenegro" (yes, I know there is no such country :)) and as you can see - the label and removing button are placed below the tag area.

I think instead of current result, the best is to have ellipsis added at the end and part of the label being truncated. This should be done both for tags & autocomplete list items.

Here is the complete Plunker example:
http://plnkr.co/edit/6Pzl3iY5jZCnHRsInois?p=preview

Do you think there are relatively easy way to fix that (probably via tag & autocomplete templates)?

Best Regards

**Comment by dcortes92** [comment]
Hey @angel1st did you come up with a workaround for this? I was thinking to fork the repo and fix this myself. For now I'm overwriting the template, but it's quite complicated.

**Comment by angel1st** [comment]
Hi @dcortes92 - no, I didn't find workaround. In fact I was expecting some feedback from the ngTagsInput's creator, but apparently, it didn't happened yet.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
