### ISSUE TITLE
Input text becomes hidden

### ISSUE THREAD

**Issue by carlitux** [mbenford/ngTagsInput#531]
Hi,

When I added a lot of tags and I continue adding input text becomes hidden at far right. 

Here is a demo http://plnkr.co/edit/96PsKv?p=preview

**Comment by mbenford** [comment]
Sorry for not replying sooner.

In your example you have replaced the whole ngTagsInput's stylesheet with a custom one that changes the default behavior, which is to wrap the tags that don't fit in the available space.

I assume that you have created your own stylesheet to support some specific use case, and thus you'll need to figure out how to write the appropriate CSS for that specific scenario.

**Comment by carlitux** [comment]
@mbenford Hi I tried to change but didn't works... my solution was this

```js
tagHost[0].focus(); // this to force input loose the focus
tagHost.triggerHandler('click');  // this to refocus the input, autocomplete
```

Doing *focus()* on input text wasn't worked all the time really worked a few times.

I know is not the best solution but if anyone has the same issue maybe will help.
