### ISSUE TITLE
autocomplete converting space to dash

### ISSUE THREAD

**Issue by sprakashg** [mbenford/ngTagsInput#532]
Hi team, 
autocomplete converting space to dash on tag added

**Comment by sprakashg** [comment]
I fixed the issue, you may close it

**Comment by sapna1402** [comment]
You can set replace-spaces-with-dashes attribute to false like : "replace-spaces-with-dashes='false'"

**Comment by sprakashg** [comment]
Thanks Sapna, I had figured it :)
