### ISSUE TITLE
Data not in request body using formData

### ISSUE THREAD

**Issue by handonam** [mbenford/ngTagsInput#535]
I'm currently trying to process my tag data into formData.  But, I am not getting anything into the request body.  Any ideas what may be happening?

Given this (slight pseudo):

``` html
<form name="addItem" class=".js-AddItem">
  <input type="text" name="username"> <!-- example input with "TestName" -->
  <tags-input name="tags"> <!-- example input with "test" -->
  </tags>
</form>
```

I tried to echo out {{ addItem.tags }} to see what I had. and I did have this (notice $viewValue and $modelValue).

``` json
{
  "$viewValue":[{"name":"test"}],
  "$modelValue":[{"name":"test"}], 
  "$validators":{},
  "$asyncValidators":{},
  "$parsers":[],
  "$formatters":[],
  "$viewChangeListeners":[],
  "$untouched":false,
  "$touched":true,
  "$pristine":false,
  "$dirty":true,
  "$valid":true,
  "$invalid":false,
  "$error":{},
  "$name":"tags",
  "$options":null
}
```

And so, I get it loaded for posting:

``` javascript
var formData = new FormData(document.querySelector('.js-AddItem'));
$http.post("http://myapiroute", formData, {
  transformRequest: angular.identity,
  headers: { 'Content-Type': undefined }
}).success(function(){ ... });
```

I check my request body on the server end, and i'm not seeing the tags. In the same example above with "username", my $viewValue  and $modelValue show "TestName", and showed up in the request body properly.

Any ideas on how I can get the tags into the request body using formData?

**Comment by handonam** [comment]
My hunch at the moment is that the model has objects, so it needs to be encoded as a string from JSON to work.

I am only able to do this for now

```javascript
var formData = new FormData(document.querySelector('.js-AddItem'));
formData.append('tags', JSON.stringify($scope.addItem.tags.$modelValue));
//...
```

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
