### ISSUE TITLE
Controller 'tagsInput', required by directive 'tiTagItem', can't be found!

### ISSUE THREAD

**Issue by t3ddy** [mbenford/ngTagsInput#540]
I get this error after opening (and closing) some modals containing tags-input.
It's visible in Chrome console, but the UI seems fine.

**Comment by mbenford** [comment]
Please provide some plunker showing the problem you're experiencing. You can use [this template](plnkr.co/edit/tpl:93P2qxOjYmlcYSqDmo39).

**Comment by marekbigaj** [comment]
Hi,
I have exactly the same error.

**Comment by maxaus** [comment]
The same error, when using tags-input on modal window ($modal from http://mgcrea.github.io/angular-strap/ ), no issue, when using same syntax on main page (not modal)

**Comment by pribilinskiy** [comment]
I have to confirm, same happens in a dynamically compiled template. Somehow `tiTagItem` loses `tagsInput` at recompilation

**Comment by pribilinskiy** [comment]
Fixed by properly `$destroy`-ing scopes

**Comment by tokict** [comment]
I have this issue in 3.1.1 just by including the module in app and adding auto-complete directive within tags-input

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by melneff** [comment]
Was this ever fixed?

**Comment by tuanlc** [comment]
I'm facing the same error with the same context.

**Comment by pribilinskiy** [comment]
@tuanlc it was so long ago I hardly remember what it's all about )

**Comment by andiih** [comment]
I'm having a metoo moment here: Error: $compile:ctreq
Missing Required Controller
Controller 'tagsInput', required by directive 'tiTagItem', can't be found!

if @pribilinskiy can come up with his historical fix that would be great!

**Comment by DevNiravBhatt** [comment]
> @tuanlc it was so long ago I hardly remember what it's all about )



> I have to confirm, same happens in a dynamically compiled template. Somehow `tiTagItem` loses `tagsInput` at recompilation



> Fixed by properly `$destroy`-ing scopes

Can you please explain how? I am getting same error with AngularJS 1.7.
