### ISSUE TITLE
ngModelCtrl.$validate is not a function

### ISSUE THREAD

**Issue by elalchemist** [mbenford/ngTagsInput#543]
Hello,

For some reason, which I cannot seem to figure out, I get the following error when using the ngTagsInput directive:

*TypeError: ngModelCtrl.$validate is not a function
    at Object.fn (ng-tags-input.js:319)
    at Scope.promises.$get.Scope.$digest (angular.js:12650)
    at Scope.promises.$get.Scope.$apply (angular.js:12915)
    at done (angular.js:8450)
    at completeRequest (angular.js:8664)
    at XMLHttpRequest.xhr.onreadystatechange (angular.js:8603)*

My HTML is as follows:

```
<tags-input ng-model="question.tags" display-property="name" add-from-autocomplete-only="true" add-on-space="true">
    <auto-complete source="loadTags($query)"></auto-complete>
</tags-input>
```

And my Controller:

```
angular.module('forum').controller('AskQuestionController', ['$scope', 'Questions', '$location', 'Tags',
	function($scope, Questions, $location, Tags) {
        
        $scope.question = {};
        $scope.question.tags = [];
        
        $scope.loadTags = function(query){
            return Tags.load(query);
        };
        
        $scope.submitQuestion = function(){
            Questions.add($scope.question).then(function(){
                $location.path('/forum');       
            });
        };	
	}
]);

```

Any help would be greatly appreciated!

Thanks!

**Comment by rudolph2907** [comment]
I am having the same issue, please help anyone?

**Comment by jpnauta** [comment]
The README specifies that this project requires AngularJS 1.3+. ngModelCtrl.$validate was introduced in Angular 1.3. I suggest you check your current version of Angular, and upgrade accordingly. :smile:

**Comment by elalchemist** [comment]
Thank you jpnauta. That solved it.

**Comment by forhot2000** [comment]
is there any alternative method for angular v1.2.x?

**Comment by jennPeavler** [comment]
@forhot2000 Did you find an alternative method or workaround?  I am running v1.2.29.

**Comment by allpassos** [comment]
If you are under angulajs < 1.3 you must go to  ngTagsInput version 2.3.0  ( lattest version supported for angulajs < 1.3 ).  I was at 2.1.1v and some newest API directives didn't run. The version 2.3.0 works great for me.
