### ISSUE TITLE
Can't restrict digits input only

### ISSUE THREAD

**Issue by AlexanderKozhevin** [mbenford/ngTagsInput#551]
tags-input(ng-model="model[options.key].value"  placeholder="add" ng-if="options.templateOptions.multiple" allowed-tags-pattern="^[0-9]$")

**Comment by mbenford** [comment]
The `allowedTagsPattern` option doesn't prevent the user from typing any character. Instead it validates the input before adding a new tag.

Right now the best you can do to accomplish that is write a helper directive that captures the `keydown` event on the inner input element and handles it accordingly.
