### ISSUE TITLE
Limited tag capacity?

### ISSUE THREAD

**Issue by bhilst-searshc** [mbenford/ngTagsInput#552]
Is there a known limit on the number of tags that the control can handle?  They stop appearing in the control after about 80; however, it appears to recognize they are added because they no longer appear in the drop-down list.  I used CSS to limit the height and add a scroll bar, but taking this off doesn't make a difference on the capacity.  Here is the template I'm using.

``` html
<tags-input ng-model="techs" display-property="name" placeholder="Add a technician" template="tech-tag-template"
    replace-spaces-with-dashes="false" on-tag-clicked="tagClicked($tag)" on-tag-removing="canRemoveTag($tag)" on-tag-adding="canRemoveTag($tag)">
  <auto-complete source="loadTechs($query)"
    min-length="1"
    load-on-focus="false"
    load-on-empty="true"
    load-on-down-arrow="true"
    max-results-to-show="32"
    addFromAutocompleteOnly="true"
    template="auto-complete-template"></auto-complete>
</tags-input>
<div class="input-group-btn" style="vertical-align:top; padding-top:5px">
  <button class="btn btn-add-on" type="button" ng-click="clearTechs()" style="position:relative;left:-1px;"><i class="fa fa-times"></i></button>
  <button data-toggle="modal" class="btn btn-add-on dropdown-toggle" type="button" href="{{viewLocked ? '' : '#modal-form'}}" style="position:relative;left:-1px;"><i class="fa fa-search"></i></button>
</div>

<script type="text/ng-template" id="tech-tag-template">
  <div class="tech-tag-template" ng-class="{'selected-tag': data.selected }">
    <div>
      <i class="fa fa-wrench"></i> <span>{{$getDisplayText()}}</span><span class="remove-button" ng-click="$removeTag()"><i class="fa fa-times"></i></span>
    </div>
  </div>
</script>

<script type="text/ng-template" id="auto-complete-template">
  <div class="left-panel">
    <i class="fa fa-wrench"></i>
  </div>
  <div class="right-panel">
    <span ng-bind-html="$highlight($getDisplayText())"></span>
    <!--span>{{data.unit}} / {{data.team}}</span-->
  </div>
</script>
```

**Comment by mbenford** [comment]
I'm not aware of any hard limit. To be honest, I've never tried to add that many tags as you have.

I wonder if you could provide a plunker showing that behavior? You can use [this template](plnkr.co/edit/tpl:93P2qxOjYmlcYSqDmo39).

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
