### ISSUE TITLE
ngTagsInput autocomplete not working

### ISSUE THREAD

**Issue by donnybrasco** [mbenford/ngTagsInput#561]
Hi

I have created and ionic, angularjs mobile app and used the ngTagsInput module. It works fine for just simple tags but does not seem to work when its set to  auto complete. when i set focus on the input the list of suggestions does not show.Please see code below:

html:

 <tags-input ng-model="standardFieldsTemp" display-property="text" add-from-autocomplete-only="false">
                <auto-complete source="loadTags($query)" debounce-delay="0"
                               load-on-focus="true" load-on-empty="true" display-property="text" load-on-down-arrow="true"></auto-complete>
            </tags-input>

controller:

 $scope.standardFieldsTemp = [];   

$scope.loadTags = function (query) {
        var options = [{ text: "tag1" }, { text: "tag2" } ];
        var deferred = $q.defer();
        deferred.resolve(options);
        return deferred.promise;
}

**Comment by StephJan** [comment]
Same problem here with a copy/paste from a working plunker into my Ionic project. More specifically, it fails on : 
TypeError: Cannot read property 'data' of undefined
    at ng-tags-input.js:590
    at processQueue (ionic.bundle.js:23394)
    at ionic.bundle.js:23410
    at Scope.$eval (ionic.bundle.js:24673)
    at Scope.$digest (ionic.bundle.js:24484)
    at Scope.$apply (ionic.bundle.js:24778)
    at ionic.bundle.js:26545
    at completeOutstandingRequest (ionic.bundle.js:14221)
    at ionic.bundle.js:14493

Which corresponds to the handling of the promise used to get tags : 

items = tiUtil.makeObjectArray(items.data || items, getTagId());

**Comment by c0r3yz** [comment]
@StephJan - Did you figure out your issue? I'm having the same exact problem as you.

**Comment by ugunebakan** [comment]
check this issue https://github.com/mbenford/ngTagsInput/issues/89. I have the same problem this solution worked for me.
