### ISSUE TITLE
Internet Explorer issue: Text jitters when input

### ISSUE THREAD

**Issue by akomarclutch** [mbenford/ngTagsInput#568]
Couldn't find an open issue for this, apologies if there is one already made. 

When I use the ngTagsInput field in IE 11, the text jitters/shakes while I'm typing it into the browser window. I have verified this across multiple machines, and on multiple sites - for example I still see it on the various demos found on the home site (http://mbenford.github.io/ngTagsInput/demos).

I only see this issue in IE, all other browsers work great

**Comment by dwharrison** [comment]
I'm seeing the same problem, with jitter in IE11 but not in other browsers.  I had also seen the jitter on the demo site, though the demo site is currently throwing a JS error in IE11.

This is a significant issue for my team, as it's very damaging to the user experience.
