### ISSUE TITLE
Promise support for onBeforeTagAdd

### ISSUE THREAD

**Issue by brazorf** [mbenford/ngTagsInput#569]
I've recently seen that i can't use promises as return type from a `onBeforeTagAdd` handler (result is always assumed to be `true`).
I think this would be a nice addon since i might need to check items match custom constraints before adding them.

What do you think?

**Comment by pdf13** [comment]
+1

**Comment by mdickin** [comment]
It looks like this was added on February 3rd, but has not been included in the builds. The "latest build" link in the readme is a dead link, so I had to clone locally and build with grunt. I smoke tested that build and it seems that it accepts promises now.

**Comment by brazorf** [comment]
@mdickin did you notice if it has been implemented on ìtagRemoved' and 'tagRemoving' also?

**Comment by mdickin** [comment]
`onTagRemoving` supports promises, as it allows you to cancel the action if the promise fails. `onTagAdded` and `onTagRemoved` are raised after the action, so a promise does not provide any value.

**Comment by brazorf** [comment]
Doesn't seem to work, the following code doesn't prevent from tag being removed.

```
<tags-input
...  more options
on-tag-removing="onTagRemove($tag)">
```

```javascript
$scope.onTagRemove = function(item) {
			return fooAsync().then(function(response){
				return false;
			});
		}
```

I'm on 2.3.0. Maybe it was added in v3?

**Comment by mdickin** [comment]
Yeah, like I said, I had to get the latest version of code from github and build it. The last release was v3, but the support was added after that, so you'll have to build it yourself.

Or I could be a nice guy and attach the minified version I'm currently using
[ng-tags-input.min.zip](https://github.com/mbenford/ngTagsInput/files/188359/ng-tags-input.min.zip)

**Comment by brazorf** [comment]
Thanks buddy.
Any chance to see the bower dist updated?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
