### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by armarton** [mbenford/ngTagsInput#570]
Hello,
I need to create a custom people picker for SharePoint 2013. I use your directives as solution. I've been faced with the following error:

The ng-model is the **pdmPeoplePicker**:

``` javascript
fel1DataService.getPeoplePickerInfo($scope.formItem.serverData.Project_x0020_Development_x0020_)
.then(
    function (value) {
        $scope.pdmPeoplePicker = fel1DataService.result;
        console.log($scope.pdmPeoplePicker);
    },
    function (error) {
        console.error(error);
    }
);
```

and the **service method**:

``` javascript
var self = this;
self.result = [];

this.getPeoplePickerInfo = function (people) {
    var dfd = $q.defer();
    console.log(people);
    $peopleSearchService.getEntities(people.Title)
    .then(
        function (data) {
            self.result = data;
            dfd.resolve(true);
        },
        function (error) {
            dfd.resolve(false);
            console.error(error);
        }
    );
    return dfd.promise;
}
```

where the **getEntities**:

``` javascript
this.getEntities = function (request) {
    var deferred = $q.defer();
    $formDigestIntervalService.startFormDigestInterval($rootScope)
    .then(function (data) {
        $http.defaults.headers.post['X-HTTP-Method'] = "";
        var query = self.restUrl + "SP.UI.ApplicationPages.ClientPeoplePickerWebServiceInterface.clientPeoplePickerSearchUser";
        var data = {
            queryParams: {
                __metadata: {'type':'SP.UI.ApplicationPages.ClientPeoplePickerQueryParameters'},
                AllowMultipleEntities: false,
                MaximumEntitySuggestions: 50,
                PrincipalSource: 15,
                PrincipalType: 15,
                QueryString: request
            }
        };

        $http.post(
            query,
            JSON.stringify(data)
        )
        .success(function (data) {
            var result = data.d.ClientPeoplePickerSearchUser;
            deferred.resolve(JSON.parse(result));
            console.log(JSON.parse(result));
        })
        .error(function (error) {
            deferred.reject(error);
        });
    });
    return deferred.promise;
};
```

As you can see this is a normal **REST API** post.
So I can read back the data from the SharePoint to the tags input field with the model, but after that I cannot add another "tag" (name) to the input field, because I get the following error message:

```
TypeError: Cannot read property 'data' of undefined
    at ng-tags-input.js:590
    at angular.js:14567
    at n.$eval (angular.js:15846)
    at n.$digest (angular.js:15657)
    at n.$apply (angular.js:15951)
    at angular.js:17718
    at e (angular.js:5394)
    at angular.js:5666
```

Everything else is working well. If the tag input is empty, the auto-complete is working well, I can add multiple names, groups with special template. Please help me, why is the `items` _undefined_?

**Comment by lucaswelander** [comment]
I had this issue and it was poking me because I had forgot to add the `vm.` to the function in the view when I was using `controllerAs: 'vm'` when I setup my controller. By missing the vm. thingy I generated this error message from it.

So make sure that you reference your source to your controller on the `<auto-complete>` directive.

**Comment by mizhon** [comment]
Aslo got this error before, after code review, I got to know the method just need a "promise", not necessary to assign a certain value, I think that's why we receive "Cannot read property 'data' of undefined" error. Just a little trap here :)

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
