### ISSUE TITLE
Ionic : auto-complete source is never invoked

### ISSUE THREAD

**Issue by StephJan** [mbenford/ngTagsInput#583]
Hi,

I'm using ngTagsInput on in an Ionic project, debugged via ADB from  a physical Lollipop device.

Whenever autocomplete source is supposed to get invoked, I get the following exception in the console :  

TypeError: Cannot read property 'data' of undefined
    at ng-tags-input.js:590
    at processQueue (ionic.bundle.js:23394)
    at ionic.bundle.js:23410
    at Scope.$eval (ionic.bundle.js:24673)
    at Scope.$digest (ionic.bundle.js:24484)
    at Scope.$apply (ionic.bundle.js:24778)
    at ionic.bundle.js:26545
    at completeOutstandingRequest (ionic.bundle.js:14221)
    at ionic.bundle.js:14493

which indicates that the items supposedly retrieved from autocomplete are empty.

My page definition is very classic :

```
    <tags-input ng-model="tagdata.tags">
      <auto-complete source="loadTags($query)"></auto-complete>
    </tags-input>
```

while the (otherwise functioning) controller was narrowed down to something very similar to one of your plunkers :

```
$scope.loadTags = function(query) {
  console.log("Getting promise with query = " + JSON.stingify(query));
  return tagService.load(query);
};
```

The tag service itself being:

angular.module('myapp')
  .service('tagService', function($q) {
    var tags = [
      { "text": "Tag1" },
      { "text": "Tag2" },
      { "text": "Tag3" },
      { "text": "Tag4" },
      { "text": "Tag5" },
      { "text": "Tag6" },
      { "text": "Tag7" },
      { "text": "Tag8" },
      { "text": "Tag9" },
      { "text": "Tag10" }
    ];

```
this.load = function() {
  var deferred = $q.defer();
  deferred.resolve(tags);

  console.log("Defer being executed");

  return deferred.promise;
};
```

  })

None of the log get displayed, meaning that loadTags() from controller was never called ... any idea how this could be ? Thanks

**Comment by vundyalaavinash** [comment]
+1

**Comment by staydecent** [comment]
Having the exact same issue. Digging through the source-code now, but might be faster to hook together some other libraries.

**Comment by masscreation** [comment]
+1

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by afrozl** [comment]
I'm having this exact issue - autocomplete directive never fires and loadTags never gets called... 

Just a bunch of error message anytime more than 3 characters are typed:
```
TypeError: Cannot read property 'data' of undefined
    at /angular/ng-tags-input.js
```
 I realize this is a pretty old issue, but did any of you figure out what the problem was?
