### ISSUE TITLE
"onInvalidTag" event not triggering a callback

### ISSUE THREAD

**Issue by Kamilius** [mbenford/ngTagsInput#585]
Option "AddFromAutocompleteOnly" is turned on.
The thing is, that I'm trying to catch moment when user tries to enter a tag which is not in "Autocomplete" list.
Logically I thought that this will be handled by "onInvalidTag" callback, but for some reason it is not triggering.

What is a proper way of handling this case?

**Comment by murilozilli** [comment]
@Kamilius Why did you close this? I am facing the same problem
