### ISSUE TITLE
minification broken - wrong directive definitions

### ISSUE THREAD

**Issue by mobidev111** [mbenford/ngTagsInput#589]
two directives don't get defined correctly:

--> change to:

```
  tagsInput.directive('tiTranscludeAppend', [function() {
  tagsInput.directive('tiBindAttrs', [function() {
```

this is critical - we cannot ship our production code without this.

**Comment by mobidev111** [comment]
@mbenford any update?

**Comment by mobidev111** [comment]
@mbenford any update? 

in case you're busy: who else can help add the code changes / merge pull requests?

**Comment by mbenford** [comment]
Sorry for not replying sooner.

I don't quite understand the problem you are experiencing. The source code of all directives (and services, for that matter) is concatenated, annotated and compressed (minified) at build time, and everything has been working just fine so far. You can actually check that out by taking a look at the [build artifacts](https://s3.amazonaws.com/ng-tags-input/ng-tags-input.min.zip) generated by Travis after each successful build.

I wonder if you could clarify your issue better?

**Comment by mobidev111** [comment]
### Background: explicit dependency injection helps track dependency injection bugs
- I use turned off implicit dependency injection - using the ng-strict-di directive
http://stackoverflow.com/questions/18782324/angularjs-minify-best-practice/26734698#26734698
- the why: "the application will fail to invoke functions which do not use explicit function annotation (and are thus unsuitable for minification), as described in the Dependency Injection guide, and useful debugging info will assist in tracking down the root of these bugs."
http://stackoverflow.com/questions/17238759/angular-module-minification-bug/24659782#24659782

### Situation: ngTagsInput v3.0.0 uses explicit dependency injection for almost all methods
e.g.: 
```
tagsInput.directive('tagsInput', ["$timeout", "$document", "$window", "tagsInputConfig", "tiUtil", function($timeout, $document, $window, tagsInputConfig, tiUtil) {
```

### Problem: Few methods lack explicit dependency injection
We do minify ngTagsInput in our own build process

A few methods lack explicit dependency injection - e.g.

```
tagsInput.directive('tiTranscludeAppend', function() {
```
```
tagsInput.directive('tiBindAttrs', function() {
```

### Impact: breaks ngTagsInput minification in strict mode
This  breaks the minification with turned on strict dependency injection.

### Solution

* change
```
tagsInput.directive('tiTranscludeAppend', function() {
-->
tagsInput.directive('tiTranscludeAppend', [function() {
```

* change
```
tagsInput.directive('tiBindAttrs', function() {
-->
tagsInput.directive('tiBindAttrs', [function() {
```

Sorry, I assumed too much from the context - since almost all methods use explicit dependency injection, I thought the two missing ones are an small oversight..

Does this shed some light on the situation?

**Comment by mbenford** [comment]
Thanks for the clarification.

As I mentioned, at build time ngAnnotate ensures that explicit dependency injection is used wherever it is required. Those particular directives (`tiBindAttrs` and `tiTranscludeAppend`) don't have any dependencies, so as far as I know they don't need any annotation for minification to work. In fact, ngAnnotate leaves them untouched for that very reason.

I've created these examples ([here](http://plnkr.co/edit/aH4jZ1daMQTUw7PUU5lk?p=preview) and [here](http://plnkr.co/edit/BSKX92UnkDUox8pwNi7V?p=preview)) to show that only components with external dependencies need to be annotated so they work with strict DI mode, and one of them uses ngTagsInput.

Is Angular telling you that those two directives need to be explicit annotated, even though they have no dependencies?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
