### ISSUE TITLE
Autocomplete item not being selected on enter

### ISSUE THREAD

**Issue by wolkvolk** [mbenford/ngTagsInput#593]
When I press enter after having typed a partially matched tag name, the full autocompleted name for that name is not being selected. Instead the partially typed name is added to the list of tags (e.g. 'Tag o' instead of 'Tag one').

This bug appears when using ngTagsInput in combination with AngularJS 1.5 RC0, but not with AngularJS 1.4.8.

I've tried setting the parameter `select-first-match` to both true and false, but this did not have any effect.

Here's the configuration I'm using:

```
<tags-input ng-model="vm.tags" 
           key-property="tag_name" 
           display-property="tag_name" 
           add-on-enter="true" 
           add-on-space="false" 
           add-on-comma="false" 
           add-on-blur="false" 
           add-on-paste="false" 
           replace-spaces-with-dashes="false"
           on-tag-adding="vm.addTag($tag)" 
           on-tag-removing="vm.removeTag($tag)"
           enable-editing-last-tag="false" 
           select-on-backspace="false" 
           template="{{vm.templateName}}">

    <auto-complete source="vm.GroupTags.search($query)" 
                  display-property="tag_name"
                  min-length="1"
                  debounce-delay="0">
    </auto-complete>

</tags-input>
```

**Comment by alyrik** [comment]
+ The same is for me.

**Comment by exp-gokul** [comment]
I am also having the same issue. Is there any solution ?

**Comment by alangria** [comment]
Looks like on 'input-keydown' registration changes with AngularJS 1.5. 
One workaround is to change SimplePubSub's On method to do 'unshift' instead of  push;; but this is not a good solution and seems brittle

**Comment by salgmachine** [comment]
definitely an issue with angularjs 1.5.0, selection by enter key from the autocomplete list isn't working for me as well. the markup i'm using is pretty simple:

```
<tags-input id="tags" ng-model="selected.tokens" add-on-enter="true">
<auto-complete source="loadTags($query)">
</auto-complete> 
</tags-input>

```

**Comment by asaarnak** [comment]
same problem

**Comment by tfeslee** [comment]
I've found where to change.
https://github.com/angular/angular.js/commit/652b83eb226131d131a44453520a569202aa4aac?diff=unified

`auto-complete` is compiled after `tags-input` compile thus to be ensure that is first listener to `auto-complete`.

**Comment by igalt** [comment]
so from reading this thread it seems like this has been fixed?
I updated my files and it's still the same.
am I missing something?

**Comment by danidev** [comment]
Same issue here...using angular 1.5.5 and ng-tags-input 3.0.0

**Comment by yugansh20** [comment]
Facing same problem.
Any solution yet??

**Comment by davidamitchell** [comment]
@yugansh20 have a look at: https://github.com/mbenford/ngTagsInput/issues/638#issuecomment-218357299.  the commit reference a few comments above this one seems to have fixed the issue.

**Comment by facultymatt** [comment]
Great this is fixed - can we get a 3.0.1 release with the fix please?

**Comment by Zhouzi** [comment]
If you need it right now, you can get it by running:

```
npm install --save wizbii/ngTagsInput#v3.0.1
```

It's going to pull a built version with the latest commits. **Please also note that it includes a new feature to use a custom "track by" expression (it's pending merge #633).**

**Comment by mbenford** [comment]
Just so you guys know, version 3.1.1 has been released earlier today on all distribution channels. v3.1.0 has a bug that affects applications using Angular prior than 1.5.x, so don't use it.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
