### ISSUE TITLE
Activating autocomplete on first letter instead of third?

### ISSUE THREAD

**Issue by chrillewoodz** [mbenford/ngTagsInput#595]
I find it really annoying that the autocomplete doesn't activate until the third letter is entered, is there a way to change this? Been looking through the issues but no one else seem to be as frustrated by this as I am, perhaps I've missed a setting somewhere? 

Thanks in advance.

**Comment by paul-barry-kenzan** [comment]
@chrillewoodz 
The autocomplete directive has a `min-length` attribute that can be used to set the amount of characters required before the suggestions display.

http://mbenford.github.io/ngTagsInput/documentation/api#autoComplete

**Comment by chrillewoodz** [comment]
Just found it after I looked really hard one more time, but thanks for your reply! :)

**Comment by RodolpheGohard** [comment]
just a note for anyone wondering: a `min-length` is also available on `ng-tags-input` but limits the length of newly input tags, which is not to be confused with the attribute on the `auto-complete` element.

**Comment by Legend-Mortal** [comment]
```
<AutoCompleteTextView
        android:id="@+id/auto_complete_tv"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:completionThreshold="1"
        android:hint="Name" />
```

by `android:completionThreshold="1"` you can activate autocomplete on first letter instead of third
