### ISSUE TITLE
is this still maintained?

### ISSUE THREAD

**Issue by sibelius** [mbenford/ngTagsInput#610]
I would like to know where this is still maintained?

@mbenford I could help you to merge some PR and screening issues

Ping me on twitter @sseraphini or on email: sibeliusseraphini@gmail.com

Thanks for this component!

**Comment by anas10** [comment]
+1 @mbenford

**Comment by shyamal890** [comment]
+1 

I was wondering the same. I have raised this issue since many days no reply - https://github.com/mbenford/ngTagsInput/issues/578

**Comment by vieiralucas** [comment]
+1

**Comment by mbenford** [comment]
@sibeliusseraphini Yes, it is. Kind of. :)

I just posted [an issue](https://github.com/mbenford/ngTagsInput/issues/613) explaining my plans for 2016. I appreciate your willingness to help.  I'll try to get in touch with you later this week.

**Comment by sibeliusseraphini** [comment]
@mbenford thanks for the response

**Comment by shyamal890** [comment]
@sibeliusseraphini if you have permission to merge PRs, can you please have a look at Custom Tag classes? https://github.com/mbenford/ngTagsInput/issues/273

**Comment by sibeliusseraphini** [comment]
@shyamal890 ask @mbenford to be a contributor
