### ISSUE TITLE
Roadmap for 2016

### ISSUE THREAD

**Issue by mbenford** [mbenford/ngTagsInput#613]
Hi folks.

2015 was a slow year for ngTagsInput. Only three releases saw the light of day and the reasons for that are twofold: 1) my spare time was next to nothing throughout the year, and 2) I no longer use the directive in the projects I'm currently working on, and that seriously affects the so-called _[open source stamina](https://medium.com/@kentcdodds/open-source-stamina-dafd063f9932)_. But in spite of that, I'm aware that many people use ngTagsInput (if GitHub stars are an indication of anything) and I'm willing to invest a couple of hours every week in order to get the ball rolling again.

So here's the plan for 2016 (in no particular order):
- Address all major issues currently open (bugs and features that will be useful for most people);
- Update the docs;
- Update the main website;
- ~~Move~~ Copy all demos to JS Bin,  ~~since Plunker has been unstable lately~~ for redundancy purposes;
- Merge/close all currently open pull requests;
- Ensure everything works with latest Angular 1.x releases.

So there you have it. And if you use ngTagsInput and want to help me get all of the above done, I'll very much appreciate it. :)

P.S: In case you missed Angular 2 support on the list above, it wasn't left out by mistake. I honestly don't know whether I'll be able to rewrite ngTagsInput from scratch in order for it to work with Angular 2. Only time will tell.

**Comment by shyamal890** [comment]
Just one request please don't shift from Plunker to JS Bin

**Comment by mbenford** [comment]
@shyamal890 why not?

**Comment by shyamal890** [comment]
I think Plunker is easier to use than JS Bin

**Comment by jfairley** [comment]
Thanks for the update. :clap:

**Comment by ggoodman** [comment]
FYI, Plunker.NEXT is a user of `ngTagsInput` (and would love a base `.less` stylesheet that `(reference)`es the bootstrap variables instead of hard-codes styles).

I'm also in favour of sticking with Plunker. You are right to say that over the holidays, Plunker experienced abnormal levels of unavailability. I have since replaced the mongo clusters and made improvements that should make Plunker's availability much stronger.

![image](https://cloud.githubusercontent.com/assets/50030/12584107/ed159648-c413-11e5-8ee6-3df76efdf015.png)

**Comment by mbenford** [comment]
@ggoodman thanks for the update on Plunker status. I personally have no reason to move away from Plunker; it's been working for me quite well. I just thought of switching to another service because some people were affected by Plunker's recent instability and I couldn't do much about it. But come to think of it, perhaps the best option is to use both Plunker and JS Bin.

**Comment by ggoodman** [comment]
@mbenford can't argue with that logic. Hope 2016 brings lots of motivation and long periods of uninterrupted productivity! :)

**Comment by anvesh48** [comment]
@mbenford Michael do you know any other ngTagsInputs plugins that support for angular-2 and has all the features currently we have in this?

**Comment by tfont** [comment]
Without Angular 2+ support this library will eventually die out. Something worth pointing out..

**Comment by StephJan** [comment]
@tfont : couldn't agree more ... I'm porting my Ionic/Angular 1.x app to Ionic/Angular 2.x, and I'm stuck without a decent tags input component, while ngTagsInput was perfect :(

Too bad I don't have the knowledge to assist with this migration...

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
