### ISSUE TITLE
Suggestions should not replace whitespace with - in model

### ISSUE THREAD

**Issue by MichaelArnoldOwens** [mbenford/ngTagsInput#620]
Given these suggestions:

```
[
{text: 'The Great Dane'},
{text: 'Nate The Great'},
{text: 'Great Cheese'}
]
```

If I select

`{text: 'Great Cheese'}
`

This will be stored in the model as:

`{text: 'Great-Cheese'}
`

ngTagsInput should **not** transform my data

**Comment by mbenford** [comment]
You can disable that behavior by setting the `replaceSpacesWithDashes` option to false. The [documentation](http://mbenford.github.io/ngTagsInput/documentation/api) is your friend. :)

**Comment by MichaelArnoldOwens** [comment]
Sorry, I missed this one! Thanks for the reply :+1:
