### ISSUE TITLE
Update scope array won't refresh until tap on tag-input

### ISSUE THREAD

**Issue by scottj425** [mbenford/ngTagsInput#621]
Hi,

I am trying to update the scope array attached to ng-model variable programatically. I update the array and then the tag-input is not refreshed until i tap on it. Any way to have the tag-input refresh programmatically?

**Comment by scottj425** [comment]
Sorry, I was not using the correct variable name

**Comment by lewp** [comment]
@scottj425 how did you figure this out?  I am having a similar problem.

**Comment by scottj425** [comment]
I needed to call scope.apply(); after the selection

**Comment by rqx110** [comment]
I also have similar problem, could you share your code? @scottj425
