### ISSUE TITLE
on-tag-added expression should be evaluated AFTER tag is added to ngModel whenever adding a tag

### ISSUE THREAD

**Issue by MichaelArnoldOwens** [mbenford/ngTagsInput#622]
When I enter in the first tag, on-tag-added expression gets evaluated BEFORE the tag is added to ngModel. However on the second tag I add, ng-model is updated AFTER evaluating on-tag-added expression.

This inconsistent behavior should be fixed such that whether it's the 1st tag or nth tag, the on-tag-added expression should be evaluated after ngModel is updated.

**Comment by Cassidie** [comment]
I had this issue today! I fixed this by moving the tag-added callback event to later in the following section of ng-tags-input.js under the link function:

events
.on('invalid-tag', scope.onInvalidTag)
.on('tag-removed', scope.onTagRemoved)
.on('tag-clicked', scope.onTagClicked)
.on('tag-added', function() {
      scope.newTag.text('');
})
.on('tag-added tag-removed', function() {
      scope.tags = tagList.items;
      ngModelCtrl.$setDirty();
})
.on('tag-added', scope.onTagAdded)   // Moved this to the last tag-added call
.on('invalid-tag', function() {
     scope.newTag.invalid = true;
})

I tried to add this to github, but it seemed like my js file was really different. We might've refactored it ourselves. But if you can find where the tag-added callback is, just move it further down the list of events! Hope it works for you, too!

**Comment by corse-xx** [comment]
are you sure your initiliasing the tag's model variable as an array? i had this problem until i initialised it as tags = []; in the controller

**Comment by JackGommeren** [comment]
I am having this problem as well and had to fix it by using a timeout. I tried initialising the list with an array but this made no diffirence.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
