### ISSUE TITLE
Duplicates in a repeater are not allowed.

### ISSUE THREAD

**Issue by BukicMicko** [mbenford/ngTagsInput#629]
Hi guys,

I have this problem when using auto-complete from ngTagsInput directive:

Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: tag in tagList.items track by track(tag), Duplicate key

For example this is response that i get:

```
 {
    "id": "101",
    "create_date": "2016-02-01T18:33:39Z",
    "tag_token": "Tag 2",
    "parent_id": "2",
    "parent_type": "FILE"
},
{
    "id": "102",
   "create_date_tdt": "2016-02-01T18:33:39Z",
   "tag_token": "Tag 2",
   "parent_id": "3",
   "parent_type": "FILE"
} 
```

and this is view where I am using tags-input

```
  <tags-input             
                ng-model="searchQuery"
                display-property="tag_token"
                key-property="tag_token"
                on-tag-adding="checkTag($tag)"
                on-tag-removed="onTagRemoved($tag)"
                replace-spaces-with-dashes="false"
                add-from-autocomplete-only="true"
            >
            <auto-complete min-length="1" max-results-to-show="10" source="typeahead($query)"></auto-complete>
            </tags-input>
```

As you can see i have same value "Tag 2" for tag_token. I tried using key-property="tag_token track by $index", but still no success...same error. How can I solve this problem?

Regards,
Bojan

**Comment by canivel** [comment]
Same here... where do I download the this build?

**Comment by cariquitanmac** [comment]
I've experienced this also and my fix is to make sure that I returned a promise in my source and not an array.  So for this one `source="typeahead($query)"` make sure that it will return a promise.

**Comment by sabareeshkk** [comment]
give a unique value in the key-property attribute. like id or something.unique to be tracked.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
