### ISSUE TITLE
Define the onTagAdded trigger method

### ISSUE THREAD

**Issue by brunifrancesco** [mbenford/ngTagsInput#63]
Hi all, 
I'm using the ngTaginput, but I do not understand where I have to define the onTagAdded trigger. 
I saw someone solved this iussue, but there's not a clear explanation there. 
Thanks
FB

**Comment by kunalthool** [comment]
Thanks Awesome, really i have wasted lots for hours for this.

**Comment by comapedrosa** [comment]
Thank you!

**Comment by felipepastor** [comment]
+1

**Comment by davidsanders** [comment]
Would love to see this on the doc site! ;)

**Comment by ZikZakJainy** [comment]
Thank ..U..

**Comment by suvarnajayanth** [comment]
Awesome , 
I need a help here , want to stop removing few tags, written some thing like below , its not working 
$scope.onTagRemoving = function(tag) {

if(tag == "XYZ"){
	  	return false;
}else{
	  	return true;
} 
};

Please suggest me

**Comment by felipepastor** [comment]
@suvarnajayanth Use the function 
`$scope.tagRemoved = function(tag) {
if(tag === "XYZ"){
	  	return false;
}else{
	  	return true;
} 
    };`

instead of ontagremove and get the tag from parameter.

**Comment by suvarnajayanth** [comment]
Hi Thanks for quick reply ,
I just want to stop removing few of the tag 
`  $scope.tagRemoved = function(tag) {

	  	
	  	return false;
        
    };`

Even this is not working

**Comment by felipepastor** [comment]
Is the event even being triggered? Can you debug and check if the
breakpoint is stopping on that?

**Comment by suvarnajayanth** [comment]
@felipepastor 
Yes event is triggering , i did put alerts inside methods .

**Comment by felipepastor** [comment]
Well, so returning false in some condition should cancel the event and not
remove the tag from the DOM, unless it's triggering the remove event after
remove from DOM.

**Comment by suvarnajayanth** [comment]
@felipepastor 

Its not cancelling the event . 

```
$scope.tagRemoved = function(tag) {

	  	alert("test");
	  	return false;
        
    };
```
It alerts test, once i click on alert ok button, it will remove items

**Comment by felipepastor** [comment]
It's calling the event, but we have another bind to remove the UI elements
from the DOM and it's happening first of tagRemoved Event, that's my guess.
Try to go into the function and find where it triggers. Later I'll try to
implement something with this again and let you know my finds.

**Comment by suvarnajayanth** [comment]
Ok Thank you

**Comment by NP00490312** [comment]
on-tag-removing event is not firing. suvarnajayanth  i having the same requirement.
