### ISSUE TITLE
Wrap tag longer than the width of the tag-input

### ISSUE THREAD

**Issue by ja67** [mbenford/ngTagsInput#642]
I am using ng-tags-input 3.0.0 on my site with angular 1.3.8. I just found an issue that if user inputs keywords that is longer the width of the tag-input, it would be weird when displaying that keyword like

http://plnkr.co/edit/lcn2aR?p=preview

While there is a maximum length of the tag that user inputs, I was wondering if the long tag tag can still be displayed correctly like wrapping it. A simple solution is just change the style of the tag-item to something like:
`.tag-item {
              height:auto;
              max-width:100%;
            }
` 
Hope this helps!

**Comment by beans9** [comment]
i sold this. 

first set css
`tags-input .tags span {
    display: inline-block;
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
}

@for $i from 1 through 50 {
  .max-width-#{20 * $i} span {
    max-width:((20px * $i)-50px);
  }
}
`

and add class in tags-input tag
`<tags-input ng-model="test" class="max-width-240"></tags-input>`

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by cdmckay** [comment]
This is what I went with:
```
tags-input .tags .tag-item {

  max-width: calc(100% - 5px);
  padding-right: 20px;
  position: relative;

  span {
    display: inline-block;
    max-width: 100%;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .remove-button {
    position: absolute;
    right: 4px;
    top: 4px;
  }

}
```

Ends up looking like this:
<img width="674" alt="screenshot" src="https://user-images.githubusercontent.com/67923/30669529-8a36de98-9e13-11e7-837b-4a4f7513d873.png">

**Comment by Tommy9021** [comment]
@cdmckay Can you provide a plunker/jsfiddle ? Thanks so much.
