### ISSUE TITLE
autocomplete not showing matching results

### ISSUE THREAD

**Issue by rishijain** [mbenford/ngTagsInput#655]
autocomplete shows all the objects in list irrespective of what I have typed.
ex: I have typed in 'abc' in input box, autocomplete will show me all results and not just the ones matching abc.

Its weird. It works fine here: http://mbenford.github.io/ngTagsInput/

but on the demo pages, the example of autocomplete, it works the way I mentioned above.

I am not sure why 2 different behaviour.

**Comment by rishijain** [comment]
Well it was a mistake on my part.

Instead of passing a function load_items($query), I passed an array of strings. So it always returned the array irrespective of what I typed.

In this function, load_items($query), I matched the `indexOf` of the typed string and returned the result of matching strings in an array.

**Comment by Dean-Christian-Armada** [comment]
Could you write an example code?

**Comment by rishijain** [comment]
In html, I have something like this:
`<auto-complete source="load_items($query, all_items)" select-first-match=="false" highlight-matched-text="true"></auto-complete>`

and in controller I have a function `load_items` which is defined like this:
`
  $scope.load_items = function(query, parent_object) {
      query = query.toLowerCase();
      var result = [];
      angular.forEach(parent_object, function(item, index){
        if(item.toLowerCase().indexOf(query) != -1){
            result.push(item);
        }
      });
      return result;
  };
`

This above function returns the result in an array of items matched with the query.

**Comment by Dean-Christian-Armada** [comment]
What about the all_items?

**Comment by rishijain** [comment]
@Dean-Christian-Armada  `all_items` is an array of pre-defined values from which it tries to match with the typed `query`.

**Comment by Dean-Christian-Armada** [comment]
I got it anyway, but this will be a great help for everyone.
