### ISSUE TITLE
On removing first tag, scope is updated, but view isn't

### ISSUE THREAD

**Issue by psmod2** [mbenford/ngTagsInput#657]
Hi,

In my ngTagsInput Field if i have `one, two, three`. 

When i click on remove `one` the fields shows 

`one, two`, 

rather than 

`two, three`

I've checked the model variable and it appears fine. Is this a bug or am i doing something wrong. I even tried using my own tagRemoved method to attempt however no luck:

```
<tags-input ng-model="detail.tagsToAddField" add-on-space="true"
                    placeholder="." on-tag-removed="detail.tagRemoved($tag)">
 </tags-input>
```

```
self.tagRemoved = function($tag) {
    console.log($scope.detail.tagsToAddField);    //this shows me 2 Objects, two and three so why is one still there?   
};
```

**Comment by rishijain** [comment]
Hi @psmod2 , can you give a jsFiddle reproducing the bug? It would help. Because I cannot reproduce the behaviour you mentioned.

**Comment by psmod2** [comment]
I'm not sure what was going on, however on using the JS directly from the URL below, all works fine:

<link rel="stylesheet" href="http://mbenford.github.io/ngTagsInput/css/ng-tags-input.min.css" />
<script src="http://mbenford.github.io/ngTagsInput/js/ng-tags-input.min.js"></script>

rather than from Bower.

Anyway, solved for now.
