### ISSUE TITLE
Trying to create auto-complete

### ISSUE THREAD

**Issue by RonenMars** [mbenford/ngTagsInput#667]
Hi,

It looks like that:
HTML:

```
    <div class="row expanded columns RowGray" style="margin-bottom: 2%;">
        <div class="medium-2 columns">סינון:</div>
        <div class="medium-10 columns">על פי מנחה: <tags-input ng-model="lecturerFilter" id="lecturerFilter" add-on-paste="true">

            <auto-complete source="loadTags($query)"></auto-complete>
        </tags-input></div>
    </div>
```

Controller:

```
    $http({
        method: 'GET',
        url: 'api/users/for-project/names/software/lecturer',
    }).then(function (result) {
        $scope.lecturers = result.data;
    });

    $scope.loadTags = function(query) {
        var tags =[
            { "text": "Tag1" },
            { "text": "Tag2" },
            { "text": "Tag3" },
            { "text": "Tag4" },
            { "text": "Tag5" },
            { "text": "Tag6" },
            { "text": "Tag7" },
            { "text": "Tag8" },
            { "text": "Tag9" },
            { "text": "Tag10" }
            ];
        return tags;
    };
```

And in the page I get: 

> ```
> angular.min.js:107 TypeError: array.some is not a function
> at Object.self.findInObjectArray (http://localhost:3000/js/ng-tags-input/ng-tags-input.js:1046:15)
> at TagList.tagIsValid (http://localhost:3000/js/ng-tags-input/ng-tags-input.js:98:28)
> at Object.TagList.self.add (http://localhost:3000/js/ng-tags-input/ng-tags-input.js:119:17)
> at Object.TagList.self.addText (http://localhost:3000/js/ng-tags-input/ng-tags-input.js:107:25)
> at http://localhost:3000/js/ng-tags-input/ng-tags-input.js:407:33
> at http://localhost:3000/js/ng-tags-input/ng-tags-input.js:1093:29
> at http://localhost:3000/js/ng-tags-input/ng-tags-input.js:1121:69
> at Array.every (native)
> at Object.trigger (http://localhost:3000/js/ng-tags-input/ng-tags-input.js:1120:26)
> at http://localhost:3000/js/ng-tags-input/ng-tags-input.js:347:40
> ```

**Comment by noherczeg** [comment]
Try `key-property` and/or `display-property`

**Comment by noherczeg** [comment]
I think key-property="text" should be a good start.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
