### ISSUE TITLE
Any way for edit tags?

### ISSUE THREAD

**Issue by nevedimko** [mbenford/ngTagsInput#674]
Can I edit already existing tags? Anyway?

**Comment by daric81** [comment]
+1

**Comment by mbenford** [comment]
Currently only the last tag that was added can be edited if the `enableEditingLastTag` is set as `true`.

**Comment by cguran** [comment]
Very nice library. Editing tags would be very useful for us also.  There might be a problem with people adding the same value as another tag though in case of edit.

**Comment by kishoreMaria** [comment]
Mr. @mbenford, can we able to edit existing tags now..?
