### ISSUE TITLE
Selections are not visible, potential hotkey problems as well?

### ISSUE THREAD

**Issue by noherczeg** [mbenford/ngTagsInput#683]
Hey!

Before anything I find your library very neat! Good job!

Now for the sad part: it seems like hotkeys or selections are not working for us right now. I went to see the code what happens when I push the DOWN ARROW key and it sets the self.selected element, but I can't see it highlighted. Plus the focus stays inside the input part of the component.

Angular version: 1.3.18
Version: 3.1.1

Configuration:

```
<tags-input
                ng-if="viewField.$single && viewField.$single.isCodeStoreRelation()"
                id="{{ ::viewField.$single.id }}_filter"
                ng-model="vm.filter.values[viewField.name]"
                class="ti-input-sm"
                key-property="code"
                display-property="value"
                add-from-autocomplete-only="true"
                add-on-blur="false"
                min-tags="0"
                allow-leftover-text="false">
        <auto-complete
                        source="vm.loadTags($query, viewField)"
                        display-property="value"
                        max-results-to-show="5"
                        min-length="2"
                        highlight-matched-text="true"
                        load-on-empty="false"
                        load-on-down-arrow="true">
        </auto-complete>
</tags-input>
```

We use the bootstrap styling as well (not the minified one since it is part of our build process).

Could it be that the tags component collide with other libraries? We also use cfp-hotkeys as well.

Thanks in advance!

**Comment by noherczeg** [comment]
Is it normal that a full blown object is being placed inside of the class property of the autosuggest list items?

[image](http://i.imgur.com/yVwHfTo.png)

**Comment by noherczeg** [comment]
Seems like hotkeys are working, but the styling is off for some reason.

**Comment by noherczeg** [comment]
It works in 3.0.0

It does not work in 3.1.0 either though. I don't have time right now to investigate further, but my wild guess is that you may used something not available in angular 1.3.x?

**Comment by TodorTodorin** [comment]
It's caused by ng-class. This method `getSuggestionClass` is depending on "Array and Map Syntax" of ng-class which is supported on angular 1.4.0+

**Comment by vdsabev** [comment]
@TodorTodorin a reference from the [1.4.0 documentation](https://code.angularjs.org/1.4.0/docs/api/ng/directive/ngClass):

> The directive operates in three different ways, depending on which of three types the expression evaluates to:
> 1. If the expression evaluates to a string, the string should be one or more space-delimited class names.
> 2. If the expression evaluates to an object, then for each key-value pair of the object with a truthy value the corresponding key is used as a class name.
> **3. If the expression evaluates to an array, each element of the array should either be a string as in type 1 or an object as in type 2.** This means that you can mix strings and objects together in an array to give you more control over what CSS classes appear.

Compared to the [1.3.20 documentation](https://code.angularjs.org/1.4.0/docs/api/ng/directive/ngClass):
> The directive operates in three different ways, depending on which of three types the expression evaluates to:
> 1. If the expression evaluates to a string, the string should be one or more space-delimited class names.
> **2. If the expression evaluates to an array, each element of the array should be a string that is one or more space-delimited class names.**
> 3. If the expression evaluates to an object, then for each key-value pair of the object with a truthy value the corresponding key is used as a class name.

**Comment by bsatorius** [comment]
Just wanted to add my own test results--

Angular version: 1.5.7
Version: 3.1.1

Bootstrap css: hotkeys and selections **not** working 
Default css: hotkeys and selections **are** working

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
