### ISSUE TITLE
Error using ngTagInput : TypeError: a.filter is not a function

### ISSUE THREAD

**Issue by surajsonawane111** [mbenford/ngTagsInput#702]
I am trying to use ngTagInput but getting following Error. Please help!

angular.min.js:117 TypeError: a.filter is not a function
    at d (ng-tags-input.min.js:1)
    at ng-tags-input.min.js:1
    at angular.min.js:130
    at n.$eval (angular.min.js:144)
    at n.$digest (angular.min.js:142)
    at n.$apply (angular.min.js:145)
    at l (angular.min.js:97)
    at H (angular.min.js:101)
    at XMLHttpRequest.u.onload (angular.min.js:102)

HTML Code:

                    <tags-input ng-model="selectedList">
                        <auto-complete source="getData($query)"></auto-complete>
                    </tags-input>

Javascript code:
      $scope.getData = function(query) { 
           var request = {
                     //GET request is defined here
            };
            return $http(request)
                .success(function (response, status) {
                    var defer = $q.defer();
                    defer.resolve([
                        { 'text': 'just' },
                        { 'text': 'some' },
                        { 'text': 'cool' },
                        { 'text': 'tags' }
                    ]);
                    return defer.promise;
                })
       }

**Comment by surajsonawane111** [comment]
@mbenford : Could you please help me with this. I feel this is a cool component and really want to use in my project. but, I am really blocked because of this issue.

Thanks in advance!

**Comment by tchinou1** [comment]
Same for me !

**Comment by surajsonawane111** [comment]
instead of .success, I should have used .then

It worked! Thanks @mbenford

**Comment by kondalraodurgam** [comment]
$scope.example= {
                                               "text" : [],
                                               "text" : [],
                                               "text" : [], 
                                                "text" : []
                                            };
I'm using like this i didn't understand is this right..?? but the error shows like this angular.js:13920 TypeError: a.filter is not a function
    at d (ng-tags-input.min.js:1)
    at ng-tags-input.min.js:1
    at processQueue (angular.js:16383)
    at angular.js:16399
    at Scope.$eval (angular.js:17682)
    at Scope.$digest (angular.js:17495)
    at Scope.$apply (angular.js:17790)
    at angular.js:19621
    at completeOutstandingRequest (angular.js:5964)
    at angular.js:6243
when i was added data error shows like please explain wihich one is right..??
