### ISSUE TITLE
Refactor to ES6

### ISSUE THREAD

**Issue by sibelius** [mbenford/ngTagsInput#712]
I think we should follow this styleguide https://github.com/toddmotto/angular-styleguide

and refactor ng-tags-input to use es6 syntax

**Comment by sibelius** [comment]
@mbenford I've just refactored and put the source here: https://github.com/sibelius/ngTagsInputES6

feel free to get this changes here

**Comment by mackbrowne** [comment]
Is this required to get it working in ES6 based projects?  I'm trying to get the basic examples working in my project [here](https://github.com/mackbrowne/meteor-angular-boilerplate).

I can upload an example of it not working if needed, but can anyone confirm this plugin still works?

**Comment by sibelius** [comment]
@mackbrowne https://github.com/mbenford/ngTagsInput/issues/711 is enough to make it work on webpack and es6 code

**Comment by mackbrowne** [comment]
Ok I've tried installing your fork straight from github with npm.  But you have .npmignore the src folder so when I install, I basically get nothing.  Do I need to fork your fork, build it, and then try adding it to my app?

**Comment by sibelius** [comment]
my repo is not ready yet

@mackbrowne let me know if you wanna access to help me finish it

**Comment by vladimiry** [comment]
You better rewrite to TypeScript since ES6 is nothing more than fancy syntax, but TypeScript would increase maintainability.

**Comment by maciejszpyra** [comment]
Adding `module.exports = tagsInput.name; ` is enough to make this module work with webpack. Can you add it?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by stevenvachon** [comment]
This should not have been spring-cleaned.
