### ISSUE TITLE
Allowing duplicate tags

### ISSUE THREAD

**Issue by fredspivock** [mbenford/ngTagsInput#713]
Looking for a way to have a user add multiple tags that could have the same text. Read about the "key-property" and don't really understand how you are suppose to use it to get the desired effect. Anyone use this property successfully? Thanks in advance.

**Comment by weihanchen** [comment]
I use index as id and works for me below
```html
<tags-input ng-model="tags" key-property="id" display-property="text" on-tag-added="tagAdded($tag)"></tags-input>
```
```javascript
$scope.tags=[];
$scope.tagAdded = function($tag) {
      $scope.tags = $scope.tags.map(function(tag,$index){
             return {
                  text: tag.text,
                  id: $index
             }
      })
}
```

But when paste duplicate tags still have some error like `Error: [ngRepeat:dupes]`

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by unkulesagar** [comment]
If array contains duplicate entries(same text but different ids) drop down does not appears. How to allow such duplicate entries? I have tried with "key-property='id'" suggested by the above solution but does not solve my problem. I have gone through similar issues with keyword duplicate but could not help me out.

<tags-input add-from-autocomplete-only=true 
                        	display-property=Name 
                        	ng-model=dispatcherTask.user 
                        	on-tag-added="tagAdded($tag, dispatcherTask)"
                        	placeholder="Pick User"
                        	keyProperty = Id                        	
                        	replace-spaces-with-dashes=false>
                           <auto-complete source="getPeoplePicker($query, dispatcherTask)"></auto-complete>
                        </tags-input>

array(
{
id:0,
name:xyz
email:xzy@x.com
}
{
id:1,
name:xyz
email:pqr@x.com
}
)
