### ISSUE TITLE
Question: How to I trigger tags-input internal events

### ISSUE THREAD

**Issue by werpu** [mbenford/ngTagsInput#714]
I could not find a discussion list on this component so I am trying my luck here.

Hi I have following issue/problem. I try to add editing capabilities to TagsInput from the outside. So far i have following. If I click on a tag I remove the tag and fill the tag value into the input. However I cannot find a way to notify the embedded tags-input that the int value has changed.
There is an internal event input-change which would do the trick to notify the component and clean up its internal state. But how to I trigger that from the outside?
Any ideas.

**Comment by werpu** [comment]
Ok I found it out myself, I can use the text attribute from the control to update the internal input state. So instead of setting the input directly I simply update the text attribute. My Usecase now works without the need to trigger the internal event system.

**Comment by wangdh1** [comment]
what's r u update the attribute,please give us some usecase of code?

**Comment by werpu** [comment]
Mhh I wrote that issue a year ago. I have solved in the meanwhile all my problems. I am not even sure anymore what the problem was back then. Sorry for the trouble. I guess you can close the issue.
