### ISSUE TITLE
Jitter when entering tags in IE11

### ISSUE THREAD

**Issue by dwharrison** [mbenford/ngTagsInput#715]
Using ngTagsInput on IE11, the text "jitters" when entering a tag into the control.  By that I mean that the text shakes around a bit as I type, making it hard to read.  This is a significant concern for our team, as it negatively affects the user experience, and given our customer base consists of enterprise users, IE11 is necessarily a prime browser for us to support.

I've seen this on both my code and on the control demo site, though the demo site is currently not showing it due to a JS error.

A [previous issue](https://github.com/mbenford/ngTagsInput/issues/568) covered this problem but was closed by the originator after a week with no action or comment, so I'm creating a new issue to cover it.

**Comment by ccesarz** [comment]
I'm experiencing the same jittery behavior while using this component in a large-scale web app. What is the ETA for resolving this issue?

**Comment by mayankkalbhor** [comment]
I know a workaround. It minimises the jittering. In your tags-input just add this spellcheck ="false" attribute. So what it does is it does not do the spell check and the jitter is reduce to more than 80 percent. Just try and see if it works.

**Comment by xyz017048** [comment]
I tried adding the spellcheck ="false" attribute and it did reduce the jittery effect by a lot. I'm only seeing the jittery effect when I enter space. That is very odd. Is there other ways that we could further reduce the effect?

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by bhuthardik333** [comment]
@mayankkalbhor 

Thank you so much. I just tried spellcheck ="false" attribute and it works like charm.
