### ISSUE TITLE
Autocomplete becomes useless with 10+ tags source

### ISSUE THREAD

**Issue by bptstmlgt** [mbenford/ngTagsInput#736]
Hey,

I've been very enthusiast about this nifty tool, but I only found out now what seems to be a big limitation to it. Or am I missing something? I hope I am!

When you have a list of tags (source) exceeding 10 items, e.g. 17 items, you won't be able to find those last > 10 tags in the autocomplete dropdown.

Here's an example with the demo using Autocomplete with $resource (which I'm also using in my code):
- add a couple more tags to the tags.json. I did it with 17 tags for this example.
- in the input field, type "Tag15" for instance. You won't see Tag15 in the autocomplete list. It will only load the first 10 elements in your source.
  Here's a screenshot of that: http://imgur.com/seKLmc0

I tried to do a plunker to show this but for some reason I cannot even see the input field on plunker edit mode. It will work from the demo page though: mbenford.github.io/ngTagsInput/demos

Thanks

**Comment by cfman** [comment]
You should look for the `maxResultsToShow` parameter in http://mbenford.github.io/ngTagsInput/documentation/api#autoComplete. It is set to 10 by default.

**Comment by ordwulf** [comment]
That only works up to a point, the list could have 100\1,000\10,000 values.

I think the limitation is, it is not showing a filtered list as per the ui.bootstrap.typeahead, in the original attached image you would expect to only see the matched values, 1 item, tag17.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by sguilly** [comment]
You could redefine your filter function : 

```
$scope.filter = function(query) {

                    return $q(function(resolve, reject) {

                        var filterArray = []

                        for (var index = 0; index < $scope.to.options.length && filterArray.length < 10; index++) {
                            var element = $scope.to.options[index];

                            if (element.name.toLowerCase().indexOf(query.toLowerCase()) > -1) {
                                filterArray.push(({ name: element.name, value: element.value }))
                            }
                        }

                        resolve(filterArray)
                    })
                }
```
and use it in the auto-complete tag

`<auto-complete min-length="1" source='filter($query)'></auto-complete>`
