### ISSUE TITLE
Watch input before adding tag

### ISSUE THREAD

**Issue by DDroll** [mbenford/ngTagsInput#747]
Hi all! Maybe i haven't dig anouth, but can anyone answer me :  is there any convinient way to watch user input before adding tag? I'll try to explain: i have two separate blocks - search string, where is placed "ng-tags-input" perfect directive, and few blocks below, each has it own tags input, with its own model. When user typing in search string, last tag in that lower blocks should updated in real-time. I have made this work earlier, then search string was just a string: but now i was asked to add tags in this search string too, and faced with this problem. I need just change event and value from input, but it looks like not so easy, as it sounds. Only way, i can see now, it use good-old jQuery, but.. ) May be, there is a way to solve it using $scope?

**Comment by AniWar** [comment]
![tags](https://cloud.githubusercontent.com/assets/16691390/23119097/c7f71470-f77c-11e6-97e4-77a7ae6fafe3.PNG)

JS
------------------------------------------------------------------------------------------------------------------
`var mod=angular.module("myApp",["ngTagsInput"]);
mod.controller("MyTags",AddTags);

function AddTags($scope){
console.log("Tags app has started");
$scope.tags=[];
$scope.addSearch=function(){
console.log("So tags we have is = "+$scope.tags);
$scope.tags.push({text:$scope.customTags});
}
}`

HTML
-----------------------------------------------------------------------------------------------------------------
		<div ng-controller="MyTags">
				<div>
						<input type="text" ng-model="customTags"/><button ng-click="addSearch()">Search</button>
						<h4> Your recent search Sir,</h4>
						<tags-input ng-model="tags" ></tags-input>						
				</div>
			

		</div>

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
