### ISSUE TITLE
Possible to prevent autofocus when removing tag?

### ISSUE THREAD

**Issue by iqbal-admedo** [mbenford/ngTagsInput#749]
Hi,

I am trying to find a way to prevent the autofocus from occurring on the input box when I remove a tag. The reason being is that we have cases where the tag list could be very large (over 200+) so we don't want users to lose their scroll position.

I couldn't find anything from the documentation, is it possible?

Thanks

**Comment by dani-lo** [comment]
Having the same problem - I have a long list of tags and when I click on one to delete it, the widget jumps to the bottom of the list (looks like its because the input gets focus so the widget jumps down to show the 'add tag' prompt / placeholder). Can not find a way to bypass this ...

**Comment by danieljin** [comment]
A better implementation would be to check that see if the input is in the current view and then focusing.

Or focusing but don't scroll.

**Comment by abhijeetbhanjadeo** [comment]
Having **"load-on-focus" set to false** (if it's not already) resolves the focus issue which causes the "Auto Complete" to triggered.  
[API Documentation](http://mbenford.github.io/ngTagsInput/documentation/api#autoComplete)

Similar thing happens for "load-on-empty" scenario, having it set to "false" resolves the empty load situation(when a new a tag is added/selected).

**Default value for both the attributes(load-on-empty,load-on-focus) are "false"** in "autoComplete" directive.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by popod** [comment]
I think this issus should be reopened and that all is write about it.
