### ISSUE TITLE
add on space|comma not respected on Galaxy S7, Nexus 6P, and Nexus 9

### ISSUE THREAD

**Issue by calebfaruki** [mbenford/ngTagsInput#770]
Problem devices: Galaxy S7, Nexus 6P, and Nexus 9

Here is how I am invoking the directive:

````
<tags-input name="emails"
  ng-model="edVm.emails"
  type="email"
  display-property="email"
  placeholder="Enter email addresses"
  min-tags="1" max-tags="10"
  add-on-space="true"
  add-on-comma="true"
  add-on-blur="true"
  replace-spaces-with-dashes="false"
  allowed-tags-pattern="^[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+$"></tags-input>
````

However, if I hit the return button on the keyboard, it will register the email as a tag. But when I type commas or spaces, nothing happens. This does not affect other Android versions.

**Comment by YouCantTriforce** [comment]
I can confirm this issue exists on Xiaomi Mi4C running Android 6.0.1 (CyanogenMod 13) using Crosswalk as runtime for hybrid application. User-agent: "Mozilla/5.0 (Linux; Android 6.0.1; Mi-4c Build/MHC19Q) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Crosswalk/22.52.561.4 Mobile Safari/537.36"

**Comment by YouCantTriforce** [comment]
Looks like #692 resolves the issue for commas. This approach probably won't work for spaces unless ngTrim is set to false for the input field.

**Comment by calebfaruki** [comment]
The library does automatically sets the ngTrim parameter to false. However, the bug still happens on these devices. I manually patched the library to include the fix from the PR you referenced. But the issue still persists. @YouCantTriforce 

Did you have any luck with these devices at all?

**Comment by YouCantTriforce** [comment]
I didn't have time to look into it yet. Once I get into fixing this issue I'll definitely post my observations here.

**Comment by calebfaruki** [comment]
I've identified the issue as being related to the keyCode value 229. When using a physical keyboard connected to an emulator, the 229 key code does not occur.

But if you use the software keyboard of the Android device, emulator or real device, the 229 key code event happens for ANY key pressed.

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.
