### ISSUE TITLE
Multiple tags without key property

### ISSUE THREAD

**Issue by somangshu** [mbenford/ngTagsInput#779]
I am trying to use ur directive as below

`<tags-input name="skill" ng-model="storage.skills" placeholder="specializations" min-tags="1" add-on-enter="true" min-length="1" key-property="id" display-property="name" required>
                        <auto-complete source="getSkillSearch($query)" highlight-matched-text="true" min-length="1"></auto-complete>
                    </tags-input>`

Here if you see i have set the key property as id, when i add new tags(which does not have the key property), the directive does not allow me to do so more than once .

[https://github.com/mbenford/ngTagsInput/issues/509](Something very similar), but no solution to this. Is their a workaround or i am missing something very silly.

**Comment by weihanchen** [comment]
I guess the source code default does not allow duplicate tags , we can see [the logic of valid code](https://github.com/mbenford/ngTagsInput/blob/master/src/tags-input.js#L75) and [compare function](https://github.com/weihanchen/ngTagsInput/blob/master/src/util.js#L37).
We can manually add key property as id after `tagAdded`, below code is my workaround solution：
```html
<tags-input ng-model="tags" key-property="id" display-property="text" on-tag-added="tagAdded($tag)"></tags-input>
```
```javascript
$scope.tags=[];
$scope.tagAdded = function($tag) {
     var currentId = 0;
     if ($scope.tags.length > 1) {
              var previousTagIdx = $scope.tags.indexOf($tag) - 1;
              var previousTag  = $scope.tags[previousTagIdx];
              currentId = previousTag.id + 1;
      }
      $tag.id = currentId;
}
```
[Plunker here](https://plnkr.co/edit/o0JZnP?p=preview)

**Comment by somangshu** [comment]
Yes, That makes sense. But i think even here we are adding an id to the new tag which is going to bomb my backend as it will think its an old entry though its not. Rather i think i will make a changes in the backend in order to remove all the duplicate keys while making an entry to resolve the ng dupes error. Anyways thanks for the help

**Comment by somangshu** [comment]
Yes, That makes sense. But i think even here we are adding an id to the new tag which is going to bomb my backend as it will think its an old entry though its not. Rather i think i will make a changes in the backend in order to remove all the duplicate keys while making an entry to resolve the ng dupes error. Anyways thanks for the help

**Comment by runderworld** [comment]
@somangshu if you don't want the `id` property passed to the server-side, `$http` will ignore anything you declare with "private" prefix `$$`.  In other words, rename your property `$$id` and it will be omitted from the `$http` payload.
