### ISSUE TITLE
object within a object

### ISSUE THREAD

**Issue by kreeshna** [mbenford/ngTagsInput#780]
I have array of objects which have another object from which I have to take the property for display-property. I tried "display-property= "person.Title" " but its not working. How to resolve it?

Object {__metadata: Object, person: Object, __proto__: Object}
Title, which I want as display property is in person object.
I also tried to return .person from the return object in auto-complete function, but no use.

Thanks for great help!

**Comment by DevDmitryHub** [comment]
Display property applies to iterator value without computing. 
So for your case I advise you to use a custom `template` for display tags where you can define any tag sructure.

**Comment by mbenford** [comment]
The best approach is to use a custom template, as mentioned by @DevDmitryHub. More information on how to use custom templates can be found [here](http://mbenford.github.io/ngTagsInput/documentation/guides/custom-templates).
