### ISSUE TITLE
Release a new version which includes the XSS vulnerability fix

### ISSUE THREAD

**Issue by koczkatamas** [mbenford/ngTagsInput#787]
This vulnerability was fixed 10 months ago: https://github.com/mbenford/ngTagsInput/commit/bbc1f584acc8e154c04969180baddbd8f11f9c8c , but there is no new release since then.

Everybody who use your component from the release build, or one of the package managers are potentially vulnerable to this security issue without even noticing it.

Please release a new version which includes the security fix. Thanks.

**Comment by mbenford** [comment]
Thanks for the reminder. I have no idea why that fix wasn't published yet. Well, it's done now.

**Comment by koczkatamas** [comment]
Thanks!

Do you know why Github shows 3.1.1 as the latest release instead of 3.1.2 on the Releases page ( https://github.com/mbenford/ngTagsInput/releases )?
