### ISSUE TITLE
There seems to be a bug when writing tags in Korean on iOS.

### ISSUE THREAD

**Issue by Jimin77** [mbenford/ngTagsInput#794]
First, I can not speak English well, so the context can be strange. I hope you understand.

I am developing with the ngTagsInput function.
However, I have an unusual bug and I register an issue.

The same problem also appears in the ngTagsInput demo page.

1. Demo page access on ios mobile. (http://mbenford.github.io/ngTagsInput/demos)
2. Enter 'simple tags input' in Korean. input text --> '한태그'
3. Press return key, enter '한태' and press return key again.
4. If so, it will be listed as '그한태' in the tag.
    That is, the last string entered before the last tag is registered together.
5. In this demo page, the minimum number of characters is 3 characters. Therefore, when inputting '한태' and pressing return key, an error should be displayed.

How should I handle it? 
Please advise.

**Comment by IosAnkitsingh** [comment]
Hi,
    I am facing this same issue in my IONIC App,
    Please suggest if anyone have any solution for this issue.

Thanks!!!
Ankit Singh
![img_5421](https://user-images.githubusercontent.com/31728882/30158302-7a093272-93e2-11e7-9841-35bef1d3d5f6.jpg)
