### ISSUE TITLE
placeholder doesn't get an expression

### ISSUE THREAD

**Issue by Urigo** [mbenford/ngTagsInput#8]
For example if i want to use angular-translate for the placeholder in the input:
placeholder="{{ 'ADD_CATEGORIES' | translate }}"
if won't get the value (although that in regular input it does work fine).

Thanks man, good job

**Comment by renanlecaro** [comment]
Is it just me, or this is again the case in the current version @mbenford ? I've been trying to put an ng-translate interpolation in the placeholder attribute with no success.
