### ISSUE TITLE
Select all matching option from autocomplete

### ISSUE THREAD

**Issue by bijaykush** [mbenford/ngTagsInput#803]
Hi Ben,
I have been using ng-tags input for sometime, I would like to add "select all" option for it which would help select all the matching items from the autocomplete options. 
Approach: I tried by adding a button aside ng tag input field, and adding a function to select all the matching items. But the problem is, I am not being able to populate  all the selected tags in the ngTag input.
Can you let me know how to do it? And help would be appreciated.

Thanks,
Bijay Kushawaha

**Comment by Christian-X** [comment]
I've accomplished this function. 
In the autoComplete-calculate function, i add a meta-tag with some special fields (for styling) to the completion list. (I add it first, so it will be displayed as first option)
something like:
```
$scope.autoComplete = function(key, query) {
   var MAX_COMPLETIONS = 20;
   var result=[];
   //Calculate possible completions
   if (result.length < MAX_COMPLETIONS && result.length > 2) {
       result.splice(0, 0, "ALL:" + query);
  }
}
'''

Then, i register a callback on onTagAdding :
```
$scope.onTagAdding = function(key, tag) {
				if (tag.text.indexOf("ALL:") == 0) {
					var query = tag.text.substr(4);
					var re = new RegExp(query.replace("*", ".*"), 'i');
					var result = [];
					$scope.filterValues[key].forEach(function(el) {
						if (re.test(el.value)) {
							$scope.filterSpec[key].push({
								"text" : el.value
							});
						}
					});
					return false;
				}
				return true;
			}
```

i prevent the normal adding of the element, but add elements myself as appropiate.

**Comment by bijaykush** [comment]
@Christian-X, It worked fine for me. Great solution. Thanks a lot.
