### ISSUE TITLE
Placeholder disappear when it is loaded in a directive and enabled with a click

### ISSUE THREAD

**Issue by angeloh** [mbenford/ngTagsInput#84]
Hi

If I override css of input box, the placeholder text will disappear when page is just loaded becuase the width on input box = 0. What can I do to fix it? 

This is my overriding css:
.ngTagsInput .tags {
  -webkit-appearance: none;
  -webkit-border-radius: 6px;
  -moz-border-radius: 6px;
  border-radius: 6px;
  box-shadow: none;
  min-height: 50px;
  width: 86%;
  margin: auto;
  border: 2px solid #bdc3c7;
  font: 22px/1.5 'Open Sans', Helvetica, sans-serif;
}

.ngTagsInput .tags .tag-input {
  height: auto;
  font: 18px/2 'Open Sans', Helvetica, sans-serif;
}

.ngTagsInput .tags .tag-item {
  height: auto;
}

.ngTagsInput .tags .tag-item span {
  font: 22px/1.5 'Open Sans', Helvetica, sans-serif;
}

![screenshot 2014-02-20 21 14 55](https://f.cloud.github.com/assets/304674/2227080/2b47ef52-9ab7-11e3-8fe0-d0077ef928fe.png)

**Comment by adithyasai** [comment]
I dont want the tags to be with in the input field and so iam placing them out of the input filed. and when i type something on the input filed it is resizing the texbox. and i dont want that to happen. i have tried couple of solution to stop the autosize but none of them worked. how to stop "autosize" directive to resize my textbox based on the input. i want to have a fixed width for my input field. 
Kindly solve this issue
