### ISSUE TITLE
Do not display placeholder when max-tags has been reached

### ISSUE THREAD

**Issue by steve-lorimer** [mbenford/ngTagsInput#88]
when `max-tags` has been reached, the `placeholder` text should not be displayed, as it is now no longer possible to "Add a tag"

**Comment by 7Prasanna** [comment]
i have used it .. working fine.. thnx

**Comment by zardaloop** [comment]
I have used kevinrenskers solution and modified it  a little bit to work with version 3.1.1
tags-input.has-tags .tags .input {
    display: none !important;
}

tags-input.has-tags .tags ul {
    height: 26px;
}


<tags-input ng-class="{'has-tags': myModel.length > 0 }" ng-model="myModel.length">

**Comment by sajithk** [comment]
My solution based on kevinrenskers solution and directive's maxTags parameter (maxTagsAllowed should be one less that required tags count),

```
 tags-input.ng-invalid-max-tags .tags{
    cursor: default !important;
  }  
  tags-input.ng-invalid-max-tags .tags .input {
    display: none !important;
  }  
```

`<tags-input max-tags="maxTagsAllowed" ng-model="myModel.length">`
