### ISSUE TITLE
auto complete array of suggestions problem

### ISSUE THREAD

**Issue by augkamil** [mbenford/ngTagsInput#89]
Hi,

I wanted to have suggestions in <code><auto-complete></code> to use as a source a filtered array. I made a function that returns an array of strings 

```
$scope.filteredTagsAutoComplete = (query) ->
    $filter('filter') $scope.all.tags, query
```

and I putted it in <code>source</code> attribute

```
<tags-input class="span12" ng-model="comment.tags" placeholder="type tags here" min-length="2" on-tag-added="addTag($tag)" on-tag-removed="removeTag($tag)">
   <auto-complete
     source="filteredTagsAutoComplete($query)"
     highlightMatchedText="false">
     </auto-complete>
</tags-input>

```

But I receive an error <code>Object [object Array] has no method 'then'</code>
at line ng-tags-input.js:333:25

Please help me - I don't know what's happening... Maybe I'm doing something wrong here.

**Comment by donaldparker** [comment]
@mbenford what does $q refer to in your example?
