### ISSUE TITLE
Support for displaying multiple properties in the autocomplete dropdown

### ISSUE THREAD

**Issue by sjain07** [mbenford/ngTagsInput#98]
Since this now supports arrays of objects would it be possible to add support for displaying multiple properties in the autocomplete dropdown.

im using this for selecting email ids in an auto complete and id like to show both the name and the email id as a part of the dropdown.

If possible another thing that would be useful is if only the name were displayed in the tag. I can currently circumvent this by passing the string in the required format , but i would prefer it to be two separate fields

**Comment by jvega-190** [comment]
Hey, I know this is from a long time ago, I got a custom template for the autocomplete showing multiple properties of the object, but I can only search by one property, is there a way of searching by different properties of the object?
