### ISSUE TITLE
Custom template support for autocomplete

### ISSUE THREAD

**Issue by mbenford** [mbenford/ngTagsInput#99]
The autocomplete directive should have support for custom templates so additional information could be displayed instead of just a list of strings.

**Comment by inguansoft** [comment]
Is there any progress on this feature?  I would like to help to make it happen.

I think the template needs to follow the way angular handles templates: 'templateUrl'

and this should be extended not just to autocomplete lists but to the tags themselves.

**Comment by mbenford** [comment]
@inguansoft As a matter of fact, I'm working on this feature right now. I'm using the `ngInclude` directive in order to load the custom template. Take a look at [this prototype](http://plnkr.co/edit/tesDEo1qPoIwte1cVkLW?p=preview) I created to understand the solution better.

And I agree with you that the tags should also support a custom template. But one step at a time. ;)

**Comment by inguansoft** [comment]
neat, take a look at this PR, The functionality is working but I need to fix the unit test and remove the build files.   I wanted to share with you the progress so that I dint invest too much time on showing the status.    I'm working on this because We needed very badly for a product We are building.

PR:
https://github.com/mbenford/ngTagsInput/pull/386

**Comment by mbenford** [comment]
@inguansoft I took a look at your PR and I guess it resembles my own implementation at some points.

I've pushed my changes to a [remote branch](https://github.com/mbenford/ngTagsInput/tree/feat/autocomplete-custom-template) so you can check them out. I appreciate if you could share your feedback. It's not final yet, but it's very close. And don't mind the commit messages; I'll squash them into one later.

Here's how to use the new feature:

```html
<tags-input ng-model="tags">
  <auto-complete source="loadSuggestions($query)" 
                 template="template-name-or-url"></auto-complete>
</tags-input>
```

The `template` option can be set to either a url or an id pointing to a script tag. Here's an example:

```html
<script type="text/ng-template" id="template1">
...
</script>
```

The template will be bound to an isolate scope containing the following:

- `data`: The match returned by the `source` option.
- `highlight`: A function that highlights the matched text. You need to provide it with some text. 
- `getDisplayText`: A function that returns the text to be displayed according to the `display-property` option.

The `test-page.html` file was updated to use all of the above, if you need an working example.

**Comment by rajesh-rns** [comment]
@mbenford  - I also need this functionality of customizing the template for one of the projects I am working on. Need to show two separate lists one below the other (normal options and the favorite options) separated by a divider and allow the user to select from any of the two. Would you be ready with the final version today. I have to start working on this tomorrow so that would help :-)!

**Comment by mbenford** [comment]
@rajesh-rns Probably not. :( 

It's worth saying that my implementation allows you to customize each *element* of the autocomplete list., not the entire thing. It will be tricky to do what you want, if at all possible. I guess what you need is *to group* elements, but that feature isn't available yet (it's [documented](https://github.com/mbenford/ngTagsInput/issues/61), though).

**Comment by inguansoft** [comment]
neat,  I'll have a look at it,  We would love to keep in line with the core library.      The PR I got had the wiring for the tag as well + adding a regexp checker for items not coming from autocomplete, I'll try to organize them together in a separate PR.   Huge thanks for sharing such amazing library!

**Comment by ronaldohoch** [comment]
Thanks for this awesome feature, but how auto-complete works in this case?

For example, i have this array:

`[  {
    "group": "aaa",
    "id": "-1",
    "name": "Adquiridos (Pagos)"
  },
  {
    "group": "bbb",
    "id": "-2",
    "name": "Captados (Concluídos)"
  }]`

So, how can I put the "group" property before all of same type, like this other plugin(image below)

![image](https://cloud.githubusercontent.com/assets/2287371/24912472/9396a8d6-1ea4-11e7-82bd-0884fa21c337.png)
